<?php

namespace App\Omnify\Modules\OrderItemTopping\Locales;

/**
 * Localized display names for OrderItemTopping.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class OrderItemToppingLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Order Item Topping',
        'ja' => '注文アイテムトッピング',
        'vi' => 'Topping trong Order Item',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'quantity' => [
            'en' => 'Quantity',
            'ja' => '数量',
            'vi' => 'Số lượng',
        ],
        'waived_quantity' => [
            'en' => 'Waived Quantity',
            'ja' => '無料数量',
            'vi' => 'Số lượng được miễn',
        ],
        'status' => [
            'en' => 'Status',
            'ja' => 'ステータス',
            'vi' => 'Trạng thái',
        ],
        'unit_price' => [
            'en' => 'Unit Price',
            'ja' => '単価',
            'vi' => 'Đơn giá',
        ],
        'note' => [
            'en' => 'Note',
            'ja' => '備考',
            'vi' => 'Ghi chú',
        ],
    ];
}
