<?php

namespace App\Omnify\Modules\TillCashEvent\Locales;

/**
 * Localized display names for TillCashEvent.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class TillCashEventLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Till Cash Event',
        'ja' => '現金イベント',
        'vi' => 'Giao dịch tiền mặt giữa ca',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'event_type' => [
            'en' => 'Event Type',
            'ja' => '種別',
            'vi' => 'Loại',
        ],
        'amount' => [
            'en' => 'Amount',
            'ja' => '金額',
            'vi' => 'Số tiền',
        ],
        'currency_code' => [
            'en' => 'Currency',
            'ja' => '通貨',
            'vi' => 'Tiền tệ',
        ],
        'reason' => [
            'en' => 'Reason',
            'ja' => '理由',
            'vi' => 'Lý do',
        ],
        'reference_no' => [
            'en' => 'Reference No',
            'ja' => '参照番号',
            'vi' => 'Mã tham chiếu',
        ],
        'occurred_at' => [
            'en' => 'Occurred At',
            'ja' => '発生日時',
            'vi' => 'Thời điểm',
        ],
        'performed_by_id' => [
            'en' => 'Performed By',
            'ja' => '実行者',
            'vi' => 'Người thực hiện',
        ],
        'manual_adjustment' => [
            'en' => 'Manual Adjustment',
            'ja' => '手動調整',
            'vi' => 'Điều chỉnh thủ công',
        ],
    ];
}
