<?php

namespace App\Omnify\Modules\NotificationDigestPreference\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\User;
use App\Omnify\Modules\NotificationDigestPreference\Locales\NotificationDigestPreferenceLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * NotificationDigestPreferenceBaseModel
 *
 * @property int $user_id
 * @property string $cadence
 * @property string $delivery_time
 * @property string $timezone
 * @property int|null $weekday
 * @property array $include_priorities
 * @property mixed|null $last_sent_at
 */
class NotificationDigestPreferenceBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;

    /**
     * The table associated with the model.
     */
    protected $table = 'notification_digest_preferences';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = NotificationDigestPreferenceLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = NotificationDigestPreferenceLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'user_id',
        'cadence',
        'delivery_time',
        'timezone',
        'weekday',
        'include_priorities',
        'last_sent_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'weekday' => 'integer',
            'include_priorities' => 'array',
            'last_sent_at' => 'datetime',
        ];
    }

    /**
     * Get the user that owns this model.
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}
