<?php

namespace App\Omnify\Modules\Denomination\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\Organization;
use App\Models\TillCashDenominationCount;
use App\Omnify\Enums\DenominationKindEnum;
use App\Omnify\Modules\Denomination\Locales\DenominationLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * DenominationBaseModel
 *
 * @property string $currency_code
 * @property float $value
 * @property DenominationKindEnum $kind
 * @property string|null $label
 * @property int $sort_order
 * @property bool $is_active
 * @property int|null $organization_id
 */
class DenominationBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;

    /**
     * The table associated with the model.
     */
    protected $table = 'denominations';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = DenominationLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = DenominationLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'currency_code',
        'value',
        'kind',
        'label',
        'sort_order',
        'is_active',
        'organization_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'value' => 'decimal:2',
            'kind' => DenominationKindEnum::class,
            'sort_order' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Get the organization that owns this model.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }

    /**
     * Auto-generated inverse of TillCashDenominationCount.denomination (ManyToOne).
     */
    public function tillCashDenominationCounts(): HasMany
    {
        return $this->hasMany(TillCashDenominationCount::class, 'denomination_id');
    }
}
