<?php

namespace App\Omnify\Modules\BranchScheduleOverride\Locales;

/**
 * Localized display names for BranchScheduleOverride.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class BranchScheduleOverrideLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Branch Schedule Override',
        'ja' => '店舗スケジュール上書き',
        'vi' => 'Ghi đè lịch trình chi nhánh',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'start_time' => [
            'en' => 'Start Time (Override)',
            'ja' => '開始時刻（上書き）',
            'vi' => 'Giờ bắt đầu (ghi đè)',
        ],
        'days_of_week' => [
            'en' => 'Days of Week (Override)',
            'ja' => '曜日（上書き）',
            'vi' => 'Ngày trong tuần (ghi đè)',
        ],
        'end_time' => [
            'en' => 'End Time (Override)',
            'ja' => '終了時刻（上書き）',
            'vi' => 'Giờ kết thúc (ghi đè)',
        ],
        'start_date' => [
            'en' => 'Start Date (Override)',
            'ja' => '開始日（上書き）',
            'vi' => 'Ngày bắt đầu (ghi đè)',
        ],
        'end_date' => [
            'en' => 'End Date (Override)',
            'ja' => '終了日（上書き）',
            'vi' => 'Ngày kết thúc (ghi đè)',
        ],
        'days_of_month' => [
            'en' => 'Days of Month (Override)',
            'ja' => '日付（上書き）',
            'vi' => 'Ngày trong tháng (ghi đè)',
        ],
    ];
}
