<?php

namespace App\Omnify\Modules\CashDeviceTransaction\Locales;

/**
 * Localized display names for CashDeviceTransaction.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class CashDeviceTransactionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Cash Device Transaction',
        'ja' => '釣銭機取引',
        'vi' => 'Lượt thu tiền mặt',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'glory_transaction_id' => [
            'en' => 'Glory Transaction ID',
            'ja' => '取引ID',
            'vi' => 'Mã giao dịch máy',
        ],
        'outcome' => [
            'en' => 'Outcome',
            'ja' => '取引結果',
            'vi' => 'Kết cục',
        ],
        'requested_minor' => [
            'en' => 'Requested (minor)',
            'ja' => '請求額',
            'vi' => 'Yêu cầu thu',
        ],
        'deposited_minor' => [
            'en' => 'Deposited (minor)',
            'ja' => '投入額',
            'vi' => 'Khách đã bỏ vào',
        ],
        'change_minor' => [
            'en' => 'Change Due (minor)',
            'ja' => '釣銭額',
            'vi' => 'Tiền thối phải trả',
        ],
        'dispensed_minor' => [
            'en' => 'Dispensed (minor)',
            'ja' => '出金額',
            'vi' => 'Máy đã nhả',
        ],
        'error_title' => [
            'en' => 'Error Title',
            'ja' => 'エラー種別',
            'vi' => 'Loại lỗi',
        ],
        'machine_seq_no' => [
            'en' => 'Machine Seq No',
            'ja' => '機器連番',
            'vi' => 'Số thứ tự máy',
        ],
        'started_at' => [
            'en' => 'Started At',
            'ja' => '開始日時',
            'vi' => 'Bắt đầu',
        ],
        'finished_at' => [
            'en' => 'Finished At',
            'ja' => '終了日時',
            'vi' => 'Kết thúc',
        ],
    ];
}
