<?php

namespace App\Omnify\Modules\PeripheralDevice\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\Branch;
use App\Models\CashDeviceErrorEvent;
use App\Models\CashDeviceInventorySnapshot;
use App\Models\CashDeviceTransaction;
use App\Models\Device;
use App\Models\Organization;
use App\Omnify\Modules\PeripheralDevice\Locales\PeripheralDeviceLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * PeripheralDeviceBaseModel
 *
 * @property int $organization_id
 * @property int $branch_id
 * @property string $name
 * @property string $type
 * @property bool $is_active
 * @property array|null $metadata
 * @property string|null $secret
 * @property int|null $registered_by_device_id
 */
class PeripheralDeviceBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;

    /**
     * The table associated with the model.
     */
    protected $table = 'peripheral_devices';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = PeripheralDeviceLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = PeripheralDeviceLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'organization_id',
        'branch_id',
        'name',
        'type',
        'is_active',
        'metadata',
        'secret',
        'registered_by_device_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'is_active' => 'boolean',
            'metadata' => 'array',
        ];
    }

    /**
     * Get the organization that owns this model.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }

    /**
     * Get the branch that owns this model.
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    /**
     * Get the registeredByDevice that owns this model.
     */
    public function registeredByDevice(): BelongsTo
    {
        return $this->belongsTo(Device::class, 'registered_by_device_id');
    }

    /**
     * Auto-generated inverse of CashDeviceErrorEvent.peripheralDevice (ManyToOne).
     */
    public function cashDeviceErrorEvents(): HasMany
    {
        return $this->hasMany(CashDeviceErrorEvent::class, 'peripheral_device_id');
    }

    /**
     * Auto-generated inverse of CashDeviceInventorySnapshot.peripheralDevice (ManyToOne).
     */
    public function cashDeviceInventorySnapshots(): HasMany
    {
        return $this->hasMany(CashDeviceInventorySnapshot::class, 'peripheral_device_id');
    }

    /**
     * Auto-generated inverse of CashDeviceTransaction.peripheralDevice (ManyToOne).
     */
    public function cashDeviceTransactions(): HasMany
    {
        return $this->hasMany(CashDeviceTransaction::class, 'peripheral_device_id');
    }
}
