<?php

namespace App\Omnify\Modules\StockLevel\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\MaterialLotResource;
use App\Http\Resources\MaterialResource;
use App\Http\Resources\ProductSkuResource;
use App\Http\Resources\WarehouseResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class StockLevelResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'warehouse_id' => $this->warehouse_id,
            'warehouse' => $this->whenLoaded('warehouse', fn () => new WarehouseResource($this->warehouse)),
            'product_sku_id' => $this->product_sku_id,
            'productSku' => $this->whenLoaded('productSku', fn () => new ProductSkuResource($this->productSku)),
            'material_id' => $this->material_id,
            'material' => $this->whenLoaded('material', fn () => new MaterialResource($this->material)),
            'material_lot_id' => $this->material_lot_id,
            'materialLot' => $this->whenLoaded('materialLot', fn () => new MaterialLotResource($this->materialLot)),
            'quantity' => $this->quantity,
            'unit' => $this->unit,
            'min_stock' => $this->min_stock,
            'max_stock' => $this->max_stock,
            'alert_enabled' => $this->alert_enabled,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
