<?php

namespace App\Omnify\Modules\TillTenderType\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\Branch;
use App\Models\Organization;
use App\Models\TillSettlementTenderDetail;
use App\Omnify\Modules\TillTenderType\Locales\TillTenderTypeLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * TillTenderTypeBaseModel
 *
 * @property string $tender_key
 * @property string $name
 * @property string $category
 * @property string|null $parent_tender_key
 * @property string $currency_code
 * @property string|null $payment_method_code
 * @property bool $is_expected_anchor
 * @property bool $requires_terminal_total
 * @property int $sort_order
 * @property bool $is_active
 * @property int|null $branch_id
 * @property int $organization_id
 */
class TillTenderTypeBaseModel extends BaseModel implements TranslatableContract
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;
    use Translatable;

    /**
     * The table associated with the model.
     */
    protected $table = 'till_tender_types';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = TillTenderTypeLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = TillTenderTypeLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are translatable.
     *
     * @var array<int, string>
     */
    public $translatedAttributes = [
        'name',
    ];

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'tender_key',
        'name',
        'category',
        'parent_tender_key',
        'currency_code',
        'payment_method_code',
        'is_expected_anchor',
        'requires_terminal_total',
        'sort_order',
        'is_active',
        'branch_id',
        'organization_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'is_expected_anchor' => 'boolean',
            'requires_terminal_total' => 'boolean',
            'sort_order' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    /**
     * Get the branch that owns this model.
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    /**
     * Get the organization that owns this model.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }

    /**
     * Auto-generated inverse of TillSettlementTenderDetail.tenderType (ManyToOne).
     */
    public function tillSettlementTenderDetails(): HasMany
    {
        return $this->hasMany(TillSettlementTenderDetail::class, 'tender_type_id');
    }
}
