<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('material_batches', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('batch_code', 50)->comment('Batch Code');
            $table->uuid('warehouse_id')->comment('Warehouse');
            $table->uuid('material_id')->comment('Output Material ID');
            $table->uuid('recipe_id')->nullable()->comment('Recipe');
            $table->decimal('multiplier', 10, 4)->default(1)->comment('Multiplier');
            $table->decimal('planned_yield', 15, 4)->comment('Planned Yield');
            $table->decimal('actual_yield', 15, 4)->nullable()->comment('Actual Yield');
            $table->text('yield_variance_reason')->nullable()->comment('Yield Variance Reason');
            $table->string('yield_unit', 50)->comment('Yield Unit');
            $table->string('status', 50)->default('draft')->comment('Status');
            $table->uuid('stock_out_transaction_id')->nullable()->comment('Stock Out Transaction');
            $table->uuid('stock_in_transaction_id')->nullable()->comment('Stock In Transaction');
            $table->text('note')->nullable()->comment('Note');
            $table->uuid('created_by_id')->comment('Created By');
            $table->uuid('approved_by_id')->nullable()->comment('Approved By');
            $table->timestamp('approved_at')->nullable()->comment('Approved At');
            $table->timestamp('started_at')->nullable()->comment('Started At');
            $table->timestamp('completed_at')->nullable()->comment('Completed At');
            $table->dateTime('expiry_date')->nullable()->comment('Expiry Date');
            $table->uuid('output_lot_id')->nullable()->comment('Output Lot');
            $table->uuid('organization_id')->comment('Organization');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->foreign('warehouse_id')->references('id')->on('warehouses')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->foreign('recipe_id')->references('id')->on('recipes')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->foreign('organization_id')->references('id')->on('organizations')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('warehouse_id');
            $table->index('recipe_id');
            $table->index('output_lot_id');
            $table->index('organization_id');
            $table->unique(['organization_id', 'batch_code', 'deleted_at'], 'uq_material_batch_org_code');
            $table->index(['organization_id', 'status']);
            $table->index(['warehouse_id', 'material_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('material_batches');
    }
};
