<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('customer_point_entries', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->integer('points')->comment('Points');
            $table->string('kind', 50)->comment('Kind');
            $table->string('note', 255)->nullable()->comment('Note');
            $table->timestamp('expires_at')->nullable()->comment('Expires At');
            $table->uuid('customer_id')->comment('Customer');
            $table->uuid('organization_id')->nullable()->comment('Organization');
            $table->uuid('customer_order_id')->nullable()->comment('Customer Order');
            $table->uuid('coupon_id')->nullable()->comment('Coupon');
            $table->uuid('point_reward_id')->nullable()->comment('Point Reward');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->foreign('customer_id')->references('id')->on('customers')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('organization_id')->references('id')->on('organizations')->onDelete('SET NULL')->onUpdate('cascade');
            $table->foreign('customer_order_id')->references('id')->on('customer_orders')->onDelete('SET NULL')->onUpdate('cascade');
            $table->foreign('coupon_id')->references('id')->on('coupons')->onDelete('SET NULL')->onUpdate('cascade');
            $table->foreign('point_reward_id')->references('id')->on('point_rewards')->onDelete('SET NULL')->onUpdate('cascade');
            $table->index('customer_id');
            $table->index('organization_id');
            $table->index('customer_order_id');
            $table->index('coupon_id');
            $table->index('point_reward_id');
            $table->index(['customer_id', 'created_at']);
            $table->unique(['customer_order_id', 'kind'], 'customer_point_entries_order_kind_unique');
            $table->index('kind');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('customer_point_entries');
    }
};
