<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('production_orders', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('order_code', 50)->comment('Order Code');
            $table->uuid('warehouse_id')->comment('Warehouse');
            $table->uuid('output_variant_id')->comment('Output Variant');
            $table->decimal('planned_quantity', 15, 4)->comment('Planned Quantity');
            $table->decimal('actual_quantity', 15, 4)->nullable()->comment('Actual Quantity');
            $table->string('output_unit', 50)->comment('Output Unit');
            $table->decimal('recipe_multiplier', 10, 4)->default(1)->comment('Recipe Multiplier');
            $table->string('status', 50)->default('draft')->comment('Status');
            $table->uuid('stock_out_transaction_id')->nullable()->comment('Stock Out Transaction');
            $table->uuid('stock_in_transaction_id')->nullable()->comment('Stock In Transaction');
            $table->text('note')->nullable()->comment('Note');
            $table->uuid('created_by_id')->comment('Created By');
            $table->uuid('approved_by_id')->nullable()->comment('Approved By');
            $table->timestamp('approved_at')->nullable()->comment('Approved At');
            $table->timestamp('started_at')->nullable()->comment('Started At');
            $table->timestamp('completed_at')->nullable()->comment('Completed At');
            $table->uuid('organization_id')->comment('Organization');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->foreign('warehouse_id')->references('id')->on('warehouses')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->foreign('output_variant_id')->references('id')->on('product_skus')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->foreign('organization_id')->references('id')->on('organizations')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('warehouse_id');
            $table->index('output_variant_id');
            $table->index('organization_id');
            $table->unique('order_code');
            $table->index(['organization_id', 'status']);
            $table->index(['warehouse_id', 'output_variant_id']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('production_orders');
    }
};
