<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('material_lot_reservations', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('material_lot_id')->comment('Material Lot');
            $table->decimal('qty_reserved', 18, 4)->comment('Quantity Reserved');
            $table->uuid('reserved_by_id')->comment('Reserved By');
            $table->timestamp('expected_consume_at')->nullable()->comment('Expected Consume At');
            $table->uuid('material_batch_id')->nullable()->comment('Material Batch');
            $table->string('status', 16)->comment('Status');
            $table->text('reason')->nullable()->comment('Reason');
            $table->uuid('organization_id')->comment('Organization ID');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->foreign('material_lot_id')->references('id')->on('material_lots')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('reserved_by_id')->references('id')->on('users')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->foreign('material_batch_id')->references('id')->on('material_batches')->onDelete('SET NULL')->onUpdate('cascade');
            $table->index('material_lot_id');
            $table->index('reserved_by_id');
            $table->index('material_batch_id');
            $table->index(['material_lot_id', 'status']);
            $table->index(['status', 'expected_consume_at']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('material_lot_reservations');
    }
};
