<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('sku', 50)->nullable()->comment('SKU');
            $table->string('name', 100)->nullable()->comment('Name');
            $table->string('slug', 100)->nullable()->comment('Slug');
            $table->text('description')->nullable()->comment('Description');
            $table->string('image_url', 500)->nullable()->comment('Image URL');
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->boolean('is_featured')->default(false)->comment('Featured');
            $table->uuid('parent_id')->nullable()->comment('Parent Category');
            $table->uuid('organization_id')->comment('Organization');
            $table->uuid('brand_id')->comment('Brand');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->foreign('parent_id')->references('id')->on('categories')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('organization_id')->references('id')->on('organizations')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('brand_id')->references('id')->on('brands')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('parent_id');
            $table->index('organization_id');
            $table->index('brand_id');
            $table->unique(['organization_id', 'sku']);
            $table->index(['brand_id', 'sku']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('categories');
    }
};
