<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('till_cash_events', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('event_type', 50)->comment('Event Type');
            $table->decimal('amount', 15, 2)->comment('Amount');
            $table->string('currency_code', 3)->default('JPY')->comment('Currency');
            $table->text('reason')->nullable()->comment('Reason');
            $table->string('reference_no', 100)->nullable()->comment('Reference No');
            $table->timestamp('occurred_at')->comment('Occurred At');
            $table->uuid('performed_by_id')->nullable()->comment('Performed By');
            $table->boolean('manual_adjustment')->default(false)->comment('Manual Adjustment');
            $table->uuid('session_id')->comment('Session');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->foreign('session_id')->references('id')->on('till_sessions')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('session_id');
            $table->index(['session_id', 'occurred_at']);
            $table->index(['session_id', 'event_type']);
            $table->index('event_type');
            $table->index('manual_adjustment');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('till_cash_events');
    }
};
