<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('workstation_log_requests', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('device_id')->comment('Device ID');
            $table->uuid('branch_id')->comment('Branch ID');
            $table->uuid('organization_id')->comment('Organization ID');
            $table->uuid('requested_by_user_id')->nullable()->comment('Requested By');
            $table->dateTime('window_from')->comment('Window From');
            $table->dateTime('window_to')->comment('Window To');
            $table->integer('max_records')->comment('Max Records');
            $table->string('status', 50)->comment('Status');
            $table->dateTime('expires_at')->comment('Expires At');
            $table->dateTime('fulfilled_at')->nullable()->comment('Fulfilled At');
            $table->integer('received_count')->comment('Received Count');
            $table->integer('rejected_count')->comment('Rejected Count');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['device_id', 'status']);
            $table->index(['branch_id', 'created_at']);
            $table->index(['status', 'expires_at']);
            $table->index('status');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('workstation_log_requests');
    }
};
