<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('topping_group_items', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('topping_group_id')->comment('Topping Group');
            $table->uuid('product_id')->comment('Product');
            $table->integer('sort_order')->default(0)->comment('Sort Order');
            $table->boolean('is_default')->default(false)->comment('Default Included');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->uuid('created_by_id')->nullable();
            $table->uuid('updated_by_id')->nullable();
            $table->foreign('topping_group_id')->references('id')->on('topping_groups')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('product_id')->references('id')->on('products')->onDelete('RESTRICT')->onUpdate('cascade');
            $table->index('topping_group_id');
            $table->index('product_id');
            $table->unique(['topping_group_id', 'product_id']);
            $table->index('sort_order');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('topping_group_items');
    }
};
