<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('print_image_rasters', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->uuid('asset_id')->comment('Asset');
            $table->integer('max_width_dots')->unsigned()->comment('Max Width Dots');
            $table->integer('width_dots')->unsigned()->comment('Width Dots');
            $table->integer('height_dots')->unsigned()->comment('Height Dots');
            $table->mediumText('data')->comment('Bitmap Data');
            $table->string('content_hash', 64)->comment('Content Hash');
            $table->integer('byte_length')->unsigned()->comment('Byte Length');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->foreign('asset_id')->references('id')->on('print_image_assets')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('asset_id');
            $table->unique(['asset_id', 'max_width_dots'], 'print_image_rasters_asset_width_unique');
            $table->index('content_hash', 'print_image_rasters_content_hash_idx');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('print_image_rasters');
    }
};
