<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('order_conditions', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('conditionable_type', 20)->comment('Conditionable Type');
            $table->uuid('conditionable_id')->comment('Conditionable ID');
            $table->string('type', 20)->comment('Type');
            $table->string('source', 30)->nullable()->comment('Source');
            $table->string('label', 100)->comment('Label');
            $table->decimal('rate', 5, 2)->nullable()->comment('Rate (%)');
            $table->decimal('amount', 15, 2)->comment('Amount');
            $table->decimal('taxable_base', 15, 2)->nullable()->comment('Taxable Base');
            $table->string('currency_code', 8)->comment('Currency');
            $table->json('meta')->nullable()->comment('Meta');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index(['conditionable_type', 'conditionable_id']);
            $table->index('type');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('order_conditions');
    }
};
