<?php

/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 * KHÔNG ĐƯỢC SỬA FILE NÀY!
 *
 * This file is AUTO-GENERATED by Omnify.
 * Any manual changes will be OVERWRITTEN on next generation.
 *
 * To modify: Edit the schema YAML file and run: omnify generate
 *
 * @generated by omnify-go
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('recipes', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('sku', 50)->nullable()->comment('Recipe SKU');
            $table->string('name', 255)->nullable()->comment('Recipe Name');
            $table->text('description')->nullable()->comment('Description');
            $table->uuid('material_id')->nullable()->comment('Material');
            $table->decimal('output_quantity', 10, 4)->default(1)->comment('Output Quantity');
            $table->string('output_unit', 50)->nullable()->comment('Output Unit');
            $table->json('ingredients')->nullable()->comment('Ingredients');
            $table->integer('preparation_time')->nullable()->comment('Preparation Time');
            $table->decimal('yield_variance_tolerance_pct', 5, 2)->nullable()->default(0)->comment('Yield Variance Tolerance (%)');
            $table->text('instructions')->nullable()->comment('Instructions');
            $table->boolean('is_active')->default(true)->comment('Active');
            $table->string('approval_status', 50)->nullable()->default('draft')->comment('Approval Status');
            $table->uuid('approved_by_id')->nullable()->comment('Approved By');
            $table->dateTime('approved_at')->nullable()->comment('Approved At');
            $table->uuid('rejected_by_id')->nullable()->comment('Rejected By');
            $table->dateTime('rejected_at')->nullable()->comment('Rejected At');
            $table->text('rejection_reason')->nullable()->comment('Rejection Reason');
            $table->json('allergen_rollup')->nullable()->comment('Allergen Rollup');
            $table->dateTime('allergen_rollup_updated_at')->nullable()->comment('Allergen Rollup Updated At');
            $table->uuid('organization_id')->comment('Organization');
            $table->uuid('brand_id')->comment('Brand');
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->timestamp('deleted_at')->nullable();
            $table->uuid('created_by_id')->nullable();
            $table->foreign('material_id')->references('id')->on('materials')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('approved_by_id')->references('id')->on('users')->onDelete('SET NULL')->onUpdate('cascade');
            $table->foreign('rejected_by_id')->references('id')->on('users')->onDelete('SET NULL')->onUpdate('cascade');
            $table->foreign('organization_id')->references('id')->on('organizations')->onDelete('CASCADE')->onUpdate('cascade');
            $table->foreign('brand_id')->references('id')->on('brands')->onDelete('CASCADE')->onUpdate('cascade');
            $table->index('material_id');
            $table->index('approved_by_id');
            $table->index('rejected_by_id');
            $table->index('organization_id');
            $table->index('brand_id');
            $table->unique(['organization_id', 'sku']);
            $table->index(['brand_id', 'sku']);
            $table->index('approval_status');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('recipes');
    }
};
