<?php

namespace App\Models;

use App\Services\Printing\Enums\PrintConfidence;
use App\Services\Printing\Enums\PrintJobKind;
use App\Services\Printing\Enums\PrintJobStatus;
use App\Services\Printing\Enums\PrintTransport;
use App\Services\Printing\ReprintAdvisor;
use Database\Factories\PrintJobFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use LogicException;

/**
 * plan-052 (#1166) — one row per print command issued in a shop.
 *
 * TWO invariants live here, and both exist because the alternative hurts a
 * real shop:
 *
 * 1. **§1b journal mode.** A `ws_lan` row is a FACT that already happened at
 *    the shop. The workstation owns that queue — it dispatches, it retries, it
 *    decides. Cloud writes the row down and never touches it again. If Cloud
 *    could transition a ws_lan row, the ledger would become a second opinion
 *    about a print that Cloud did not perform, and the day Cloud is
 *    unreachable that second opinion would silently win (RISKS PR2).
 *
 * 2. **P-33 confidence is one-way.** `sent_only` means "the bytes left, and
 *    this machine cannot tell us more". Promoting that to `confirmed` invents
 *    knowledge nobody has. There is no sanctioned escape hatch for this one.
 *
 * Idempotency is the primary key: the id is generated by the CLIENT, so a
 * replayed journal batch collides in the DB rather than relying on an
 * application check that a concurrent retry can race past (P-09).
 */
class PrintJob extends Model
{
    use HasFactory;

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'id',
        'organization_id',
        'branch_id',
        'printer_id',
        'transport',
        'kind',
        'order_id',
        'payment_id',
        'payload',
        'reprint_no',
        'requested_by_id',
        'requested_via',
        'reprint_reason',
        // plan-053 TR-28 (#1171). `<scope>:<version>`; NULL = drawn by the
        // workstation's legacy formatter, which has no version.
        //
        // Listed here because this model is hand-written and does NOT extend
        // `PrintJobBaseModel` — the generated `$fillable` never reaches it. The
        // COLUMN is schema-driven (schemas/Backend/Device/PrintJob.yaml), so a
        // regen keeps it; this line is the one place the two have to be kept in
        // step by hand.
        'template_version',
        'status',
        'confidence',
        'attempts',
        'last_error',
        'acked_at',
        'printed_reported_at',
        'expires_at',
    ];

    protected function casts(): array
    {
        return [
            'transport' => PrintTransport::class,
            'kind' => PrintJobKind::class,
            'status' => PrintJobStatus::class,
            'confidence' => PrintConfidence::class,
            'payload' => 'array',
            'reprint_no' => 'integer',
            'attempts' => 'integer',
            'acked_at' => 'datetime',
            'printed_reported_at' => 'datetime',
            'expires_at' => 'datetime',
        ];
    }

    protected static function booted(): void
    {
        static::updating(function (self $job): void {
            // getRawOriginal: these columns are enum-cast, so getOriginal would
            // hand back an enum instance — compare the stored strings.
            if ($job->getRawOriginal('transport') === PrintTransport::WsLan->value) {
                throw new LogicException(
                    'ws_lan print jobs are journal rows (plan-052 §1b) — the workstation owns that queue; '
                    .'Cloud records the fact and never transitions it.',
                );
            }

            if ($job->getRawOriginal('confidence') === PrintConfidence::SentOnly->value
                && $job->confidence === PrintConfidence::Confirmed) {
                throw new LogicException(
                    'print confidence is one-way (plan-052 P-33): a machine that could not confirm the sheet '
                    .'came out never earns `confirmed` afterwards.',
                );
            }
        });

        static::deleting(function (self $job): void {
            if ($job->getRawOriginal('transport') === PrintTransport::WsLan->value) {
                throw new LogicException(
                    'ws_lan print jobs are append-only journal facts (plan-052 §1b) and can never be deleted.',
                );
            }
        });
    }

    protected static function newFactory(): PrintJobFactory
    {
        return PrintJobFactory::new();
    }

    public function isJournalRow(): bool
    {
        return $this->transport === PrintTransport::WsLan;
    }

    /**
     * plan-052 §4 (#1166) — "a money document was reprinted and nobody said
     * why". This is what replaced the 422: the reprint is never refused, so
     * the fact is recorded instead and the M2 reconcile report surfaces it.
     *
     * DERIVED, not stored. Every input is already a column on this row, so a
     * stored copy could only ever disagree with the row beside it — and it
     * would need a backfill for the history that predates the ruling. One rule,
     * one place: {@see ReprintAdvisor::warnedWithoutReason()}, which the POS
     * pre-flight advice and this accessor both call.
     *
     * Role-independent on purpose. A manager reprinting without a reason is
     * still a reprint without a reason; `requested_by_id` beside it records
     * that a manager is who did it.
     */
    public function warnedWithoutReason(): bool
    {
        return $this->kind instanceof PrintJobKind
            && app(ReprintAdvisor::class)->warnedWithoutReason(
                $this->kind,
                (int) $this->reprint_no,
                $this->reprint_reason,
            );
    }

    /**
     * P-10b — copy N ≥ 2 left the printer carrying the locked 「BAN IN #N」
     * mark. A screen showing this row can say so without re-deriving the rule.
     */
    public function reprintMarkerPrinted(): bool
    {
        return (int) $this->reprint_no >= 2;
    }

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }

    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    public function printer(): BelongsTo
    {
        return $this->belongsTo(Printer::class, 'printer_id');
    }

    public function requestedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'requested_by_id');
    }

    /*
     * #1666 (#962) — `order()` / `payment()` đã bị GỠ.
     *
     * Hai quan hệ đó trỏ sang `CustomerOrder` (Ordering) và `OrderPayment`
     * (Payments) từ một model của PlatformIntegration, và đo lại thì **không có
     * một chỗ gọi nào** — không controller, không resource, không test. Nghĩa là
     * cái giá duy nhất chúng đang trả là hai cạnh module bắc qua ranh giới.
     *
     * Các cột `order_id` / `payment_id` GIỮ NGUYÊN: chúng là con trỏ, và bản ghi
     * công việc in cần biết nó in cho đơn nào. Cần đọc chi tiết đơn từ phía in
     * thì đi qua cổng đã công bố (`App\Services\Order\Contracts\OrderQueryPort`),
     * đừng dựng lại quan hệ.
     */

    /**
     * plan-052 M2 — the human's side of the story, kept in its own append-only
     * table so a ws_lan journal row stays byte-for-byte untouchable (§1b).
     */
    public function resolution(): HasOne
    {
        return $this->hasOne(PrintJobResolution::class, 'print_job_id');
    }
}
