<?php

namespace App\Omnify\Modules\Printer\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\Printer\Locales\PrinterLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class PrinterUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'name' => ['sometimes', 'string', 'max:255'],
            'roles' => ['sometimes', 'array'],
            'connection_type' => ['sometimes', 'string'],
            'address' => ['nullable', 'string', 'max:255'],
            'paper_width' => ['sometimes', 'integer'],
            'cut_type' => ['sometimes', 'string'],
            'encoding' => ['sometimes', 'string', 'max:32'],
            'is_active' => ['sometimes', 'boolean'],
            'last_seen_at' => ['nullable', 'date'],
            'notes' => ['nullable', 'string'],
            'organization_id' => ['sometimes', 'uuid', 'exists:organizations,id'],
            'branch_id' => ['sometimes', 'uuid', 'exists:branches,id'],
            'transport' => ['sometimes', 'string', 'max:32'],
            'print_token' => ['nullable', 'string', 'max:128', Rule::unique('printers')->ignore($this->route('printer'))],
            'model_profile' => ['nullable', 'array'],
            'last_status' => ['nullable', 'string', 'max:32'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = PrinterLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'name',
            'roles',
            'connection_type',
            'address',
            'paper_width',
            'cut_type',
            'encoding',
            'is_active',
            'last_seen_at',
            'notes',
            'organization_id',
            'branch_id',
            'transport',
            'print_token',
            'model_profile',
            'last_status',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
