/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * アレルゲン重要度
 */
export enum AllergenSeverity {
  Mandatory = 'mandatory',
  Recommended = 'recommended',
}

/** All AllergenSeverity values */
export const AllergenSeverityValues = Object.values(AllergenSeverity) as AllergenSeverity[];

/** Type guard for AllergenSeverity */
export function isAllergenSeverity(value: unknown): value is AllergenSeverity {
  return AllergenSeverityValues.includes(value as AllergenSeverity);
}

const allergenSeverityLabels: Partial<Record<AllergenSeverity, Record<string, string>>> = {
  [AllergenSeverity.Mandatory]: { 'en': 'Mandatory', 'ja': '表示義務', 'vi': 'Bắt buộc' },
  [AllergenSeverity.Recommended]: { 'en': 'Recommended', 'ja': '表示推奨', 'vi': 'Khuyến nghị' },
};

/** Get label for AllergenSeverity value with locale support */
export function getAllergenSeverityLabel(value: AllergenSeverity, locale?: string): string {
  const labels = allergenSeverityLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for AllergenSeverity value */
export function getAllergenSeverityExtra(_value: AllergenSeverity): Record<string, unknown> | undefined {
  return undefined;
}
