/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 支払方法
 */
export enum PaymentMethod {
  Cash = 'cash',
  Card = 'card',
  Transfer = 'transfer',
  Other = 'other',
}

/** All PaymentMethod values */
export const PaymentMethodValues = Object.values(PaymentMethod) as PaymentMethod[];

/** Type guard for PaymentMethod */
export function isPaymentMethod(value: unknown): value is PaymentMethod {
  return PaymentMethodValues.includes(value as PaymentMethod);
}

const paymentMethodLabels: Partial<Record<PaymentMethod, Record<string, string>>> = {
  [PaymentMethod.Cash]: { 'en': 'Cash', 'ja': '現金', 'vi': 'Tiền mặt' },
  [PaymentMethod.Card]: { 'en': 'Card', 'ja': 'カード', 'vi': 'Thẻ' },
  [PaymentMethod.Transfer]: { 'en': 'Transfer', 'ja': '振込', 'vi': 'Chuyển khoản' },
  [PaymentMethod.Other]: { 'en': 'Other', 'ja': 'その他', 'vi': 'Khác' },
};

/** Get label for PaymentMethod value with locale support */
export function getPaymentMethodLabel(value: PaymentMethod, locale?: string): string {
  const labels = paymentMethodLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for PaymentMethod value */
export function getPaymentMethodExtra(_value: PaymentMethod): Record<string, unknown> | undefined {
  return undefined;
}
