/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 決済ゲートウェイ接続オプション
 */
export type PaymentGatewayConnectionOptionVerificationState = 'unknown' | 'contract_required' | 'certification_required' | 'verified' | 'restricted';

/** All PaymentGatewayConnectionOptionVerificationState values */
export const PaymentGatewayConnectionOptionVerificationStateValues: PaymentGatewayConnectionOptionVerificationState[] = ['unknown', 'contract_required', 'certification_required', 'verified', 'restricted'];

/** Type guard for PaymentGatewayConnectionOptionVerificationState */
export function isPaymentGatewayConnectionOptionVerificationState(value: unknown): value is PaymentGatewayConnectionOptionVerificationState {
  return PaymentGatewayConnectionOptionVerificationStateValues.includes(value as PaymentGatewayConnectionOptionVerificationState);
}

/** Get label for PaymentGatewayConnectionOptionVerificationState value */
export function getPaymentGatewayConnectionOptionVerificationStateLabel(value: PaymentGatewayConnectionOptionVerificationState): string {
  return value;
}

/** Get extra metadata for PaymentGatewayConnectionOptionVerificationState value */
export function getPaymentGatewayConnectionOptionVerificationStateExtra(_value: PaymentGatewayConnectionOptionVerificationState): Record<string, unknown> | undefined {
  return undefined;
}
