/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 製造指示ステータス
 */
export enum ProductionOrderStatus {
  Draft = 'draft',
  Pending = 'pending',
  Approved = 'approved',
  InProgress = 'in_progress',
  Completed = 'completed',
  Cancelled = 'cancelled',
}

/** All ProductionOrderStatus values */
export const ProductionOrderStatusValues = Object.values(ProductionOrderStatus) as ProductionOrderStatus[];

/** Type guard for ProductionOrderStatus */
export function isProductionOrderStatus(value: unknown): value is ProductionOrderStatus {
  return ProductionOrderStatusValues.includes(value as ProductionOrderStatus);
}

const productionOrderStatusLabels: Partial<Record<ProductionOrderStatus, Record<string, string>>> = {
  [ProductionOrderStatus.Draft]: { 'en': 'Draft', 'ja': '下書き', 'vi': 'Nháp' },
  [ProductionOrderStatus.Pending]: { 'en': 'Pending', 'ja': '承認待ち', 'vi': 'Chờ duyệt' },
  [ProductionOrderStatus.Approved]: { 'en': 'Approved', 'ja': '承認済み', 'vi': 'Đã duyệt' },
  [ProductionOrderStatus.InProgress]: { 'en': 'In Progress', 'ja': '進行中', 'vi': 'Đang sản xuất' },
  [ProductionOrderStatus.Completed]: { 'en': 'Completed', 'ja': '完了', 'vi': 'Hoàn thành' },
  [ProductionOrderStatus.Cancelled]: { 'en': 'Cancelled', 'ja': 'キャンセル', 'vi': 'Đã hủy' },
};

/** Get label for ProductionOrderStatus value with locale support */
export function getProductionOrderStatusLabel(value: ProductionOrderStatus, locale?: string): string {
  const labels = productionOrderStatusLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for ProductionOrderStatus value */
export function getProductionOrderStatusExtra(_value: ProductionOrderStatus): Record<string, unknown> | undefined {
  return undefined;
}
