/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 棚卸範囲
 */
export enum StockCountScope {
  Full = 'full',
  Partial = 'partial',
}

/** All StockCountScope values */
export const StockCountScopeValues = Object.values(StockCountScope) as StockCountScope[];

/** Type guard for StockCountScope */
export function isStockCountScope(value: unknown): value is StockCountScope {
  return StockCountScopeValues.includes(value as StockCountScope);
}

const stockCountScopeLabels: Partial<Record<StockCountScope, Record<string, string>>> = {
  [StockCountScope.Full]: { 'en': 'Full Count', 'ja': '全品棚卸', 'vi': 'Kiểm kê toàn bộ' },
  [StockCountScope.Partial]: { 'en': 'Partial Count', 'ja': '一部棚卸', 'vi': 'Kiểm kê một phần' },
};

/** Get label for StockCountScope value with locale support */
export function getStockCountScopeLabel(value: StockCountScope, locale?: string): string {
  const labels = stockCountScopeLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for StockCountScope value */
export function getStockCountScopeExtra(_value: StockCountScope): Record<string, unknown> | undefined {
  return undefined;
}
