<?php

namespace App\Omnify\Modules\GatewayPayout\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\GatewayPayout\Locales\GatewayPayoutLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class GatewayPayoutStoreRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'connection_id' => ['required', 'uuid', 'exists:payment_gateway_connections,id'],
            'provider' => ['required', 'string', 'max:50'],
            'external_payout_id' => ['required', 'string', 'max:191'],
            'expected_arrival_date' => ['nullable', 'date'],
            'paid_at' => ['nullable', 'date'],
            'gross_minor' => ['required', 'integer'],
            'fee_minor' => ['required', 'integer'],
            'net_minor' => ['required', 'integer'],
            'currency' => ['required', 'string', 'max:3'],
            'status' => ['required', 'string', 'max:50'],
            'reconciled_at' => ['nullable', 'date'],
            'bank_ref' => ['nullable', 'string', 'max:191'],
            'metadata' => ['nullable', 'array'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = GatewayPayoutLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'connection_id',
            'provider',
            'external_payout_id',
            'expected_arrival_date',
            'paid_at',
            'gross_minor',
            'fee_minor',
            'net_minor',
            'currency',
            'status',
            'reconciled_at',
            'bank_ref',
            'metadata',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
