<?php

namespace App\Omnify\Modules\Printer\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\BranchResource;
use App\Http\Resources\OrganizationResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PrinterResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'name' => $this->name,
            'roles' => $this->roles,
            'connection_type' => $this->connection_type,
            'address' => $this->address,
            'paper_width' => $this->paper_width,
            'cut_type' => $this->cut_type,
            'encoding' => $this->encoding,
            'is_active' => $this->is_active,
            'last_seen_at' => $this->last_seen_at?->toISOString(),
            'notes' => $this->notes,
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'branch_id' => $this->branch_id,
            'branch' => $this->whenLoaded('branch', fn () => new BranchResource($this->branch)),
            'transport' => $this->transport,
            'print_token' => $this->print_token,
            'model_profile' => $this->model_profile,
            'last_status' => $this->last_status,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'deleted_at' => $this->deleted_at?->toISOString(),
        ];
    }
}
