<?php

namespace App\Omnify\Modules\MenuSection\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use Illuminate\Database\Eloquent\Model;

/**
 * MenuSectionTranslationBaseModel
 */
class MenuSectionTranslationBaseModel extends Model
{
    /**
     * The table associated with the model.
     */
    protected $table = 'menu_section_translations';

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
    ];
}
