/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 注文明細ステータス
 */
export enum OrderItemStatus {
  Pending = 'pending',
  Preparing = 'preparing',
  Ready = 'ready',
  Served = 'served',
  Voided = 'voided',
}

/** All OrderItemStatus values */
export const OrderItemStatusValues = Object.values(OrderItemStatus) as OrderItemStatus[];

/** Type guard for OrderItemStatus */
export function isOrderItemStatus(value: unknown): value is OrderItemStatus {
  return OrderItemStatusValues.includes(value as OrderItemStatus);
}

const orderItemStatusLabels: Partial<Record<OrderItemStatus, Record<string, string>>> = {
  [OrderItemStatus.Pending]: { 'en': 'Pending', 'ja': '受付済み', 'vi': 'Chờ chế biến' },
  [OrderItemStatus.Preparing]: { 'en': 'Preparing', 'ja': '調理中', 'vi': 'Đang chế biến' },
  [OrderItemStatus.Ready]: { 'en': 'Ready', 'ja': '完成', 'vi': 'Sẵn sàng' },
  [OrderItemStatus.Served]: { 'en': 'Served', 'ja': '提供済み', 'vi': 'Đã phục vụ' },
  [OrderItemStatus.Voided]: { 'en': 'Voided', 'ja': '取消', 'vi': 'Đã hủy' },
};

/** Get label for OrderItemStatus value with locale support */
export function getOrderItemStatusLabel(value: OrderItemStatus, locale?: string): string {
  const labels = orderItemStatusLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for OrderItemStatus value */
export function getOrderItemStatusExtra(_value: OrderItemStatus): Record<string, unknown> | undefined {
  return undefined;
}
