/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Branch } from './Branch';
import type { Brand } from './Brand';
import type { Organization } from './Organization';

/**
 * 通知ルーティング
 */
export interface NotificationChannelRoute {
  id: string;
  organization_id: string;
  organization?: Organization;
  brand_id?: string | null;
  brand?: Brand | null;
  branch_id?: string | null;
  branch?: Branch | null;
  type: string;
  channels: unknown;
  priority_overrides?: unknown | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for NotificationChannelRoute
 */
export const notificationChannelRouteI18n = {
  label: {"ja":"通知ルーティング","en":"Notification Channel Route","vi":"Định tuyến kênh thông báo"},
  fields: {
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    brand: {
      label: {"ja":"ブランド","en":"Brand","vi":"Thương hiệu"},
      placeholder: {"ja":"ブランドを入力","en":"Enter Brand","vi":"Nhập Thương hiệu"},
    },
    branch: {
      label: {"ja":"店舗","en":"Shop","vi":"Cửa hàng"},
      placeholder: {"ja":"店舗を入力","en":"Enter Shop","vi":"Nhập Cửa hàng"},
    },
    type: {
      label: {"ja":"タイプ","en":"Type","vi":"Loại"},
      placeholder: {"ja":"タイプを入力","en":"Enter Type","vi":"Nhập Loại"},
    },
    channels: {
      label: {"ja":"チャンネル","en":"Channels","vi":"Kênh"},
      placeholder: {"ja":"チャンネルを入力","en":"Enter Channels","vi":"Nhập Kênh"},
    },
    priority_overrides: {
      label: {"ja":"優先度上書き","en":"Priority Overrides","vi":"Ghi đè ưu tiên"},
      placeholder: {"ja":"優先度上書きを入力","en":"Enter Priority Overrides","vi":"Nhập Ghi đè ưu tiên"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for NotificationChannelRoute */
export const baseNotificationChannelRouteSchemas = {
  type: z.string().min(1).max(100),
  channels: z.unknown(),
  priority_overrides: z.unknown().optional().nullable(),
} as const;

/** Create schema for NotificationChannelRoute */
export const baseNotificationChannelRouteCreateSchema = z.object({
  type: baseNotificationChannelRouteSchemas.type,
  channels: baseNotificationChannelRouteSchemas.channels,
  priority_overrides: baseNotificationChannelRouteSchemas.priority_overrides,
});

/** Update schema for NotificationChannelRoute */
export const baseNotificationChannelRouteUpdateSchema = baseNotificationChannelRouteCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseNotificationChannelRouteCreate = z.infer<typeof baseNotificationChannelRouteCreateSchema>;
export type BaseNotificationChannelRouteUpdate = z.infer<typeof baseNotificationChannelRouteUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getNotificationChannelRouteLabel(locale: string): string {
  return notificationChannelRouteI18n.label[locale as keyof typeof notificationChannelRouteI18n.label] ?? notificationChannelRouteI18n.label['en'] ?? 'NotificationChannelRoute';
}

/** Get field label for a specific locale */
export function getNotificationChannelRouteFieldLabel(field: string, locale: string): string {
  const fields = notificationChannelRouteI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getNotificationChannelRouteFieldPlaceholder(field: string, locale: string): string {
  const fields = notificationChannelRouteI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for NotificationChannelRoute.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const notificationChannelRouteMetadata = {
  modelName: "NotificationChannelRoute",
  table: "notification_channel_routes",

  fields: {
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    brand_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Brand",
        table: "brands",
        onDelete: "CASCADE",
      },
      label: {},
    },
    branch_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Branch",
        table: "branches",
        onDelete: "CASCADE",
      },
      label: {},
    },
    type: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 100,
      },
      label: {
        ja: "タイプ",
        en: "Type",
        vi: "Loại",
      },
      placeholder: {
        ja: "タイプを入力",
        en: "Enter Type",
        vi: "Nhập Loại",
      },
      description: {
        ja: "通知タイプ文字列（ドット区切り）。`notifications.type` + `notification_templates.key` と一致。",
        en: "Notification type string (dot-namespaced). Matches `notifications.type` + `notification_templates.key`.",
        vi: "Chuỗi loại thông báo (dấu chấm). Trùng với `notifications.type` + `notification_templates.key`.",
      },
    },
    channels: {
      type: "json",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "チャンネル",
        en: "Channels",
        vi: "Kênh",
      },
      placeholder: {
        ja: "チャンネルを入力",
        en: "Enter Channels",
        vi: "Nhập Kênh",
      },
      description: {
        ja: "NotificationChannel 値の JSON 配列（例：['in_app','email']）。空配列はこのスコープで当該タイプを完全無効化。",
        en: "JSON array of NotificationChannel cases, e.g. ['in_app','email']. Empty array disables the type entirely for this scope.",
        vi: "Mảng JSON các case NotificationChannel (VD: ['in_app','email']). Mảng rỗng vô hiệu hoá hoàn toàn type cho scope này.",
      },
    },
    priority_overrides: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "優先度上書き",
        en: "Priority Overrides",
        vi: "Ghi đè ưu tiên",
      },
      placeholder: {
        ja: "優先度上書きを入力",
        en: "Enter Priority Overrides",
        vi: "Nhập Ghi đè ưu tiên",
      },
      description: {
        ja: "オプション：`{ <priority>: [<channel>, ...] }` マップ — 優先度別チャンネル上書き。例：urgent → [in_app, realtime, email]。",
        en: "Optional { <priority>: [<channel>, ...] } map — per-priority channel override. E.g. urgent → [in_app, realtime, email] for this type.",
        vi: "Tuỳ chọn: map `{ <priority>: [<channel>, ...] }` — override kênh theo priority. VD: urgent → [in_app, realtime, email].",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["organization_id", "type", "channels"] as const,
  enumFields: [] as const,
  relationFields: ["organization_id", "brand_id", "branch_id"] as const,
} as const;

export type NotificationChannelRouteFieldName = keyof typeof notificationChannelRouteMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a NotificationChannelRoute. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface NotificationChannelRouteCreateFormState {
  organization_id: string;
  brand_id?: string | null;
  branch_id?: string | null;
  type: string;
  channels: unknown;
  priority_overrides?: unknown | null;
}

/** Form-state shape for updating a NotificationChannelRoute. Every field optional. */
export interface NotificationChannelRouteUpdateFormState {
  organization_id?: string;
  brand_id?: string | null;
  branch_id?: string | null;
  type?: string;
  channels?: unknown;
  priority_overrides?: unknown | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyNotificationChannelRouteCreateForm(): NotificationChannelRouteCreateFormState {
  return {
    organization_id: '',
    brand_id: '',
    branch_id: '',
    type: '',
    channels: null,
    priority_overrides: null,
  };
}

/** Convert create form state into the payload that baseNotificationChannelRouteCreateSchema accepts. */
export function buildNotificationChannelRouteCreatePayload(form: NotificationChannelRouteCreateFormState): BaseNotificationChannelRouteCreate {
  const payload: Record<string, unknown> = {
    organization_id: form.organization_id.trim(),
    brand_id: form.brand_id?.toString().trim() || null,
    branch_id: form.branch_id?.toString().trim() || null,
    type: form.type.trim(),
    channels: form.channels,
    priority_overrides: form.priority_overrides,
  };

  return payload as BaseNotificationChannelRouteCreate;
}

/** Convert update form state into the payload that baseNotificationChannelRouteUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildNotificationChannelRouteUpdatePayload(form: NotificationChannelRouteUpdateFormState): BaseNotificationChannelRouteUpdate {
  const payload: Record<string, unknown> = {};
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.brand_id !== undefined) {
    payload.brand_id = form.brand_id?.toString().trim() ?? null;
  }
  if (form.branch_id !== undefined) {
    payload.branch_id = form.branch_id?.toString().trim() ?? null;
  }
  if (form.type !== undefined) {
    payload.type = form.type?.toString().trim() ?? null;
  }
  if (form.channels !== undefined) {
    payload.channels = form.channels;
  }
  if (form.priority_overrides !== undefined) {
    payload.priority_overrides = form.priority_overrides;
  }
  return payload as BaseNotificationChannelRouteUpdate;
}
