/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { CustomerOrder } from './CustomerOrder';
import type { TaxType } from './TaxType';
import type { User } from './User';

/**
 * OrderAdjustment
 */
export interface OrderAdjustment {
  id: string;
  customerOrder_id: string;
  customerOrder?: CustomerOrder;
  direction: string;
  kind: string;
  target_type: string;
  targetAdjustment_id?: string | null;
  targetAdjustment?: OrderAdjustment | null;
  phase: string;
  sequence: number;
  stacking_mode: string;
  value_type: string;
  value: number;
  tax_mode: string;
  taxType_id?: string | null;
  taxType?: TaxType | null;
  tax_rate?: number | null;
  price_includes_tax?: boolean | null;
  source_type?: string | null;
  source_id?: string | null;
  reason?: string | null;
  actorUser_id?: string | null;
  actorUser?: User | null;
  metadata?: unknown | null;
  reversalOf_id?: string | null;
  reversalOf?: OrderAdjustment | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for OrderAdjustment
 */
export const orderAdjustmentI18n = {
  label: {"ja":"OrderAdjustment","en":"OrderAdjustment","vi":"OrderAdjustment"},
  fields: {
    customer_order: {
      label: {"ja":"注文","en":"Customer Order","vi":"Đơn hàng"},
      placeholder: {"ja":"注文を入力","en":"Enter Customer Order","vi":"Nhập Đơn hàng"},
    },
    direction: {
      label: {"ja":"方向","en":"Direction","vi":"Chiều"},
      placeholder: {"ja":"方向を入力","en":"Enter Direction","vi":"Nhập Chiều"},
    },
    kind: {
      label: {"ja":"種別","en":"Kind","vi":"Loại"},
      placeholder: {"ja":"種別を入力","en":"Enter Kind","vi":"Nhập Loại"},
    },
    target_type: {
      label: {"ja":"対象種別","en":"Target Type","vi":"Loại đối tượng"},
      placeholder: {"ja":"対象種別を入力","en":"Enter Target Type","vi":"Nhập Loại đối tượng"},
    },
    target_adjustment: {
      label: {"ja":"対象調整","en":"Target Adjustment","vi":"Khoản đích"},
      placeholder: {"ja":"対象調整を入力","en":"Enter Target Adjustment","vi":"Nhập Khoản đích"},
    },
    phase: {
      label: {"ja":"フェーズ","en":"Phase","vi":"Giai đoạn"},
      placeholder: {"ja":"フェーズを入力","en":"Enter Phase","vi":"Nhập Giai đoạn"},
    },
    sequence: {
      label: {"ja":"順序","en":"Sequence","vi":"Thứ tự"},
      placeholder: {"ja":"順序を入力","en":"Enter Sequence","vi":"Nhập Thứ tự"},
    },
    stacking_mode: {
      label: {"ja":"重ね方","en":"Stacking Mode","vi":"Cách chồng"},
      placeholder: {"ja":"重ね方を入力","en":"Enter Stacking Mode","vi":"Nhập Cách chồng"},
    },
    value_type: {
      label: {"ja":"値種別","en":"Value Type","vi":"Kiểu giá trị"},
      placeholder: {"ja":"値種別を入力","en":"Enter Value Type","vi":"Nhập Kiểu giá trị"},
    },
    value: {
      label: {"ja":"値","en":"Value","vi":"Giá trị"},
      placeholder: {"ja":"値を入力","en":"Enter Value","vi":"Nhập Giá trị"},
    },
    tax_mode: {
      label: {"ja":"税モード","en":"Tax Mode","vi":"Chế độ thuế"},
      placeholder: {"ja":"税モードを入力","en":"Enter Tax Mode","vi":"Nhập Chế độ thuế"},
    },
    tax_type: {
      label: {"ja":"税区分","en":"Tax Type","vi":"Loại thuế"},
      placeholder: {"ja":"税区分を入力","en":"Enter Tax Type","vi":"Nhập Loại thuế"},
    },
    tax_rate: {
      label: {"ja":"税率","en":"Tax Rate","vi":"Thuế suất"},
      placeholder: {"ja":"税率を入力","en":"Enter Tax Rate","vi":"Nhập Thuế suất"},
    },
    price_includes_tax: {
      label: {"ja":"税込","en":"Price Includes Tax","vi":"Giá đã gồm thuế"},
      placeholder: {"ja":"税込を入力","en":"Enter Price Includes Tax","vi":"Nhập Giá đã gồm thuế"},
    },
    source_type: {
      label: {"ja":"由来種別","en":"Source Type","vi":"Loại nguồn"},
      placeholder: {"ja":"由来種別を入力","en":"Enter Source Type","vi":"Nhập Loại nguồn"},
    },
    source_id: {
      label: {"ja":"由来ID","en":"Source ID","vi":"ID nguồn"},
      placeholder: {"ja":"由来IDを入力","en":"Enter Source ID","vi":"Nhập ID nguồn"},
    },
    reason: {
      label: {"ja":"理由","en":"Reason","vi":"Lý do"},
      placeholder: {"ja":"理由を入力","en":"Enter Reason","vi":"Nhập Lý do"},
    },
    actor_user: {
      label: {"ja":"操作者","en":"Actor","vi":"Người thao tác"},
      placeholder: {"ja":"操作者を入力","en":"Enter Actor","vi":"Nhập Người thao tác"},
    },
    metadata: {
      label: {"ja":"メタデータ","en":"Metadata","vi":"Dữ liệu kèm"},
      placeholder: {"ja":"メタデータを入力","en":"Enter Metadata","vi":"Nhập Dữ liệu kèm"},
    },
    reversal_of: {
      label: {"ja":"取消元","en":"Reversal Of","vi":"Đảo của"},
      placeholder: {"ja":"取消元を入力","en":"Enter Reversal Of","vi":"Nhập Đảo của"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for OrderAdjustment */
export const baseOrderAdjustmentSchemas = {
  direction: z.string().min(1).max(16),
  kind: z.string().min(1).max(50),
  target_type: z.string().min(1).max(16),
  phase: z.string().min(1).max(32),
  sequence: z.number().int(),
  stacking_mode: z.string().min(1).max(16),
  value_type: z.string().min(1).max(16),
  value: z.number(),
  tax_mode: z.string().min(1).max(32),
  tax_rate: z.number().optional().nullable(),
  price_includes_tax: z.boolean().optional().nullable(),
  source_type: z.string().max(100).optional().nullable(),
  source_id: z.string().optional().nullable(),
  reason: z.string().max(255).optional().nullable(),
  metadata: z.unknown().optional().nullable(),
} as const;

/** Create schema for OrderAdjustment */
export const baseOrderAdjustmentCreateSchema = z.object({
  direction: baseOrderAdjustmentSchemas.direction,
  kind: baseOrderAdjustmentSchemas.kind,
  target_type: baseOrderAdjustmentSchemas.target_type,
  phase: baseOrderAdjustmentSchemas.phase,
  sequence: baseOrderAdjustmentSchemas.sequence,
  stacking_mode: baseOrderAdjustmentSchemas.stacking_mode,
  value_type: baseOrderAdjustmentSchemas.value_type,
  value: baseOrderAdjustmentSchemas.value,
  tax_mode: baseOrderAdjustmentSchemas.tax_mode,
  tax_rate: baseOrderAdjustmentSchemas.tax_rate,
  price_includes_tax: baseOrderAdjustmentSchemas.price_includes_tax,
  source_type: baseOrderAdjustmentSchemas.source_type,
  source_id: baseOrderAdjustmentSchemas.source_id,
  reason: baseOrderAdjustmentSchemas.reason,
  metadata: baseOrderAdjustmentSchemas.metadata,
});

/** Update schema for OrderAdjustment */
export const baseOrderAdjustmentUpdateSchema = baseOrderAdjustmentCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseOrderAdjustmentCreate = z.infer<typeof baseOrderAdjustmentCreateSchema>;
export type BaseOrderAdjustmentUpdate = z.infer<typeof baseOrderAdjustmentUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getOrderAdjustmentLabel(locale: string): string {
  return orderAdjustmentI18n.label[locale as keyof typeof orderAdjustmentI18n.label] ?? orderAdjustmentI18n.label['en'] ?? 'OrderAdjustment';
}

/** Get field label for a specific locale */
export function getOrderAdjustmentFieldLabel(field: string, locale: string): string {
  const fields = orderAdjustmentI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getOrderAdjustmentFieldPlaceholder(field: string, locale: string): string {
  const fields = orderAdjustmentI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for OrderAdjustment.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const orderAdjustmentMetadata = {
  modelName: "OrderAdjustment",
  table: "order_adjustments",

  fields: {
    customer_order_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "CustomerOrder",
        table: "customer_orders",
        onDelete: "CASCADE",
      },
      label: {},
    },
    direction: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 16,
      },
      label: {
        ja: "方向",
        en: "Direction",
        vi: "Chiều",
      },
      placeholder: {
        ja: "方向を入力",
        en: "Enter Direction",
        vi: "Nhập Chiều",
      },
    },
    kind: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "種別",
        en: "Kind",
        vi: "Loại",
      },
      placeholder: {
        ja: "種別を入力",
        en: "Enter Kind",
        vi: "Nhập Loại",
      },
    },
    target_type: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 16,
      },
      label: {
        ja: "対象種別",
        en: "Target Type",
        vi: "Loại đối tượng",
      },
      placeholder: {
        ja: "対象種別を入力",
        en: "Enter Target Type",
        vi: "Nhập Loại đối tượng",
      },
    },
    target_adjustment_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "OrderAdjustment",
        table: "order_adjustments",
        onDelete: "SET NULL",
      },
      label: {},
    },
    phase: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 32,
      },
      label: {
        ja: "フェーズ",
        en: "Phase",
        vi: "Giai đoạn",
      },
      placeholder: {
        ja: "フェーズを入力",
        en: "Enter Phase",
        vi: "Nhập Giai đoạn",
      },
    },
    sequence: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "順序",
        en: "Sequence",
        vi: "Thứ tự",
      },
      placeholder: {
        ja: "順序を入力",
        en: "Enter Sequence",
        vi: "Nhập Thứ tự",
      },
    },
    stacking_mode: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 16,
      },
      label: {
        ja: "重ね方",
        en: "Stacking Mode",
        vi: "Cách chồng",
      },
      placeholder: {
        ja: "重ね方を入力",
        en: "Enter Stacking Mode",
        vi: "Nhập Cách chồng",
      },
    },
    value_type: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 16,
      },
      label: {
        ja: "値種別",
        en: "Value Type",
        vi: "Kiểu giá trị",
      },
      placeholder: {
        ja: "値種別を入力",
        en: "Enter Value Type",
        vi: "Nhập Kiểu giá trị",
      },
    },
    value: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "値",
        en: "Value",
        vi: "Giá trị",
      },
      placeholder: {
        ja: "値を入力",
        en: "Enter Value",
        vi: "Nhập Giá trị",
      },
    },
    tax_mode: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 32,
      },
      label: {
        ja: "税モード",
        en: "Tax Mode",
        vi: "Chế độ thuế",
      },
      placeholder: {
        ja: "税モードを入力",
        en: "Enter Tax Mode",
        vi: "Nhập Chế độ thuế",
      },
    },
    tax_type_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "TaxType",
        table: "tax_types",
        onDelete: "SET NULL",
      },
      label: {},
    },
    tax_rate: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "税率",
        en: "Tax Rate",
        vi: "Thuế suất",
      },
      placeholder: {
        ja: "税率を入力",
        en: "Enter Tax Rate",
        vi: "Nhập Thuế suất",
      },
    },
    price_includes_tax: {
      type: "boolean",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "税込",
        en: "Price Includes Tax",
        vi: "Giá đã gồm thuế",
      },
      placeholder: {
        ja: "税込を入力",
        en: "Enter Price Includes Tax",
        vi: "Nhập Giá đã gồm thuế",
      },
    },
    source_type: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 100,
      },
      label: {
        ja: "由来種別",
        en: "Source Type",
        vi: "Loại nguồn",
      },
      placeholder: {
        ja: "由来種別を入力",
        en: "Enter Source Type",
        vi: "Nhập Loại nguồn",
      },
    },
    source_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "由来ID",
        en: "Source ID",
        vi: "ID nguồn",
      },
      placeholder: {
        ja: "由来IDを入力",
        en: "Enter Source ID",
        vi: "Nhập ID nguồn",
      },
    },
    reason: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "理由",
        en: "Reason",
        vi: "Lý do",
      },
      placeholder: {
        ja: "理由を入力",
        en: "Enter Reason",
        vi: "Nhập Lý do",
      },
    },
    actor_user_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "User",
        table: "users",
        onDelete: "SET NULL",
      },
      label: {},
    },
    metadata: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "メタデータ",
        en: "Metadata",
        vi: "Dữ liệu kèm",
      },
      placeholder: {
        ja: "メタデータを入力",
        en: "Enter Metadata",
        vi: "Nhập Dữ liệu kèm",
      },
    },
    reversal_of_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "OrderAdjustment",
        table: "order_adjustments",
        onDelete: "SET NULL",
      },
      label: {},
    },
  },

  translatableFields: [] as const,
  requiredFields: ["customer_order_id", "direction", "kind", "target_type", "phase", "sequence", "stacking_mode", "value_type", "value", "tax_mode"] as const,
  enumFields: [] as const,
  relationFields: ["customer_order_id", "target_adjustment_id", "tax_type_id", "actor_user_id", "reversal_of_id"] as const,
} as const;

export type OrderAdjustmentFieldName = keyof typeof orderAdjustmentMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a OrderAdjustment. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface OrderAdjustmentCreateFormState {
  customer_order_id: string;
  direction: string;
  kind: string;
  target_type: string;
  target_adjustment_id?: string | null;
  phase: string;
  sequence: number;
  stacking_mode: string;
  value_type: string;
  value: number;
  tax_mode: string;
  tax_type_id?: string | null;
  tax_rate?: number | null;
  price_includes_tax?: boolean | null;
  source_type?: string | null;
  source_id?: string | null;
  reason?: string | null;
  actor_user_id?: string | null;
  metadata?: unknown | null;
  reversal_of_id?: string | null;
}

/** Form-state shape for updating a OrderAdjustment. Every field optional. */
export interface OrderAdjustmentUpdateFormState {
  customer_order_id?: string;
  direction?: string;
  kind?: string;
  target_type?: string;
  target_adjustment_id?: string | null;
  phase?: string;
  sequence?: number;
  stacking_mode?: string;
  value_type?: string;
  value?: number;
  tax_mode?: string;
  tax_type_id?: string | null;
  tax_rate?: number | null;
  price_includes_tax?: boolean | null;
  source_type?: string | null;
  source_id?: string | null;
  reason?: string | null;
  actor_user_id?: string | null;
  metadata?: unknown | null;
  reversal_of_id?: string | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyOrderAdjustmentCreateForm(): OrderAdjustmentCreateFormState {
  return {
    customer_order_id: '',
    direction: '',
    kind: '',
    target_type: "order",
    target_adjustment_id: '',
    phase: '',
    sequence: 0,
    stacking_mode: "stack",
    value_type: '',
    value: 0,
    tax_mode: '',
    tax_type_id: '',
    tax_rate: 0,
    price_includes_tax: false,
    source_type: '',
    source_id: '',
    reason: '',
    actor_user_id: '',
    metadata: null,
    reversal_of_id: '',
  };
}

/** Convert create form state into the payload that baseOrderAdjustmentCreateSchema accepts. */
export function buildOrderAdjustmentCreatePayload(form: OrderAdjustmentCreateFormState): BaseOrderAdjustmentCreate {
  const payload: Record<string, unknown> = {
    customer_order_id: form.customer_order_id.trim(),
    direction: form.direction.trim(),
    kind: form.kind.trim(),
    target_type: form.target_type.trim(),
    target_adjustment_id: form.target_adjustment_id?.toString().trim() || null,
    phase: form.phase.trim(),
    sequence: form.sequence,
    stacking_mode: form.stacking_mode.trim(),
    value_type: form.value_type.trim(),
    value: form.value,
    tax_mode: form.tax_mode.trim(),
    tax_type_id: form.tax_type_id?.toString().trim() || null,
    tax_rate: form.tax_rate,
    price_includes_tax: form.price_includes_tax,
    source_type: form.source_type?.toString().trim() || null,
    source_id: form.source_id?.toString().trim() || null,
    reason: form.reason?.toString().trim() || null,
    actor_user_id: form.actor_user_id?.toString().trim() || null,
    metadata: form.metadata,
    reversal_of_id: form.reversal_of_id?.toString().trim() || null,
  };

  return payload as BaseOrderAdjustmentCreate;
}

/** Convert update form state into the payload that baseOrderAdjustmentUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildOrderAdjustmentUpdatePayload(form: OrderAdjustmentUpdateFormState): BaseOrderAdjustmentUpdate {
  const payload: Record<string, unknown> = {};
  if (form.customer_order_id !== undefined) {
    payload.customer_order_id = form.customer_order_id?.toString().trim() ?? null;
  }
  if (form.direction !== undefined) {
    payload.direction = form.direction?.toString().trim() ?? null;
  }
  if (form.kind !== undefined) {
    payload.kind = form.kind?.toString().trim() ?? null;
  }
  if (form.target_type !== undefined) {
    payload.target_type = form.target_type?.toString().trim() ?? null;
  }
  if (form.target_adjustment_id !== undefined) {
    payload.target_adjustment_id = form.target_adjustment_id?.toString().trim() ?? null;
  }
  if (form.phase !== undefined) {
    payload.phase = form.phase?.toString().trim() ?? null;
  }
  if (form.sequence !== undefined) {
    payload.sequence = form.sequence;
  }
  if (form.stacking_mode !== undefined) {
    payload.stacking_mode = form.stacking_mode?.toString().trim() ?? null;
  }
  if (form.value_type !== undefined) {
    payload.value_type = form.value_type?.toString().trim() ?? null;
  }
  if (form.value !== undefined) {
    payload.value = form.value;
  }
  if (form.tax_mode !== undefined) {
    payload.tax_mode = form.tax_mode?.toString().trim() ?? null;
  }
  if (form.tax_type_id !== undefined) {
    payload.tax_type_id = form.tax_type_id?.toString().trim() ?? null;
  }
  if (form.tax_rate !== undefined) {
    payload.tax_rate = form.tax_rate;
  }
  if (form.price_includes_tax !== undefined) {
    payload.price_includes_tax = form.price_includes_tax;
  }
  if (form.source_type !== undefined) {
    payload.source_type = form.source_type?.toString().trim() ?? null;
  }
  if (form.source_id !== undefined) {
    payload.source_id = form.source_id?.toString().trim() ?? null;
  }
  if (form.reason !== undefined) {
    payload.reason = form.reason?.toString().trim() ?? null;
  }
  if (form.actor_user_id !== undefined) {
    payload.actor_user_id = form.actor_user_id?.toString().trim() ?? null;
  }
  if (form.metadata !== undefined) {
    payload.metadata = form.metadata;
  }
  if (form.reversal_of_id !== undefined) {
    payload.reversal_of_id = form.reversal_of_id?.toString().trim() ?? null;
  }
  return payload as BaseOrderAdjustmentUpdate;
}
