/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import { PaymentGatewayEnvironment } from '../enum/PaymentGatewayEnvironment';
import { PaymentGatewayProviderCode } from '../enum/PaymentGatewayProviderCode';
import { PaymentProviderEventState } from '../enum/PaymentProviderEventState';
import type { Organization } from './Organization';
import type { PaymentGatewayConnection } from './PaymentGatewayConnection';

/**
 * 決済プロバイダーイベント
 */
export interface PaymentProviderEvent {
  id: string;
  organization_id: string;
  organization?: Organization;
  connection_id: string;
  connection?: PaymentGatewayConnection;
  provider: PaymentGatewayProviderCode;
  environment: PaymentGatewayEnvironment;
  state: PaymentProviderEventState;
  provider_event_id: string;
  event_type: string;
  provider_object_id?: string | null;
  payload_hash: string;
  signature_version?: string | null;
  redacted_payload?: unknown | null;
  outcome?: string | null;
  delivery_count: number;
  processing_attempts: number;
  lease_token?: string | null;
  lease_expires_at?: DateTimeString | null;
  next_retry_at?: DateTimeString | null;
  last_error_code?: string | null;
  redacted_error?: unknown | null;
  received_at: DateTimeString;
  verified_at: DateTimeString;
  processed_at?: DateTimeString | null;
  operator_resolution?: string | null;
  operator_resolved_at?: DateTimeString | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for PaymentProviderEvent
 */
export const paymentProviderEventI18n = {
  label: {"ja":"決済プロバイダーイベント","en":"Payment Provider Event","vi":"Sự kiện nhà cung cấp thanh toán"},
  fields: {
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    connection: {
      label: {"ja":"接続","en":"Connection","vi":"Kết nối"},
      placeholder: {"ja":"接続を入力","en":"Enter Connection","vi":"Nhập Kết nối"},
    },
    provider: {
      label: {"ja":"プロバイダー","en":"Provider","vi":"Nhà cung cấp"},
      placeholder: {"ja":"プロバイダーを入力","en":"Enter Provider","vi":"Nhập Nhà cung cấp"},
    },
    environment: {
      label: {"ja":"環境","en":"Environment","vi":"Môi trường"},
      placeholder: {"ja":"環境を入力","en":"Enter Environment","vi":"Nhập Môi trường"},
    },
    state: {
      label: {"ja":"状態","en":"State","vi":"Trạng thái"},
      placeholder: {"ja":"状態を入力","en":"Enter State","vi":"Nhập Trạng thái"},
    },
    provider_event_id: {
      label: {"ja":"プロバイダーイベントID","en":"Provider Event ID","vi":"ID sự kiện nhà cung cấp"},
      placeholder: {"ja":"プロバイダーイベントIDを入力","en":"Enter Provider Event ID","vi":"Nhập ID sự kiện nhà cung cấp"},
    },
    event_type: {
      label: {"ja":"イベントタイプ","en":"Event Type","vi":"Loại sự kiện"},
      placeholder: {"ja":"イベントタイプを入力","en":"Enter Event Type","vi":"Nhập Loại sự kiện"},
    },
    provider_object_id: {
      label: {"ja":"プロバイダーオブジェクトID","en":"Provider Object ID","vi":"ID đối tượng nhà cung cấp"},
      placeholder: {"ja":"プロバイダーオブジェクトIDを入力","en":"Enter Provider Object ID","vi":"Nhập ID đối tượng nhà cung cấp"},
    },
    payload_hash: {
      label: {"ja":"ペイロードハッシュ","en":"Payload Hash","vi":"Hash payload"},
      placeholder: {"ja":"ペイロードハッシュを入力","en":"Enter Payload Hash","vi":"Nhập Hash payload"},
    },
    signature_version: {
      label: {"ja":"署名バージョン","en":"Signature Version","vi":"Phiên bản chữ ký"},
      placeholder: {"ja":"署名バージョンを入力","en":"Enter Signature Version","vi":"Nhập Phiên bản chữ ký"},
    },
    redacted_payload: {
      label: {"ja":"編集済みペイロード","en":"Redacted Payload","vi":"Payload đã che"},
      placeholder: {"ja":"編集済みペイロードを入力","en":"Enter Redacted Payload","vi":"Nhập Payload đã che"},
    },
    outcome: {
      label: {"ja":"結果","en":"Outcome","vi":"Kết quả"},
      placeholder: {"ja":"結果を入力","en":"Enter Outcome","vi":"Nhập Kết quả"},
    },
    delivery_count: {
      label: {"ja":"配信回数","en":"Delivery Count","vi":"Số lần nhận"},
      placeholder: {"ja":"配信回数を入力","en":"Enter Delivery Count","vi":"Nhập Số lần nhận"},
    },
    processing_attempts: {
      label: {"ja":"処理試行回数","en":"Processing Attempts","vi":"Số lần xử lý"},
      placeholder: {"ja":"処理試行回数を入力","en":"Enter Processing Attempts","vi":"Nhập Số lần xử lý"},
    },
    lease_token: {
      label: {"ja":"リーストークン","en":"Lease Token","vi":"Token lease"},
      placeholder: {"ja":"リーストークンを入力","en":"Enter Lease Token","vi":"Nhập Token lease"},
    },
    lease_expires_at: {
      label: {"ja":"リース期限","en":"Lease Expires At","vi":"Lease hết hạn"},
      placeholder: {"ja":"リース期限を入力","en":"Enter Lease Expires At","vi":"Nhập Lease hết hạn"},
    },
    next_retry_at: {
      label: {"ja":"次回再試行日時","en":"Next Retry At","vi":"Thử lại lúc"},
      placeholder: {"ja":"次回再試行日時を入力","en":"Enter Next Retry At","vi":"Nhập Thử lại lúc"},
    },
    last_error_code: {
      label: {"ja":"最終エラーコード","en":"Last Error Code","vi":"Mã lỗi gần nhất"},
      placeholder: {"ja":"最終エラーコードを入力","en":"Enter Last Error Code","vi":"Nhập Mã lỗi gần nhất"},
    },
    redacted_error: {
      label: {"ja":"編集済みエラー","en":"Redacted Error","vi":"Lỗi đã che"},
      placeholder: {"ja":"編集済みエラーを入力","en":"Enter Redacted Error","vi":"Nhập Lỗi đã che"},
    },
    received_at: {
      label: {"ja":"受信日時","en":"Received At","vi":"Nhận lúc"},
      placeholder: {"ja":"受信日時を入力","en":"Enter Received At","vi":"Nhập Nhận lúc"},
    },
    verified_at: {
      label: {"ja":"検証日時","en":"Verified At","vi":"Xác minh lúc"},
      placeholder: {"ja":"検証日時を入力","en":"Enter Verified At","vi":"Nhập Xác minh lúc"},
    },
    processed_at: {
      label: {"ja":"処理日時","en":"Processed At","vi":"Xử lý lúc"},
      placeholder: {"ja":"処理日時を入力","en":"Enter Processed At","vi":"Nhập Xử lý lúc"},
    },
    operator_resolution: {
      label: {"ja":"運用者解決内容","en":"Operator Resolution","vi":"Xử lý của vận hành"},
      placeholder: {"ja":"運用者解決内容を入力","en":"Enter Operator Resolution","vi":"Nhập Xử lý của vận hành"},
    },
    operator_resolved_at: {
      label: {"ja":"運用者解決日時","en":"Operator Resolved At","vi":"Vận hành xử lý lúc"},
      placeholder: {"ja":"運用者解決日時を入力","en":"Enter Operator Resolved At","vi":"Nhập Vận hành xử lý lúc"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for PaymentProviderEvent */
export const basePaymentProviderEventSchemas = {
  provider: z.nativeEnum(PaymentGatewayProviderCode),
  environment: z.nativeEnum(PaymentGatewayEnvironment),
  state: z.nativeEnum(PaymentProviderEventState),
  provider_event_id: z.string().min(1).max(191),
  event_type: z.string().min(1).max(160),
  provider_object_id: z.string().max(191).optional().nullable(),
  payload_hash: z.string().min(1).max(64).regex(/^[a-zA-Z0-9]+$/).regex(/^[^A-Z]*$/),
  signature_version: z.string().max(80).optional().nullable(),
  redacted_payload: z.unknown().optional().nullable(),
  outcome: z.string().max(100).optional().nullable(),
  delivery_count: z.number().int().gte(1),
  processing_attempts: z.number().int(),
  lease_token: z.string().max(80).optional().nullable(),
  lease_expires_at: z.string().datetime({ offset: true }).optional().nullable(),
  next_retry_at: z.string().datetime({ offset: true }).optional().nullable(),
  last_error_code: z.string().max(100).optional().nullable(),
  redacted_error: z.unknown().optional().nullable(),
  received_at: z.string().datetime({ offset: true }),
  verified_at: z.string().datetime({ offset: true }),
  processed_at: z.string().datetime({ offset: true }).optional().nullable(),
  operator_resolution: z.string().max(1000).optional().nullable(),
  operator_resolved_at: z.string().datetime({ offset: true }).optional().nullable(),
} as const;

/** Create schema for PaymentProviderEvent */
export const basePaymentProviderEventCreateSchema = z.object({
  provider: basePaymentProviderEventSchemas.provider,
  environment: basePaymentProviderEventSchemas.environment,
  state: basePaymentProviderEventSchemas.state,
  provider_event_id: basePaymentProviderEventSchemas.provider_event_id,
  event_type: basePaymentProviderEventSchemas.event_type,
  provider_object_id: basePaymentProviderEventSchemas.provider_object_id,
  payload_hash: basePaymentProviderEventSchemas.payload_hash,
  signature_version: basePaymentProviderEventSchemas.signature_version,
  redacted_payload: basePaymentProviderEventSchemas.redacted_payload,
  outcome: basePaymentProviderEventSchemas.outcome,
  delivery_count: basePaymentProviderEventSchemas.delivery_count,
  processing_attempts: basePaymentProviderEventSchemas.processing_attempts,
  lease_token: basePaymentProviderEventSchemas.lease_token,
  lease_expires_at: basePaymentProviderEventSchemas.lease_expires_at,
  next_retry_at: basePaymentProviderEventSchemas.next_retry_at,
  last_error_code: basePaymentProviderEventSchemas.last_error_code,
  redacted_error: basePaymentProviderEventSchemas.redacted_error,
  received_at: basePaymentProviderEventSchemas.received_at,
  verified_at: basePaymentProviderEventSchemas.verified_at,
  processed_at: basePaymentProviderEventSchemas.processed_at,
  operator_resolution: basePaymentProviderEventSchemas.operator_resolution,
  operator_resolved_at: basePaymentProviderEventSchemas.operator_resolved_at,
});

/** Update schema for PaymentProviderEvent */
export const basePaymentProviderEventUpdateSchema = basePaymentProviderEventCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BasePaymentProviderEventCreate = z.infer<typeof basePaymentProviderEventCreateSchema>;
export type BasePaymentProviderEventUpdate = z.infer<typeof basePaymentProviderEventUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getPaymentProviderEventLabel(locale: string): string {
  return paymentProviderEventI18n.label[locale as keyof typeof paymentProviderEventI18n.label] ?? paymentProviderEventI18n.label['en'] ?? 'PaymentProviderEvent';
}

/** Get field label for a specific locale */
export function getPaymentProviderEventFieldLabel(field: string, locale: string): string {
  const fields = paymentProviderEventI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getPaymentProviderEventFieldPlaceholder(field: string, locale: string): string {
  const fields = paymentProviderEventI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for PaymentProviderEvent.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const paymentProviderEventMetadata = {
  modelName: "PaymentProviderEvent",
  table: "payment_provider_events",

  fields: {
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "RESTRICT",
      },
      label: {},
    },
    connection_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "PaymentGatewayConnection",
        table: "payment_gateway_connections",
        onDelete: "RESTRICT",
      },
      label: {},
    },
    provider: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "PaymentGatewayProviderCode",
      enumValues: ["internal", "stripe", "paypay", "sbps"] as const,
      label: {
        ja: "プロバイダー",
        en: "Provider",
        vi: "Nhà cung cấp",
      },
      placeholder: {
        ja: "プロバイダーを入力",
        en: "Enter Provider",
        vi: "Nhập Nhà cung cấp",
      },
    },
    environment: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "PaymentGatewayEnvironment",
      enumValues: ["local", "sandbox", "test", "live"] as const,
      label: {
        ja: "環境",
        en: "Environment",
        vi: "Môi trường",
      },
      placeholder: {
        ja: "環境を入力",
        en: "Enter Environment",
        vi: "Nhập Môi trường",
      },
    },
    state: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "PaymentProviderEventState",
      enumValues: ["received_verified", "queued", "processing", "retryable", "succeeded", "dead_letter", "operator_resolved"] as const,
      label: {
        ja: "状態",
        en: "State",
        vi: "Trạng thái",
      },
      placeholder: {
        ja: "状態を入力",
        en: "Enter State",
        vi: "Nhập Trạng thái",
      },
    },
    provider_event_id: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 191,
      },
      label: {
        ja: "プロバイダーイベントID",
        en: "Provider Event ID",
        vi: "ID sự kiện nhà cung cấp",
      },
      placeholder: {
        ja: "プロバイダーイベントIDを入力",
        en: "Enter Provider Event ID",
        vi: "Nhập ID sự kiện nhà cung cấp",
      },
    },
    event_type: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 160,
      },
      label: {
        ja: "イベントタイプ",
        en: "Event Type",
        vi: "Loại sự kiện",
      },
      placeholder: {
        ja: "イベントタイプを入力",
        en: "Enter Event Type",
        vi: "Nhập Loại sự kiện",
      },
    },
    provider_object_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 191,
      },
      label: {
        ja: "プロバイダーオブジェクトID",
        en: "Provider Object ID",
        vi: "ID đối tượng nhà cung cấp",
      },
      placeholder: {
        ja: "プロバイダーオブジェクトIDを入力",
        en: "Enter Provider Object ID",
        vi: "Nhập ID đối tượng nhà cung cấp",
      },
    },
    payload_hash: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 64,
      },
      label: {
        ja: "ペイロードハッシュ",
        en: "Payload Hash",
        vi: "Hash payload",
      },
      placeholder: {
        ja: "ペイロードハッシュを入力",
        en: "Enter Payload Hash",
        vi: "Nhập Hash payload",
      },
    },
    signature_version: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 80,
      },
      label: {
        ja: "署名バージョン",
        en: "Signature Version",
        vi: "Phiên bản chữ ký",
      },
      placeholder: {
        ja: "署名バージョンを入力",
        en: "Enter Signature Version",
        vi: "Nhập Phiên bản chữ ký",
      },
    },
    redacted_payload: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "編集済みペイロード",
        en: "Redacted Payload",
        vi: "Payload đã che",
      },
      placeholder: {
        ja: "編集済みペイロードを入力",
        en: "Enter Redacted Payload",
        vi: "Nhập Payload đã che",
      },
    },
    outcome: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 100,
      },
      label: {
        ja: "結果",
        en: "Outcome",
        vi: "Kết quả",
      },
      placeholder: {
        ja: "結果を入力",
        en: "Enter Outcome",
        vi: "Nhập Kết quả",
      },
    },
    delivery_count: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        min: 1,
      },
      label: {
        ja: "配信回数",
        en: "Delivery Count",
        vi: "Số lần nhận",
      },
      placeholder: {
        ja: "配信回数を入力",
        en: "Enter Delivery Count",
        vi: "Nhập Số lần nhận",
      },
    },
    processing_attempts: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "処理試行回数",
        en: "Processing Attempts",
        vi: "Số lần xử lý",
      },
      placeholder: {
        ja: "処理試行回数を入力",
        en: "Enter Processing Attempts",
        vi: "Nhập Số lần xử lý",
      },
    },
    lease_token: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 80,
      },
      label: {
        ja: "リーストークン",
        en: "Lease Token",
        vi: "Token lease",
      },
      placeholder: {
        ja: "リーストークンを入力",
        en: "Enter Lease Token",
        vi: "Nhập Token lease",
      },
    },
    lease_expires_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "リース期限",
        en: "Lease Expires At",
        vi: "Lease hết hạn",
      },
      placeholder: {
        ja: "リース期限を入力",
        en: "Enter Lease Expires At",
        vi: "Nhập Lease hết hạn",
      },
    },
    next_retry_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "次回再試行日時",
        en: "Next Retry At",
        vi: "Thử lại lúc",
      },
      placeholder: {
        ja: "次回再試行日時を入力",
        en: "Enter Next Retry At",
        vi: "Nhập Thử lại lúc",
      },
    },
    last_error_code: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 100,
      },
      label: {
        ja: "最終エラーコード",
        en: "Last Error Code",
        vi: "Mã lỗi gần nhất",
      },
      placeholder: {
        ja: "最終エラーコードを入力",
        en: "Enter Last Error Code",
        vi: "Nhập Mã lỗi gần nhất",
      },
    },
    redacted_error: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "編集済みエラー",
        en: "Redacted Error",
        vi: "Lỗi đã che",
      },
      placeholder: {
        ja: "編集済みエラーを入力",
        en: "Enter Redacted Error",
        vi: "Nhập Lỗi đã che",
      },
    },
    received_at: {
      type: "datetime",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "受信日時",
        en: "Received At",
        vi: "Nhận lúc",
      },
      placeholder: {
        ja: "受信日時を入力",
        en: "Enter Received At",
        vi: "Nhập Nhận lúc",
      },
    },
    verified_at: {
      type: "datetime",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "検証日時",
        en: "Verified At",
        vi: "Xác minh lúc",
      },
      placeholder: {
        ja: "検証日時を入力",
        en: "Enter Verified At",
        vi: "Nhập Xác minh lúc",
      },
    },
    processed_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "処理日時",
        en: "Processed At",
        vi: "Xử lý lúc",
      },
      placeholder: {
        ja: "処理日時を入力",
        en: "Enter Processed At",
        vi: "Nhập Xử lý lúc",
      },
    },
    operator_resolution: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 1000,
      },
      label: {
        ja: "運用者解決内容",
        en: "Operator Resolution",
        vi: "Xử lý của vận hành",
      },
      placeholder: {
        ja: "運用者解決内容を入力",
        en: "Enter Operator Resolution",
        vi: "Nhập Xử lý của vận hành",
      },
    },
    operator_resolved_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "運用者解決日時",
        en: "Operator Resolved At",
        vi: "Vận hành xử lý lúc",
      },
      placeholder: {
        ja: "運用者解決日時を入力",
        en: "Enter Operator Resolved At",
        vi: "Nhập Vận hành xử lý lúc",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["organization_id", "connection_id", "provider", "environment", "state", "provider_event_id", "event_type", "payload_hash", "delivery_count", "processing_attempts", "received_at", "verified_at"] as const,
  enumFields: ["provider", "environment", "state"] as const,
  relationFields: ["organization_id", "connection_id"] as const,
} as const;

export type PaymentProviderEventFieldName = keyof typeof paymentProviderEventMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a PaymentProviderEvent. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface PaymentProviderEventCreateFormState {
  organization_id: string;
  connection_id: string;
  provider: PaymentGatewayProviderCode;
  environment: PaymentGatewayEnvironment;
  state: PaymentProviderEventState;
  provider_event_id: string;
  event_type: string;
  provider_object_id?: string | null;
  payload_hash: string;
  signature_version?: string | null;
  redacted_payload?: unknown | null;
  outcome?: string | null;
  delivery_count: number;
  processing_attempts: number;
  lease_token?: string | null;
  lease_expires_at?: string | null;
  next_retry_at?: string | null;
  last_error_code?: string | null;
  redacted_error?: unknown | null;
  received_at: string;
  verified_at: string;
  processed_at?: string | null;
  operator_resolution?: string | null;
  operator_resolved_at?: string | null;
}

/** Form-state shape for updating a PaymentProviderEvent. Every field optional. */
export interface PaymentProviderEventUpdateFormState {
  organization_id?: string;
  connection_id?: string;
  provider?: PaymentGatewayProviderCode;
  environment?: PaymentGatewayEnvironment;
  state?: PaymentProviderEventState;
  provider_event_id?: string;
  event_type?: string;
  provider_object_id?: string | null;
  payload_hash?: string;
  signature_version?: string | null;
  redacted_payload?: unknown | null;
  outcome?: string | null;
  delivery_count?: number;
  processing_attempts?: number;
  lease_token?: string | null;
  lease_expires_at?: string | null;
  next_retry_at?: string | null;
  last_error_code?: string | null;
  redacted_error?: unknown | null;
  received_at?: string;
  verified_at?: string;
  processed_at?: string | null;
  operator_resolution?: string | null;
  operator_resolved_at?: string | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyPaymentProviderEventCreateForm(): PaymentProviderEventCreateFormState {
  return {
    organization_id: '',
    connection_id: '',
    provider: PaymentGatewayProviderCode.Internal,
    environment: PaymentGatewayEnvironment.Local,
    state: PaymentProviderEventState.ReceivedVerified,
    provider_event_id: '',
    event_type: '',
    provider_object_id: '',
    payload_hash: '',
    signature_version: '',
    redacted_payload: null,
    outcome: '',
    delivery_count: 1,
    processing_attempts: 0,
    lease_token: '',
    lease_expires_at: '',
    next_retry_at: '',
    last_error_code: '',
    redacted_error: null,
    received_at: '',
    verified_at: '',
    processed_at: '',
    operator_resolution: '',
    operator_resolved_at: '',
  };
}

/** Convert create form state into the payload that basePaymentProviderEventCreateSchema accepts. */
export function buildPaymentProviderEventCreatePayload(form: PaymentProviderEventCreateFormState): BasePaymentProviderEventCreate {
  const payload: Record<string, unknown> = {
    organization_id: form.organization_id.trim(),
    connection_id: form.connection_id.trim(),
    provider: form.provider,
    environment: form.environment,
    state: form.state,
    provider_event_id: form.provider_event_id.trim(),
    event_type: form.event_type.trim(),
    provider_object_id: form.provider_object_id?.toString().trim() || null,
    payload_hash: form.payload_hash.trim(),
    signature_version: form.signature_version?.toString().trim() || null,
    redacted_payload: form.redacted_payload,
    outcome: form.outcome?.toString().trim() || null,
    delivery_count: form.delivery_count,
    processing_attempts: form.processing_attempts,
    lease_token: form.lease_token?.toString().trim() || null,
    lease_expires_at: form.lease_expires_at,
    next_retry_at: form.next_retry_at,
    last_error_code: form.last_error_code?.toString().trim() || null,
    redacted_error: form.redacted_error,
    received_at: form.received_at,
    verified_at: form.verified_at,
    processed_at: form.processed_at,
    operator_resolution: form.operator_resolution?.toString().trim() || null,
    operator_resolved_at: form.operator_resolved_at,
  };

  return payload as BasePaymentProviderEventCreate;
}

/** Convert update form state into the payload that basePaymentProviderEventUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildPaymentProviderEventUpdatePayload(form: PaymentProviderEventUpdateFormState): BasePaymentProviderEventUpdate {
  const payload: Record<string, unknown> = {};
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.connection_id !== undefined) {
    payload.connection_id = form.connection_id?.toString().trim() ?? null;
  }
  if (form.provider !== undefined) {
    payload.provider = form.provider;
  }
  if (form.environment !== undefined) {
    payload.environment = form.environment;
  }
  if (form.state !== undefined) {
    payload.state = form.state;
  }
  if (form.provider_event_id !== undefined) {
    payload.provider_event_id = form.provider_event_id?.toString().trim() ?? null;
  }
  if (form.event_type !== undefined) {
    payload.event_type = form.event_type?.toString().trim() ?? null;
  }
  if (form.provider_object_id !== undefined) {
    payload.provider_object_id = form.provider_object_id?.toString().trim() ?? null;
  }
  if (form.payload_hash !== undefined) {
    payload.payload_hash = form.payload_hash?.toString().trim() ?? null;
  }
  if (form.signature_version !== undefined) {
    payload.signature_version = form.signature_version?.toString().trim() ?? null;
  }
  if (form.redacted_payload !== undefined) {
    payload.redacted_payload = form.redacted_payload;
  }
  if (form.outcome !== undefined) {
    payload.outcome = form.outcome?.toString().trim() ?? null;
  }
  if (form.delivery_count !== undefined) {
    payload.delivery_count = form.delivery_count;
  }
  if (form.processing_attempts !== undefined) {
    payload.processing_attempts = form.processing_attempts;
  }
  if (form.lease_token !== undefined) {
    payload.lease_token = form.lease_token?.toString().trim() ?? null;
  }
  if (form.lease_expires_at !== undefined) {
    payload.lease_expires_at = form.lease_expires_at;
  }
  if (form.next_retry_at !== undefined) {
    payload.next_retry_at = form.next_retry_at;
  }
  if (form.last_error_code !== undefined) {
    payload.last_error_code = form.last_error_code?.toString().trim() ?? null;
  }
  if (form.redacted_error !== undefined) {
    payload.redacted_error = form.redacted_error;
  }
  if (form.received_at !== undefined) {
    payload.received_at = form.received_at;
  }
  if (form.verified_at !== undefined) {
    payload.verified_at = form.verified_at;
  }
  if (form.processed_at !== undefined) {
    payload.processed_at = form.processed_at;
  }
  if (form.operator_resolution !== undefined) {
    payload.operator_resolution = form.operator_resolution?.toString().trim() ?? null;
  }
  if (form.operator_resolved_at !== undefined) {
    payload.operator_resolved_at = form.operator_resolved_at;
  }
  return payload as BasePaymentProviderEventUpdate;
}
