<?php

namespace App\Omnify\Modules\ZoneTemplate\Locales;

/**
 * Localized display names for ZoneTemplate.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class ZoneTemplateLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Zone Template',
        'ja' => 'エリアテンプレート',
        'vi' => 'Mẫu khu vực',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'code' => [
            'en' => 'Zone Code',
            'ja' => 'エリアコード',
            'vi' => 'Mã khu vực',
        ],
        'name' => [
            'en' => 'Zone Name',
            'ja' => 'エリア名',
            'vi' => 'Tên khu vực',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'display_order' => [
            'en' => 'Display Order',
            'ja' => '表示順',
            'vi' => 'Thứ tự hiển thị',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
    ];
}
