<?php

namespace App\Omnify\Modules\ProductionOrder\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\ProductionOrder\Locales\ProductionOrderLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class ProductionOrderUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'order_code' => ['sometimes', 'string', 'max:50'],
            'warehouse_id' => ['sometimes', 'uuid', 'exists:warehouses,id'],
            'output_variant_id' => ['sometimes', 'uuid', 'exists:product_skus,id'],
            'planned_quantity' => ['sometimes', 'numeric'],
            'actual_quantity' => ['nullable', 'numeric'],
            'output_unit' => ['sometimes', 'string', 'max:50'],
            'recipe_multiplier' => ['sometimes', 'numeric'],
            'status' => ['sometimes', 'string'],
            'stock_out_transaction_id' => ['nullable', 'string', 'uuid'],
            'stock_in_transaction_id' => ['nullable', 'string', 'uuid'],
            'note' => ['nullable', 'string'],
            'created_by_id' => ['sometimes', 'string', 'uuid'],
            'approved_by_id' => ['nullable', 'string', 'uuid'],
            'approved_at' => ['nullable', 'date'],
            'started_at' => ['nullable', 'date'],
            'completed_at' => ['nullable', 'date'],
            'organization_id' => ['sometimes', 'uuid', 'exists:organizations,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = ProductionOrderLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'order_code',
            'warehouse_id',
            'output_variant_id',
            'planned_quantity',
            'actual_quantity',
            'output_unit',
            'recipe_multiplier',
            'status',
            'stock_out_transaction_id',
            'stock_in_transaction_id',
            'note',
            'created_by_id',
            'approved_by_id',
            'approved_at',
            'started_at',
            'completed_at',
            'organization_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
