<?php

namespace App\Omnify\Modules\PaymentProviderEvent\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\OrganizationResource;
use App\Http\Resources\PaymentGatewayConnectionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PaymentProviderEventResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'connection_id' => $this->connection_id,
            'connection' => $this->whenLoaded('connection', fn () => new PaymentGatewayConnectionResource($this->connection)),
            'provider' => $this->provider,
            'environment' => $this->environment,
            'state' => $this->state,
            'provider_event_id' => $this->provider_event_id,
            'event_type' => $this->event_type,
            'provider_object_id' => $this->provider_object_id,
            'payload_hash' => $this->payload_hash,
            'outcome' => $this->outcome,
            'delivery_count' => $this->delivery_count,
            'processing_attempts' => $this->processing_attempts,
            'lease_expires_at' => $this->lease_expires_at?->toISOString(),
            'next_retry_at' => $this->next_retry_at?->toISOString(),
            'last_error_code' => $this->last_error_code,
            'received_at' => $this->received_at?->toISOString(),
            'verified_at' => $this->verified_at?->toISOString(),
            'processed_at' => $this->processed_at?->toISOString(),
            'operator_resolution' => $this->operator_resolution,
            'operator_resolved_at' => $this->operator_resolved_at?->toISOString(),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
