<?php

namespace App\Omnify\Modules\MenuScheduleDate\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\MenuSchedule;
use App\Models\Organization;
use App\Omnify\Modules\MenuScheduleDate\Locales\MenuScheduleDateLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * MenuScheduleDateBaseModel
 *
 * @property mixed $date
 * @property int $menu_schedule_id
 * @property int $organization_id
 */
class MenuScheduleDateBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;

    /**
     * The table associated with the model.
     */
    protected $table = 'menu_schedule_dates';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = MenuScheduleDateLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = MenuScheduleDateLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'date',
        'menu_schedule_id',
        'organization_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'date' => 'date',
        ];
    }

    /**
     * Get the menuSchedule that owns this model.
     */
    public function menuSchedule(): BelongsTo
    {
        return $this->belongsTo(MenuSchedule::class, 'menu_schedule_id');
    }

    /**
     * Get the organization that owns this model.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }
}
