<?php

namespace App\Omnify\Modules\StockMovement\Locales;

/**
 * Localized display names for StockMovement.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class StockMovementLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Stock Movement',
        'ja' => '在庫変動',
        'vi' => 'Biến động kho',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'movement_type' => [
            'en' => 'Movement Type',
            'ja' => '変動タイプ',
            'vi' => 'Loại biến động',
        ],
        'quantity' => [
            'en' => 'Quantity',
            'ja' => '数量',
            'vi' => 'Số lượng',
        ],
        'quantity_before' => [
            'en' => 'Quantity Before',
            'ja' => '変動前数量',
            'vi' => 'Tồn trước',
        ],
        'quantity_after' => [
            'en' => 'Quantity After',
            'ja' => '変動後数量',
            'vi' => 'Tồn sau',
        ],
        'unit' => [
            'en' => 'Unit',
            'ja' => '単位',
            'vi' => 'Đơn vị',
        ],
        'created_at' => [
            'en' => 'Created At',
            'ja' => '作成日時',
            'vi' => 'Ngày tạo',
        ],
    ];
}
