<?php

namespace App\Omnify\Modules\TillTenderCategory\Locales;

/**
 * Localized display names for TillTenderCategory.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class TillTenderCategoryLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'TillTenderCategory',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'key' => [
            'en' => 'Key',
            'ja' => 'キー',
            'vi' => 'Khoá',
        ],
        'name' => [
            'en' => 'Name',
            'ja' => '名称',
            'vi' => 'Tên',
        ],
        'sort_order' => [
            'en' => 'Sort Order',
            'ja' => '表示順',
            'vi' => 'Thứ tự',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'is_system' => [
            'en' => 'System Defined',
            'ja' => 'システム定義',
            'vi' => 'Do hệ thống tạo',
        ],
    ];
}
