<?php

namespace App\Omnify\Modules\ProductOptionValue\Locales;

/**
 * Localized display names for ProductOptionValue.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class ProductOptionValueLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Product Option Value',
        'ja' => '商品オプション値',
        'vi' => 'Giá trị tùy chọn',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'value' => [
            'en' => 'Value',
            'ja' => '値',
            'vi' => 'Giá trị',
        ],
        'label' => [
            'en' => 'Label',
            'ja' => 'ラベル',
            'vi' => 'Nhãn hiển thị',
        ],
        'position' => [
            'en' => 'Position',
            'ja' => '順序',
            'vi' => 'Thứ tự',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
    ];
}
