<?php

namespace App\Omnify\Modules\WorkstationLogRequest\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\WorkstationLogRequest\Locales\WorkstationLogRequestLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class WorkstationLogRequestUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'device_id' => ['sometimes', 'string', 'uuid'],
            'branch_id' => ['sometimes', 'string', 'uuid'],
            'organization_id' => ['sometimes', 'string', 'uuid'],
            'requested_by_user_id' => ['nullable', 'string', 'uuid'],
            'window_from' => ['sometimes', 'date'],
            'window_to' => ['sometimes', 'date'],
            'max_records' => ['sometimes', 'integer'],
            'status' => ['sometimes', 'string'],
            'expires_at' => ['sometimes', 'date'],
            'fulfilled_at' => ['nullable', 'date'],
            'received_count' => ['sometimes', 'integer'],
            'rejected_count' => ['sometimes', 'integer'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = WorkstationLogRequestLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'device_id',
            'branch_id',
            'organization_id',
            'requested_by_user_id',
            'window_from',
            'window_to',
            'max_records',
            'status',
            'expires_at',
            'fulfilled_at',
            'received_count',
            'rejected_count',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
