<?php

namespace App\Omnify\Modules\Customer\Locales;

/**
 * Localized display names for Customer.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class CustomerLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Customer',
        'ja' => '顧客',
        'vi' => 'Khách hàng',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'first_name' => [
            'en' => 'First Name',
            'ja' => '名',
            'vi' => 'Tên',
        ],
        'last_name' => [
            'en' => 'Last Name',
            'ja' => '姓',
            'vi' => 'Họ',
        ],
        'phone' => [
            'en' => 'Phone',
            'ja' => '電話番号',
            'vi' => 'Số điện thoại',
        ],
        'email' => [
            'en' => 'Email',
            'ja' => 'メールアドレス',
            'vi' => 'Email',
        ],
        'address' => [
            'en' => 'Address',
            'ja' => '住所',
            'vi' => 'Địa chỉ',
        ],
        'birthday' => [
            'en' => 'Birthday',
            'ja' => '生年月日',
            'vi' => 'Ngày sinh',
        ],
        'gender' => [
            'en' => 'Gender',
            'ja' => '性別',
            'vi' => 'Giới tính',
        ],
        'tax_code' => [
            'en' => 'Tax Code',
            'ja' => '税コード',
            'vi' => 'Mã số thuế',
        ],
        'note' => [
            'en' => 'Note',
            'ja' => '備考',
            'vi' => 'Ghi chú',
        ],
        'loyalty_opted_in' => [
            'en' => 'Loyalty Opted In',
            'ja' => '会員プログラム参加',
            'vi' => 'Tham gia thành viên',
        ],
        'password' => [
            'en' => 'Password',
            'ja' => 'パスワード',
            'vi' => 'Mật khẩu',
        ],
        'google_id' => [
            'en' => 'Google ID',
            'ja' => 'Google ID',
            'vi' => 'Google ID',
        ],
        'remember_token' => [
            'en' => 'Remember Token',
            'ja' => 'Remember Token',
            'vi' => 'Remember Token',
        ],
        'email_verified_at' => [
            'en' => 'Email Verified At',
            'ja' => 'メール認証日時',
            'vi' => 'Thời gian xác minh email',
        ],
    ];
}
