<?php

namespace App\Omnify\Modules\TillSession\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\TillSession\Locales\TillSessionLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class TillSessionUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'session_code' => ['sometimes', 'string', 'max:50'],
            'status' => ['sometimes', 'string'],
            'business_date' => ['sometimes', 'date'],
            'default_currency_code' => ['sometimes', 'string', 'max:3'],
            'prices_include_tax_at_open' => ['nullable', 'boolean'],
            'opening_float_amount' => ['sometimes', 'numeric'],
            'expected_cash_amount' => ['nullable', 'numeric'],
            'counted_cash_amount' => ['nullable', 'numeric'],
            'cash_variance_amount' => ['nullable', 'numeric'],
            'closing_cash_adjustment_amount' => ['nullable', 'numeric'],
            'settled_gross_amount' => ['nullable', 'numeric'],
            'settled_net_amount' => ['nullable', 'numeric'],
            'settled_tax_amount' => ['nullable', 'numeric'],
            'settled_discount_amount' => ['nullable', 'numeric'],
            'opening_note' => ['nullable', 'string'],
            'closing_note' => ['nullable', 'string'],
            'opened_by_id' => ['nullable', 'string', 'uuid'],
            'closed_by_id' => ['nullable', 'string', 'uuid'],
            'opener_name' => ['nullable', 'string', 'max:255'],
            'opened_at' => ['sometimes', 'date'],
            'closed_at' => ['nullable', 'date'],
            'abandoned_at' => ['nullable', 'date'],
            'abandon_reason' => ['nullable', 'string'],
            'force_abandoned' => ['sometimes', 'boolean'],
            'force_abandoned_by_id' => ['nullable', 'string', 'uuid'],
            'force_abandon_reason_code' => ['nullable', 'string'],
            'force_abandon_reason_detail' => ['nullable', 'string'],
            'expired_at' => ['nullable', 'date'],
            'expire_reason' => ['nullable', 'string'],
            'expire_threshold_hours' => ['nullable', 'integer'],
            'chain_id' => ['nullable', 'string', 'uuid'],
            'chain_sequence' => ['sometimes', 'integer'],
            'settlement_kind' => ['nullable', 'string'],
            'settlement_snapshot' => ['nullable', 'array'],
            'till_id' => ['sometimes', 'uuid', 'exists:tills,id'],
            'branch_id' => ['sometimes', 'uuid', 'exists:branches,id'],
            'brand_id' => ['sometimes', 'uuid', 'exists:brands,id'],
            'organization_id' => ['sometimes', 'uuid', 'exists:organizations,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = TillSessionLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'session_code',
            'status',
            'business_date',
            'default_currency_code',
            'prices_include_tax_at_open',
            'opening_float_amount',
            'expected_cash_amount',
            'counted_cash_amount',
            'cash_variance_amount',
            'closing_cash_adjustment_amount',
            'settled_gross_amount',
            'settled_net_amount',
            'settled_tax_amount',
            'settled_discount_amount',
            'opening_note',
            'closing_note',
            'opened_by_id',
            'closed_by_id',
            'opener_name',
            'opened_at',
            'closed_at',
            'abandoned_at',
            'abandon_reason',
            'force_abandoned',
            'force_abandoned_by_id',
            'force_abandon_reason_code',
            'force_abandon_reason_detail',
            'expired_at',
            'expire_reason',
            'expire_threshold_hours',
            'chain_id',
            'chain_sequence',
            'settlement_kind',
            'settlement_snapshot',
            'till_id',
            'branch_id',
            'brand_id',
            'organization_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
