<?php

namespace App\Omnify\Modules\Device\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\Branch;
use App\Models\DevicePaymentOption;
use App\Models\DeviceSigningKey;
use App\Models\Organization;
use App\Models\PaymentAttempt;
use App\Models\PeripheralDevice;
use App\Models\Till;
use App\Models\User;
use App\Omnify\Enums\DeviceStatusEnum;
use App\Omnify\Enums\DeviceTypeEnum;
use App\Omnify\Modules\Device\Locales\DeviceLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * DeviceBaseModel
 *
 * @property string $name
 * @property DeviceTypeEnum $type
 * @property DeviceStatusEnum $status
 * @property string|null $pairing_code
 * @property mixed|null $pairing_expires_at
 * @property string|null $device_token
 * @property mixed|null $paired_at
 * @property mixed|null $last_seen_at
 * @property array|null $device_info
 * @property string|null $notes
 * @property int $organization_id
 * @property int $branch_id
 */
class DeviceBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;

    /**
     * The table associated with the model.
     */
    protected $table = 'devices';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = DeviceLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = DeviceLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'type',
        'status',
        'pairing_code',
        'pairing_expires_at',
        'device_token',
        'paired_at',
        'last_seen_at',
        'device_info',
        'notes',
        'organization_id',
        'branch_id',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'type' => DeviceTypeEnum::class,
            'status' => DeviceStatusEnum::class,
            'pairing_expires_at' => 'datetime',
            'paired_at' => 'datetime',
            'last_seen_at' => 'datetime',
            'device_info' => 'array',
        ];
    }

    /**
     * Get the organization that owns this model.
     */
    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class, 'organization_id');
    }

    /**
     * Get the branch that owns this model.
     */
    public function branch(): BelongsTo
    {
        return $this->belongsTo(Branch::class, 'branch_id');
    }

    /**
     * Auto-generated inverse of DevicePaymentOption.device (ManyToOne).
     */
    public function devicePaymentOptions(): HasMany
    {
        return $this->hasMany(DevicePaymentOption::class, 'device_id');
    }

    /**
     * Auto-generated inverse of DeviceSigningKey.device (ManyToOne).
     */
    public function deviceSigningKeys(): HasMany
    {
        return $this->hasMany(DeviceSigningKey::class, 'device_id');
    }

    /**
     * Auto-generated inverse of PaymentAttempt.device (ManyToOne).
     */
    public function paymentAttempts(): HasMany
    {
        return $this->hasMany(PaymentAttempt::class, 'device_id');
    }

    /**
     * Auto-generated inverse of PeripheralDevice.registeredByDevice (ManyToOne).
     */
    public function peripheralDevices(): HasMany
    {
        return $this->hasMany(PeripheralDevice::class, 'registered_by_device_id');
    }

    /**
     * Auto-generated inverse of Till.device (ManyToOne).
     */
    public function tills(): HasMany
    {
        return $this->hasMany(Till::class, 'device_id');
    }

    /**
     * Boot audit events.
     */
    protected static function booted(): void
    {
        parent::booted();

        static::creating(function ($model) {
            if (auth()->check() && ! $model->created_by_id) {
                $model->created_by_id = auth()->id();
            }
        });

        static::updating(function ($model) {
            if (auth()->check()) {
                $model->updated_by_id = auth()->id();
            }
        });
    }

    /**
     * Get the user who created this record.
     */
    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by_id');
    }

    /**
     * Get the user who last updated this record.
     */
    public function updatedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by_id');
    }
}
