<?php

namespace App\Omnify\Enums;

/**
 * AllergenJurisdiction — Allergen Jurisdiction
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
enum AllergenJurisdictionEnum: string
{
    case Jp = 'jp';
    case Eu = 'eu';
    case Us = 'us';

    /**
     * Localized labels for each case, embedded directly so the generated enum
     * is self-contained and works without Laravel translation files.
     *
     * @var array<string, array<string, string>>
     */
    public const LABELS = [
        'jp' => ['en' => 'Japan', 'ja' => '日本', 'vi' => 'Nhật Bản'],
        'eu' => ['en' => 'European Union', 'ja' => '欧州連合', 'vi' => 'Liên minh Châu Âu'],
        'us' => ['en' => 'United States', 'ja' => '米国', 'vi' => 'Hoa Kỳ'],
    ];

    /**
     * Get the localized label for this enum case.
     *
     * Falls back to the configured app fallback locale, then any defined
     * locale, then the raw value if no labels were declared in the schema.
     */
    public function label(?string $locale = null): string
    {
        $locale = $locale ?? app()->getLocale();
        $labels = self::LABELS[$this->value] ?? [];

        return $labels[$locale]
            ?? $labels[config('app.fallback_locale', 'en')]
            ?? $labels[array_key_first($labels) ?? 'en']
            ?? $this->value;
    }

    /**
     * Get all enum values as a flat list.
     *
     * @return array<int, string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }

    /**
     * Get an array of value → localized label suitable for select dropdowns.
     *
     * @return array<string, string>
     */
    public static function options(?string $locale = null): array
    {
        $out = [];
        foreach (self::cases() as $case) {
            $out[$case->value] = $case->label($locale);
        }

        return $out;
    }
}
