<?php

namespace App\Omnify\Enums;

/**
 * WarehouseType — Warehouse Type
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
enum WarehouseTypeEnum: string
{
    case Main = 'main';
    case Branch = 'branch';
    case Production = 'production';

    /**
     * Localized labels for each case, embedded directly so the generated enum
     * is self-contained and works without Laravel translation files.
     *
     * @var array<string, array<string, string>>
     */
    public const LABELS = [
        'main' => ['en' => 'Main Warehouse', 'ja' => 'メイン倉庫', 'vi' => 'Kho chính'],
        'branch' => ['en' => 'Branch Warehouse', 'ja' => '支店倉庫', 'vi' => 'Kho chi nhánh'],
        'production' => ['en' => 'Production Warehouse', 'ja' => '生産倉庫', 'vi' => 'Kho sản xuất'],
    ];

    /**
     * Get the localized label for this enum case.
     *
     * Falls back to the configured app fallback locale, then any defined
     * locale, then the raw value if no labels were declared in the schema.
     */
    public function label(?string $locale = null): string
    {
        $locale = $locale ?? app()->getLocale();
        $labels = self::LABELS[$this->value] ?? [];

        return $labels[$locale]
            ?? $labels[config('app.fallback_locale', 'en')]
            ?? $labels[array_key_first($labels) ?? 'en']
            ?? $this->value;
    }

    /**
     * Get all enum values as a flat list.
     *
     * @return array<int, string>
     */
    public static function values(): array
    {
        return array_column(self::cases(), 'value');
    }

    /**
     * Get an array of value → localized label suitable for select dropdowns.
     *
     * @return array<string, string>
     */
    public static function options(?string $locale = null): array
    {
        $out = [];
        foreach (self::cases() as $case) {
            $out[$case->value] = $case->label($locale);
        }

        return $out;
    }
}
