<?php

namespace App\Omnify\Modules\PaymentAttempt\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\BranchResource;
use App\Http\Resources\BrandResource;
use App\Http\Resources\CustomerOrderResource;
use App\Http\Resources\DeviceResource;
use App\Http\Resources\OrganizationResource;
use App\Http\Resources\PaymentGatewayConnectionOptionResource;
use App\Http\Resources\PaymentGatewayConnectionResource;
use App\Http\Resources\PaymentPolicyRevisionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class PaymentAttemptResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'brand_id' => $this->brand_id,
            'brand' => $this->whenLoaded('brand', fn () => new BrandResource($this->brand)),
            'branch_id' => $this->branch_id,
            'branch' => $this->whenLoaded('branch', fn () => new BranchResource($this->branch)),
            'customer_order_id' => $this->customer_order_id,
            'customerOrder' => $this->whenLoaded('customerOrder', fn () => new CustomerOrderResource($this->customerOrder)),
            'connection_id' => $this->connection_id,
            'connection' => $this->whenLoaded('connection', fn () => new PaymentGatewayConnectionResource($this->connection)),
            'connection_option_id' => $this->connection_option_id,
            'connectionOption' => $this->whenLoaded('connectionOption', fn () => new PaymentGatewayConnectionOptionResource($this->connectionOption)),
            'policy_revision_id' => $this->policy_revision_id,
            'policyRevision' => $this->whenLoaded('policyRevision', fn () => new PaymentPolicyRevisionResource($this->policyRevision)),
            'device_id' => $this->device_id,
            'device' => $this->whenLoaded('device', fn () => new DeviceResource($this->device)),
            'operation' => $this->operation,
            'state' => $this->state,
            'provider' => $this->provider,
            'environment' => $this->environment,
            'owner_scope' => $this->owner_scope,
            'operator_org_unit_id' => $this->operator_org_unit_id,
            'ownership_revision' => $this->ownership_revision,
            'channel' => $this->channel,
            'currency' => $this->currency,
            'amount_minor' => $this->amount_minor,
            'idempotency_key' => $this->idempotency_key,
            'request_fingerprint' => $this->request_fingerprint,
            'provider_request_key' => $this->provider_request_key,
            'provider_object_id' => $this->provider_object_id,
            'provider_status' => $this->provider_status,
            'next_action' => $this->next_action,
            'error_code' => $this->error_code,
            'retry_count' => $this->retry_count,
            'next_reconciliation_at' => $this->next_reconciliation_at?->toISOString(),
            'version' => $this->version,
            'prepared_at' => $this->prepared_at?->toISOString(),
            'dispatched_at' => $this->dispatched_at?->toISOString(),
            'finalized_at' => $this->finalized_at?->toISOString(),
            'last_swept_at' => $this->last_swept_at?->toISOString(),
            'estimated_fee_minor' => $this->estimated_fee_minor,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
