<?php

namespace App\Omnify\Modules\PersonalAccessToken\Locales;

/**
 * Localized display names for PersonalAccessToken.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class PersonalAccessTokenLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'PersonalAccessToken',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'tokenable_type' => [
            'en' => 'Tokenable Type',
            'ja' => '対象タイプ',
            'vi' => 'Loại đối tượng',
        ],
        'tokenable_id' => [
            'en' => 'Tokenable ID',
            'ja' => '対象ID',
            'vi' => 'ID đối tượng',
        ],
        'name' => [
            'en' => 'Name',
            'ja' => '名称',
            'vi' => 'Tên',
        ],
        'token' => [
            'en' => 'Token Hash',
            'ja' => 'トークンハッシュ',
            'vi' => 'Hash token',
        ],
        'abilities' => [
            'en' => 'Abilities',
            'ja' => '権限',
            'vi' => 'Quyền',
        ],
        'last_used_at' => [
            'en' => 'Last Used At',
            'ja' => '最終使用日時',
            'vi' => 'Lần dùng cuối',
        ],
        'expires_at' => [
            'en' => 'Expires At',
            'ja' => '有効期限',
            'vi' => 'Hết hạn',
        ],
    ];
}
