<?php

namespace App\Omnify\Modules\PaymentGatewayProvider\Locales;

/**
 * Localized display names for PaymentGatewayProvider.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class PaymentGatewayProviderLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Payment Gateway Provider',
        'ja' => '決済ゲートウェイプロバイダー',
        'vi' => 'Nhà cung cấp cổng thanh toán',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'code' => [
            'en' => 'Provider Code',
            'ja' => 'プロバイダーコード',
            'vi' => 'Mã nhà cung cấp',
        ],
        'name' => [
            'en' => 'Name',
            'ja' => '名称',
            'vi' => 'Tên',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'sort_order' => [
            'en' => 'Sort Order',
            'ja' => '表示順',
            'vi' => 'Thứ tự',
        ],
    ];
}
