<?php

namespace App\Omnify\Modules\CashDeviceInventorySnapshot\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\CashDeviceInventorySnapshot\Locales\CashDeviceInventorySnapshotLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class CashDeviceInventorySnapshotUpdateRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'peripheral_device_id' => ['sometimes', 'uuid', 'exists:peripheral_devices,id'],
            'till_session_id' => ['sometimes', 'uuid', 'exists:till_sessions,id'],
            'count_phase' => ['sometimes', 'string'],
            'denominations' => ['sometimes', 'array'],
            'uncertain_denominations' => ['nullable', 'array'],
            'bill_reject_count' => ['sometimes', 'integer'],
            'total_minor' => ['sometimes', 'integer'],
            'machine_seq_no' => ['nullable', 'integer'],
            'captured_at' => ['sometimes', 'date'],
            'branch_id' => ['sometimes', 'uuid', 'exists:branches,id'],
            'organization_id' => ['sometimes', 'uuid', 'exists:organizations,id'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = CashDeviceInventorySnapshotLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'peripheral_device_id',
            'till_session_id',
            'count_phase',
            'denominations',
            'uncertain_denominations',
            'bill_reject_count',
            'total_minor',
            'machine_seq_no',
            'captured_at',
            'branch_id',
            'organization_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
