/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { User } from './User';

/**
 * ポイント交換商品店舗
 */
export interface PointRewardBranch {
  id: number;
  toggled_by_id?: string | null;
  toggledBy?: User | null;
  is_available: boolean;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for PointRewardBranch
 */
export const pointRewardBranchI18n = {
  label: {"ja":"ポイント交換商品店舗","en":"Point Reward Branch","vi":"Phần thưởng theo chi nhánh"},
  fields: {
    toggled_by: {
      label: {"ja":"切替者","en":"Toggled By","vi":"Người bấm"},
      placeholder: {"ja":"切替者を入力","en":"Enter Toggled By","vi":"Nhập Người bấm"},
    },
    is_available: {
      label: {"ja":"提供中","en":"Available","vi":"Đang bật"},
      placeholder: {"ja":"提供中を入力","en":"Enter Available","vi":"Nhập Đang bật"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for PointRewardBranch */
export const basePointRewardBranchSchemas = {
  is_available: z.boolean(),
} as const;

/** Create schema for PointRewardBranch */
export const basePointRewardBranchCreateSchema = z.object({
  is_available: basePointRewardBranchSchemas.is_available,
});

/** Update schema for PointRewardBranch */
export const basePointRewardBranchUpdateSchema = basePointRewardBranchCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BasePointRewardBranchCreate = z.infer<typeof basePointRewardBranchCreateSchema>;
export type BasePointRewardBranchUpdate = z.infer<typeof basePointRewardBranchUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getPointRewardBranchLabel(locale: string): string {
  return pointRewardBranchI18n.label[locale as keyof typeof pointRewardBranchI18n.label] ?? pointRewardBranchI18n.label['en'] ?? 'PointRewardBranch';
}

/** Get field label for a specific locale */
export function getPointRewardBranchFieldLabel(field: string, locale: string): string {
  const fields = pointRewardBranchI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getPointRewardBranchFieldPlaceholder(field: string, locale: string): string {
  const fields = pointRewardBranchI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for PointRewardBranch.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const pointRewardBranchMetadata = {
  modelName: "PointRewardBranch",
  table: "point_reward_branches",

  fields: {
    toggled_by_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "User",
        table: "users",
        onDelete: "SET NULL",
      },
      label: {},
    },
    is_available: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "提供中",
        en: "Available",
        vi: "Đang bật",
      },
      placeholder: {
        ja: "提供中を入力",
        en: "Enter Available",
        vi: "Nhập Đang bật",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["is_available"] as const,
  enumFields: [] as const,
  relationFields: ["toggled_by_id"] as const,
} as const;

export type PointRewardBranchFieldName = keyof typeof pointRewardBranchMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a PointRewardBranch. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface PointRewardBranchCreateFormState {
  toggled_by_id?: string | null;
  is_available: boolean;
}

/** Form-state shape for updating a PointRewardBranch. Every field optional. */
export interface PointRewardBranchUpdateFormState {
  toggled_by_id?: string | null;
  is_available?: boolean;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyPointRewardBranchCreateForm(): PointRewardBranchCreateFormState {
  return {
    toggled_by_id: '',
    is_available: true,
  };
}

/** Convert create form state into the payload that basePointRewardBranchCreateSchema accepts. */
export function buildPointRewardBranchCreatePayload(form: PointRewardBranchCreateFormState): BasePointRewardBranchCreate {
  const payload: Record<string, unknown> = {
    toggled_by_id: form.toggled_by_id?.toString().trim() || null,
    is_available: form.is_available,
  };

  return payload as BasePointRewardBranchCreate;
}

/** Convert update form state into the payload that basePointRewardBranchUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildPointRewardBranchUpdatePayload(form: PointRewardBranchUpdateFormState): BasePointRewardBranchUpdate {
  const payload: Record<string, unknown> = {};
  if (form.toggled_by_id !== undefined) {
    payload.toggled_by_id = form.toggled_by_id?.toString().trim() ?? null;
  }
  if (form.is_available !== undefined) {
    payload.is_available = form.is_available;
  }
  return payload as BasePointRewardBranchUpdate;
}
