/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import type { Locale } from '../common';
import { buildI18nPayload, emptyLocaleMap } from '../payload-helpers';
import { z } from 'zod';
import type { DateTimeString } from '../common';
import { PostStatus } from '../enum/PostStatus';
import type { Branch } from './Branch';
import type { Organization } from './Organization';
import type { PostCategory } from './PostCategory';
import type { PostTag } from './PostTag';
import type { User } from './User';

/**
 * 投稿
 */
export interface Post {
  id: string;
  organization_id: string;
  organization?: Organization;
  author_id?: string | null;
  author?: User | null;
  category_id?: string | null;
  category?: PostCategory | null;
  branch_id?: string | null;
  branch?: Branch | null;
  tags?: PostTag[];
  slug: string;
  title: string;
  excerpt?: string | null;
  content?: string | null;
  cover_image_url?: string | null;
  status: PostStatus;
  published_at?: DateTimeString | null;
  is_pinned: boolean;
  view_count: number;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Post
 */
export const postI18n = {
  label: {"ja":"投稿","en":"Post","vi":"Bài viết"},
  fields: {
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    author: {
      label: {"ja":"著者","en":"Author","vi":"Tác giả"},
      placeholder: {"ja":"著者を入力","en":"Enter Author","vi":"Nhập Tác giả"},
    },
    category: {
      label: {"ja":"カテゴリー","en":"Category","vi":"Danh mục"},
      placeholder: {"ja":"カテゴリーを入力","en":"Enter Category","vi":"Nhập Danh mục"},
    },
    branch: {
      label: {"ja":"店舗","en":"Branch","vi":"Chi nhánh"},
      placeholder: {"ja":"店舗を入力","en":"Enter Branch","vi":"Nhập Chi nhánh"},
    },
    tags: {
      label: {"ja":"タグ","en":"Tags","vi":"Thẻ"},
      placeholder: {"ja":"タグを入力","en":"Enter Tags","vi":"Nhập Thẻ"},
    },
    slug: {
      label: {"ja":"スラッグ","en":"Slug","vi":"Slug"},
      placeholder: {"ja":"スラッグを入力","en":"Enter Slug","vi":"Nhập Slug"},
    },
    title: {
      label: {"ja":"タイトル","en":"Title","vi":"Tiêu đề"},
      placeholder: {"ja":"タイトルを入力","en":"Enter Title","vi":"Nhập Tiêu đề"},
    },
    excerpt: {
      label: {"ja":"抜粋","en":"Excerpt","vi":"Tóm tắt"},
      placeholder: {"ja":"抜粋を入力","en":"Enter Excerpt","vi":"Nhập Tóm tắt"},
    },
    content: {
      label: {"ja":"本文","en":"Content","vi":"Nội dung"},
      placeholder: {"ja":"本文を入力","en":"Enter Content","vi":"Nhập Nội dung"},
    },
    cover_image_url: {
      label: {"ja":"カバー画像URL","en":"Cover Image URL","vi":"URL ảnh bìa"},
      placeholder: {"ja":"カバー画像URLを入力","en":"Enter Cover Image URL","vi":"Nhập URL ảnh bìa"},
    },
    status: {
      label: {"ja":"ステータス","en":"Status","vi":"Trạng thái"},
      placeholder: {"ja":"ステータスを入力","en":"Enter Status","vi":"Nhập Trạng thái"},
    },
    published_at: {
      label: {"ja":"公開日時","en":"Published At","vi":"Thời điểm xuất bản"},
      placeholder: {"ja":"公開日時を入力","en":"Enter Published At","vi":"Nhập Thời điểm xuất bản"},
    },
    is_pinned: {
      label: {"ja":"ピン留め","en":"Pinned","vi":"Ghim"},
      placeholder: {"ja":"ピン留めを入力","en":"Enter Pinned","vi":"Nhập Ghim"},
    },
    view_count: {
      label: {"ja":"閲覧数","en":"View Count","vi":"Lượt xem"},
      placeholder: {"ja":"閲覧数を入力","en":"Enter View Count","vi":"Nhập Lượt xem"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Post */
export const basePostSchemas = {
  slug: z.string().min(1).max(180),
  title: z.string().min(1).max(200),
  excerpt: z.string().optional().nullable(),
  content: z.string().optional().nullable(),
  cover_image_url: z.string().max(500).optional().nullable(),
  status: z.nativeEnum(PostStatus),
  published_at: z.string().datetime({ offset: true }).optional().nullable(),
  is_pinned: z.boolean(),
  view_count: z.number().int(),
} as const;

/** Create schema for Post */
export const basePostCreateSchema = z.object({
  slug: basePostSchemas.slug,
  title: basePostSchemas.title,
  excerpt: basePostSchemas.excerpt,
  content: basePostSchemas.content,
  cover_image_url: basePostSchemas.cover_image_url,
  status: basePostSchemas.status,
  published_at: basePostSchemas.published_at,
  is_pinned: basePostSchemas.is_pinned,
  view_count: basePostSchemas.view_count,
  ja: z.object({
    title: z.string().max(200).optional().nullable(),
    excerpt: z.string().optional().nullable(),
    content: z.string().optional().nullable(),
  }).optional(),
  en: z.object({
    title: z.string().max(200).optional().nullable(),
    excerpt: z.string().optional().nullable(),
    content: z.string().optional().nullable(),
  }).optional(),
  vi: z.object({
    title: z.string().max(200).optional().nullable(),
    excerpt: z.string().optional().nullable(),
    content: z.string().optional().nullable(),
  }).optional(),
});

/** Update schema for Post */
export const basePostUpdateSchema = basePostCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BasePostCreate = z.infer<typeof basePostCreateSchema>;
export type BasePostUpdate = z.infer<typeof basePostUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getPostLabel(locale: string): string {
  return postI18n.label[locale as keyof typeof postI18n.label] ?? postI18n.label['en'] ?? 'Post';
}

/** Get field label for a specific locale */
export function getPostFieldLabel(field: string, locale: string): string {
  const fields = postI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getPostFieldPlaceholder(field: string, locale: string): string {
  const fields = postI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for Post.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const postMetadata = {
  modelName: "Post",
  table: "posts",

  fields: {
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    author_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "User",
        table: "users",
        onDelete: "SET NULL",
      },
      label: {},
    },
    category_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "PostCategory",
        table: "post_categories",
        onDelete: "SET NULL",
      },
      label: {},
    },
    branch_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Branch",
        table: "branches",
        onDelete: "CASCADE",
      },
      label: {},
    },
    slug: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 180,
      },
      label: {
        ja: "スラッグ",
        en: "Slug",
        vi: "Slug",
      },
      placeholder: {
        ja: "スラッグを入力",
        en: "Enter Slug",
        vi: "Nhập Slug",
      },
      description: {
        ja: "ルーティング用のURLセーフな識別子。組織内で一意。",
        en: "URL-safe identifier for routing. Unique per organization.",
        vi: "Mã định danh URL-safe cho routing. Duy nhất trong phạm vi tổ chức.",
      },
    },
    title: {
      type: "string",
      required: true,
      nullable: false,
      translatable: true,
      validation: {
        maxLength: 200,
      },
      label: {
        ja: "タイトル",
        en: "Title",
        vi: "Tiêu đề",
      },
      placeholder: {
        ja: "タイトルを入力",
        en: "Enter Title",
        vi: "Nhập Tiêu đề",
      },
    },
    excerpt: {
      type: "text",
      required: false,
      nullable: true,
      translatable: true,
      validation: {},
      label: {
        ja: "抜粋",
        en: "Excerpt",
        vi: "Tóm tắt",
      },
      placeholder: {
        ja: "抜粋を入力",
        en: "Enter Excerpt",
        vi: "Nhập Tóm tắt",
      },
      description: {
        ja: "リスト表示とソーシャルプレビュー用の短い要約（280文字以内推奨）。",
        en: "Short summary for listings and social preview (recommended ≤ 280 chars).",
        vi: "Tóm tắt ngắn cho trang list và social preview (khuyến nghị ≤ 280 ký tự).",
      },
    },
    content: {
      type: "text",
      required: false,
      nullable: true,
      translatable: true,
      validation: {},
      label: {
        ja: "本文",
        en: "Content",
        vi: "Nội dung",
      },
      placeholder: {
        ja: "本文を入力",
        en: "Enter Content",
        vi: "Nhập Nội dung",
      },
      description: {
        ja: "記事本文。Markdown またはサニタイズ済み HTML（サービス側で強制）。",
        en: "Full article body. Markdown or sanitized HTML (service-enforced).",
        vi: "Nội dung bài đầy đủ. Markdown hoặc HTML đã sanitize (service enforce).",
      },
    },
    cover_image_url: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 500,
      },
      label: {
        ja: "カバー画像URL",
        en: "Cover Image URL",
        vi: "URL ảnh bìa",
      },
      placeholder: {
        ja: "カバー画像URLを入力",
        en: "Enter Cover Image URL",
        vi: "Nhập URL ảnh bìa",
      },
    },
    status: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "PostStatus",
      enumValues: ["Draft", "Published", "Archived"] as const,
      label: {
        ja: "ステータス",
        en: "Status",
        vi: "Trạng thái",
      },
      placeholder: {
        ja: "ステータスを入力",
        en: "Enter Status",
        vi: "Nhập Trạng thái",
      },
    },
    published_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "公開日時",
        en: "Published At",
        vi: "Thời điểm xuất bản",
      },
      placeholder: {
        ja: "公開日時を入力",
        en: "Enter Published At",
        vi: "Nhập Thời điểm xuất bản",
      },
      description: {
        ja: "投稿が公開される日時。status=Published かつ過去日時である必要がある。",
        en: "When the post goes public. Must be set AND status=Published AND in the past for post to be visible.",
        vi: "Thời điểm bài đi public. Phải set + status=Published + đã qua thì bài mới hiển thị.",
      },
    },
    is_pinned: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "ピン留め",
        en: "Pinned",
        vi: "Ghim",
      },
      placeholder: {
        ja: "ピン留めを入力",
        en: "Enter Pinned",
        vi: "Nhập Ghim",
      },
      description: {
        ja: "true のとき published_at に関わらずリスト先頭に表示。",
        en: "When true, appears at top of listings regardless of published_at.",
        vi: "Khi true, luôn hiện đầu list bất kể published_at.",
      },
    },
    view_count: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "閲覧数",
        en: "View Count",
        vi: "Lượt xem",
      },
      placeholder: {
        ja: "閲覧数を入力",
        en: "Enter View Count",
        vi: "Nhập Lượt xem",
      },
    },
  },

  translatableFields: ["title", "excerpt", "content"] as const,
  requiredFields: ["organization_id", "slug", "title", "status", "is_pinned", "view_count"] as const,
  enumFields: ["status"] as const,
  relationFields: ["organization_id", "author_id", "category_id", "branch_id"] as const,
} as const;

export type PostFieldName = keyof typeof postMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a Post. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface PostCreateFormState {
  organization_id: string;
  author_id?: string | null;
  category_id?: string | null;
  branch_id?: string | null;
  slug: string;
  title: Record<Locale, string>;
  excerpt: Record<Locale, string>;
  content: Record<Locale, string>;
  cover_image_url?: string | null;
  status: PostStatus;
  published_at?: string | null;
  is_pinned: boolean;
  view_count: number;
}

/** Form-state shape for updating a Post. Every field optional. */
export interface PostUpdateFormState {
  organization_id?: string;
  author_id?: string | null;
  category_id?: string | null;
  branch_id?: string | null;
  slug?: string;
  title?: Record<Locale, string>;
  excerpt?: Record<Locale, string>;
  content?: Record<Locale, string>;
  cover_image_url?: string | null;
  status?: PostStatus;
  published_at?: string | null;
  is_pinned?: boolean;
  view_count?: number;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyPostCreateForm(): PostCreateFormState {
  return {
    organization_id: '',
    author_id: '',
    category_id: '',
    branch_id: '',
    slug: '',
    title: emptyLocaleMap(),
    excerpt: emptyLocaleMap(),
    content: emptyLocaleMap(),
    cover_image_url: '',
    status: PostStatus.Draft,
    published_at: '',
    is_pinned: false,
    view_count: 0,
  };
}

/** Convert create form state into the payload that basePostCreateSchema accepts. */
export function buildPostCreatePayload(form: PostCreateFormState): BasePostCreate {
  const payload: Record<string, unknown> = {
    organization_id: form.organization_id.trim(),
    author_id: form.author_id?.toString().trim() || null,
    category_id: form.category_id?.toString().trim() || null,
    branch_id: form.branch_id?.toString().trim() || null,
    slug: form.slug.trim(),
    title: (form.title["ja"] ?? '').trim(),
    excerpt: (form.excerpt["ja"] ?? '').trim(),
    content: (form.content["ja"] ?? '').trim(),
    cover_image_url: form.cover_image_url?.toString().trim() || null,
    status: form.status,
    published_at: form.published_at,
    is_pinned: form.is_pinned,
    view_count: form.view_count,
  };

  // Per-locale sub-objects (matches issue #53 wire shape).
  const i18n = buildI18nPayload({
    title: form.title,
    excerpt: form.excerpt,
    content: form.content,
  });
  Object.assign(payload, i18n);

  return payload as BasePostCreate;
}

/** Convert update form state into the payload that basePostUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildPostUpdatePayload(form: PostUpdateFormState): BasePostUpdate {
  const payload: Record<string, unknown> = {};
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.author_id !== undefined) {
    payload.author_id = form.author_id?.toString().trim() ?? null;
  }
  if (form.category_id !== undefined) {
    payload.category_id = form.category_id?.toString().trim() ?? null;
  }
  if (form.branch_id !== undefined) {
    payload.branch_id = form.branch_id?.toString().trim() ?? null;
  }
  if (form.slug !== undefined) {
    payload.slug = form.slug?.toString().trim() ?? null;
  }
  if (form.title !== undefined) {
    payload.title = (form.title["ja"] ?? '').trim();
  }
  if (form.excerpt !== undefined) {
    payload.excerpt = (form.excerpt["ja"] ?? '').trim();
  }
  if (form.content !== undefined) {
    payload.content = (form.content["ja"] ?? '').trim();
  }
  if (form.cover_image_url !== undefined) {
    payload.cover_image_url = form.cover_image_url?.toString().trim() ?? null;
  }
  if (form.status !== undefined) {
    payload.status = form.status;
  }
  if (form.published_at !== undefined) {
    payload.published_at = form.published_at;
  }
  if (form.is_pinned !== undefined) {
    payload.is_pinned = form.is_pinned;
  }
  if (form.view_count !== undefined) {
    payload.view_count = form.view_count;
  }

  // Per-locale sub-objects only for fields the user touched.
  const localeInput: Record<string, Record<string, string> | undefined> = {};
  if (form.title !== undefined) localeInput.title = form.title;
  if (form.excerpt !== undefined) localeInput.excerpt = form.excerpt;
  if (form.content !== undefined) localeInput.content = form.content;
  Object.assign(payload, buildI18nPayload(localeInput));
  return payload as BasePostUpdate;
}
