/**
 * DO NOT EDIT - Auto-generated by Omnify.
 * @generated by omnify
 */
import type { Product, ProductCreateFormState, ProductUpdateFormState } from "./Product";

export interface ProductFilters {
  page?: number;
  per_page?: number;
  search?: string;
  status?: string;
  is_hidden?: boolean;
  with_trashed?: boolean;
  only_trashed?: boolean;
  sort?: string;
}

export interface ProductLookupItem {
  id: string;
  name: string;
  slug: string;
}

function toParams(filters: Record<string, any>): string {
  const p = new URLSearchParams();
  if (filters.page) p.set("page", String(filters.page));
  if (filters.per_page) p.set("per_page", String(filters.per_page));
  if (filters.search) p.set("search", filters.search);
  if (filters.status) p.set("status", filters.status);
  if (filters.is_hidden !== undefined) p.set("is_hidden", filters.is_hidden ? "1" : "0");
  if (filters.with_trashed) p.set("with_trashed", "1");
  if (filters.only_trashed) p.set("only_trashed", "1");
  if (filters.sort) p.set("sort", filters.sort);
  return p.toString();
}

// Factory — URL is injected by user-land, not hardcoded.
export function createProductBaseService(baseUrl: (slug: string, path?: string) => string) {
  return {
    list: (slug: string, filters: ProductFilters = {}) =>
      apiFetch<PaginatedResponse<Product>>(
        `${baseUrl(slug)}?${toParams({ per_page: 25, ...filters })}`
      ),

    getById: (slug: string, id: string) =>
      apiFetch<{ data: Product }>(baseUrl(slug, `/${id}`)),

    lookup: (slug: string) =>
      apiFetch<{ data: ProductLookupItem[] }>(baseUrl(slug, "/lookup")),

    create: (slug: string, data: ProductCreateFormState) =>
      apiFetch<{ data: Product }>(baseUrl(slug), {
        method: "POST",
        body: JSON.stringify(data),
      }),

    update: (slug: string, id: string, data: Partial<ProductUpdateFormState>) =>
      apiFetch<{ data: Product }>(baseUrl(slug, `/${id}`), {
        method: "PUT",
        body: JSON.stringify(data),
      }),

    delete: (slug: string, id: string) =>
      apiFetch<null>(baseUrl(slug, `/${id}`), { method: "DELETE" }),

    restore: (slug: string, id: string) =>
      apiFetch<{ data: Product }>(baseUrl(slug, `/${id}/restore`), {
        method: "POST",
      }),
  };
}

export type ProductBaseServiceType = ReturnType<typeof createProductBaseService>;
