<?php

namespace App\Omnify\Modules\User\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\BranchFloatingSectionOverride;
use App\Models\BranchScheduleOverride;
use App\Models\MaterialLotReservation;
use App\Models\MenuAvailabilityEvent;
use App\Models\NotificationAudience;
use App\Models\NotificationDigestPreference;
use App\Models\NotificationPreference;
use App\Models\NotificationRule;
use App\Models\NotificationSchedule;
use App\Models\NotificationTemplate;
use App\Models\PointRewardBranch;
use App\Models\Post;
use App\Models\PostBranch;
use App\Models\PrintImageAsset;
use App\Models\PrintJob;
use App\Models\PrintJobResolution;
use App\Models\PrintTemplate;
use App\Models\Product;
use App\Models\RecallDrill;
use App\Models\Recipe;
use App\Models\RoleUserPivot;
use App\Models\SettlementReportBatch;
use App\Omnify\Modules\User\Locales\UserLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * UserBaseModel
 *
 * @property string $name
 * @property string $email
 * @property string|null $password
 * @property string|null $remember_token
 * @property mixed|null $email_verified_at
 * @property bool $is_active
 * @property string|null $avatar_url
 * @property string|null $locale
 * @property string|null $timezone
 * @property string|null $console_user_id
 * @property string|null $console_organization_id
 * @property string|null $console_access_token
 * @property string|null $console_refresh_token
 * @property mixed|null $console_token_expires_at
 * @property string|null $console_branch_id
 * @property mixed|null $last_org_sync_at
 */
class UserBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;

    /**
     * The table associated with the model.
     */
    protected $table = 'users';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = UserLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = UserLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'remember_token',
        'email_verified_at',
        'is_active',
        'avatar_url',
        'locale',
        'timezone',
        'console_user_id',
        'console_organization_id',
        'console_access_token',
        'console_refresh_token',
        'console_token_expires_at',
        'console_branch_id',
        'last_org_sync_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'is_active' => 'boolean',
            'console_token_expires_at' => 'datetime',
            'last_org_sync_at' => 'datetime',
        ];
    }

    /**
     * Auto-generated inverse of BranchFloatingSectionOverride.updatedBy (ManyToOne).
     */
    public function branchFloatingSectionOverrides(): HasMany
    {
        return $this->hasMany(BranchFloatingSectionOverride::class, 'updated_by_id');
    }

    /**
     * Auto-generated inverse of BranchScheduleOverride.updatedBy (ManyToOne).
     */
    public function branchScheduleOverrides(): HasMany
    {
        return $this->hasMany(BranchScheduleOverride::class, 'updated_by_id');
    }

    /**
     * Auto-generated inverse of MaterialLotReservation.reservedBy (ManyToOne).
     */
    public function materialLotReservations(): HasMany
    {
        return $this->hasMany(MaterialLotReservation::class, 'reserved_by_id');
    }

    /**
     * Auto-generated inverse of MenuAvailabilityEvent.actedByUser (ManyToOne).
     */
    public function menuAvailabilityEvents(): HasMany
    {
        return $this->hasMany(MenuAvailabilityEvent::class, 'acted_by_user_id');
    }

    /**
     * Auto-generated inverse of NotificationAudience.createdBy (ManyToOne).
     */
    public function notificationAudiences(): HasMany
    {
        return $this->hasMany(NotificationAudience::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of NotificationDigestPreference.user (ManyToOne).
     */
    public function notificationDigestPreferences(): HasMany
    {
        return $this->hasMany(NotificationDigestPreference::class, 'user_id');
    }

    /**
     * Auto-generated inverse of NotificationPreference.user (ManyToOne).
     */
    public function notificationPreferences(): HasMany
    {
        return $this->hasMany(NotificationPreference::class, 'user_id');
    }

    /**
     * Auto-generated inverse of NotificationRule.createdBy (ManyToOne).
     */
    public function notificationRules(): HasMany
    {
        return $this->hasMany(NotificationRule::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of NotificationSchedule.createdBy (ManyToOne).
     */
    public function notificationSchedules(): HasMany
    {
        return $this->hasMany(NotificationSchedule::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of NotificationTemplate.createdBy (ManyToOne).
     */
    public function notificationTemplates(): HasMany
    {
        return $this->hasMany(NotificationTemplate::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of PointRewardBranch.toggledBy (ManyToOne).
     */
    public function pointRewardBranches(): HasMany
    {
        return $this->hasMany(PointRewardBranch::class, 'toggled_by_id');
    }

    /**
     * Auto-generated inverse of Post.author (ManyToOne).
     */
    public function posts(): HasMany
    {
        return $this->hasMany(Post::class, 'author_id');
    }

    /**
     * Auto-generated inverse of PostBranch.toggledBy (ManyToOne).
     */
    public function postBranches(): HasMany
    {
        return $this->hasMany(PostBranch::class, 'toggled_by_id');
    }

    /**
     * Auto-generated inverse of PrintImageAsset.createdBy (ManyToOne).
     */
    public function printImageAssets(): HasMany
    {
        return $this->hasMany(PrintImageAsset::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of PrintJob.requestedBy (ManyToOne).
     */
    public function printJobs(): HasMany
    {
        return $this->hasMany(PrintJob::class, 'requested_by_id');
    }

    /**
     * Auto-generated inverse of PrintJobResolution.resolvedBy (ManyToOne).
     */
    public function printJobResolutions(): HasMany
    {
        return $this->hasMany(PrintJobResolution::class, 'resolved_by_id');
    }

    /**
     * Auto-generated inverse of PrintTemplate.createdBy (ManyToOne).
     */
    public function printTemplates(): HasMany
    {
        return $this->hasMany(PrintTemplate::class, 'created_by_id');
    }

    /**
     * Auto-generated inverse of Product.approved_by (ManyToOne).
     */
    public function products(): HasMany
    {
        return $this->hasMany(Product::class, 'approved_by_id');
    }

    /**
     * Auto-generated inverse of RecallDrill.triggeredBy (ManyToOne).
     */
    public function recallDrills(): HasMany
    {
        return $this->hasMany(RecallDrill::class, 'triggered_by_id');
    }

    /**
     * Auto-generated inverse of Recipe.approved_by (ManyToOne).
     */
    public function recipes(): HasMany
    {
        return $this->hasMany(Recipe::class, 'approved_by_id');
    }

    /**
     * Auto-generated inverse of RoleUserPivot.user (ManyToOne).
     */
    public function roleUserPivots(): HasMany
    {
        return $this->hasMany(RoleUserPivot::class, 'user_id');
    }

    /**
     * Auto-generated inverse of SettlementReportBatch.importedBy (ManyToOne).
     */
    public function settlementReportBatches(): HasMany
    {
        return $this->hasMany(SettlementReportBatch::class, 'imported_by_id');
    }
}
