<?php

namespace App\Omnify\Modules\GenealogyLink\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\GenealogyLink\Locales\GenealogyLinkLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class GenealogyLinkStoreRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'parent_lot_id' => ['required', 'uuid', 'exists:material_lots,id'],
            'child_lot_id' => ['nullable', 'uuid', 'exists:material_lots,id'],
            'customer_order_id' => ['nullable', 'string', 'uuid'],
            'qty_consumed' => ['required', 'numeric'],
            'unit' => ['required', 'string', 'max:50'],
            'consumed_at' => ['required', 'date'],
            'source_event_type' => ['required', 'string', 'max:50'],
            'source_event_id' => ['required', 'string', 'uuid'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = GenealogyLinkLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'parent_lot_id',
            'child_lot_id',
            'customer_order_id',
            'qty_consumed',
            'unit',
            'consumed_at',
            'source_event_type',
            'source_event_id',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
