<?php

namespace App\Omnify\Modules\SettlementReportBatch\Locales;

/**
 * Localized display names for SettlementReportBatch.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class SettlementReportBatchLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'SettlementReportBatch',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'provider' => [
            'en' => 'Provider',
            'ja' => 'プロバイダ',
            'vi' => 'Nhà cung cấp',
        ],
        'cycle_label' => [
            'en' => 'Cycle Label',
            'ja' => '精算サイクル',
            'vi' => 'Kỳ đối soát',
        ],
        'file_hash' => [
            'en' => 'File Hash',
            'ja' => 'ファイルハッシュ',
            'vi' => 'Hash tệp',
        ],
        'row_count' => [
            'en' => 'Row Count',
            'ja' => '行数',
            'vi' => 'Số dòng',
        ],
        'matched_count' => [
            'en' => 'Matched Count',
            'ja' => '突合済',
            'vi' => 'Số dòng khớp',
        ],
        'orphan_count' => [
            'en' => 'Orphan Count',
            'ja' => '孤立行',
            'vi' => 'Số dòng mồ côi',
        ],
        'imported_at' => [
            'en' => 'Imported At',
            'ja' => '取込日時',
            'vi' => 'Nhập lúc',
        ],
        'status' => [
            'en' => 'Status',
            'ja' => '状態',
            'vi' => 'Trạng thái',
        ],
    ];
}
