<?php

namespace App\Omnify\Modules\ProductionOrder\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\OrganizationResource;
use App\Http\Resources\ProductionOrderItemResource;
use App\Http\Resources\ProductSkuResource;
use App\Http\Resources\WarehouseResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class ProductionOrderResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'order_code' => $this->order_code,
            'warehouse_id' => $this->warehouse_id,
            'warehouse' => $this->whenLoaded('warehouse', fn () => new WarehouseResource($this->warehouse)),
            'output_variant_id' => $this->output_variant_id,
            'outputVariant' => $this->whenLoaded('outputVariant', fn () => new ProductSkuResource($this->outputVariant)),
            'planned_quantity' => $this->planned_quantity,
            'actual_quantity' => $this->actual_quantity,
            'output_unit' => $this->output_unit,
            'recipe_multiplier' => $this->recipe_multiplier,
            'status' => $this->status,
            'stock_out_transaction_id' => $this->stock_out_transaction_id,
            'stock_in_transaction_id' => $this->stock_in_transaction_id,
            'note' => $this->note,
            'created_by_id' => $this->created_by_id,
            'approved_by_id' => $this->approved_by_id,
            'approved_at' => $this->approved_at?->toISOString(),
            'started_at' => $this->started_at?->toISOString(),
            'completed_at' => $this->completed_at?->toISOString(),
            'items' => $this->whenLoaded('items', fn () => ProductionOrderItemResource::collection($this->items)),
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
            'deleted_at' => $this->deleted_at?->toISOString(),
        ];
    }
}
