/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 決済ゲートウェイ接続
 */
export type PaymentGatewayConnectionChargeModel = 'direct' | 'destination' | 'separate_charges_and_transfers' | 'provider_native';

/** All PaymentGatewayConnectionChargeModel values */
export const PaymentGatewayConnectionChargeModelValues: PaymentGatewayConnectionChargeModel[] = ['direct', 'destination', 'separate_charges_and_transfers', 'provider_native'];

/** Type guard for PaymentGatewayConnectionChargeModel */
export function isPaymentGatewayConnectionChargeModel(value: unknown): value is PaymentGatewayConnectionChargeModel {
  return PaymentGatewayConnectionChargeModelValues.includes(value as PaymentGatewayConnectionChargeModel);
}

/** Get label for PaymentGatewayConnectionChargeModel value */
export function getPaymentGatewayConnectionChargeModelLabel(value: PaymentGatewayConnectionChargeModel): string {
  return value;
}

/** Get extra metadata for PaymentGatewayConnectionChargeModel value */
export function getPaymentGatewayConnectionChargeModelExtra(_value: PaymentGatewayConnectionChargeModel): Record<string, unknown> | undefined {
  return undefined;
}
