/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 商品タイプ
 */
export type ProductTypeProductForm = 'physical' | 'digital';

/** All ProductTypeProductForm values */
export const ProductTypeProductFormValues: ProductTypeProductForm[] = ['physical', 'digital'];

/** Type guard for ProductTypeProductForm */
export function isProductTypeProductForm(value: unknown): value is ProductTypeProductForm {
  return ProductTypeProductFormValues.includes(value as ProductTypeProductForm);
}

/** Get label for ProductTypeProductForm value */
export function getProductTypeProductFormLabel(value: ProductTypeProductForm): string {
  return value;
}

/** Get extra metadata for ProductTypeProductForm value */
export function getProductTypeProductFormExtra(_value: ProductTypeProductForm): Record<string, unknown> | undefined {
  return undefined;
}
