/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * レジセッションステータス
 */
export enum TillSessionStatus {
  Open = 'open',
  Closing = 'closing',
  Settled = 'settled',
  Abandoned = 'abandoned',
  Expired = 'expired',
}

/** All TillSessionStatus values */
export const TillSessionStatusValues = Object.values(TillSessionStatus) as TillSessionStatus[];

/** Type guard for TillSessionStatus */
export function isTillSessionStatus(value: unknown): value is TillSessionStatus {
  return TillSessionStatusValues.includes(value as TillSessionStatus);
}

const tillSessionStatusLabels: Partial<Record<TillSessionStatus, Record<string, string>>> = {
  [TillSessionStatus.Open]: { 'en': 'Open', 'ja': '営業中', 'vi': 'Đang mở' },
  [TillSessionStatus.Closing]: { 'en': 'Closing', 'ja': '締め作業中', 'vi': 'Đang kết ca' },
  [TillSessionStatus.Settled]: { 'en': 'Settled', 'ja': '締め済み', 'vi': 'Đã kết ca' },
  [TillSessionStatus.Abandoned]: { 'en': 'Abandoned', 'ja': '取消', 'vi': 'Đã huỷ' },
  [TillSessionStatus.Expired]: { 'en': 'Expired', 'ja': '期限切れ', 'vi': 'Hết hạn' },
};

/** Get label for TillSessionStatus value with locale support */
export function getTillSessionStatusLabel(value: TillSessionStatus, locale?: string): string {
  const labels = tillSessionStatusLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for TillSessionStatus value */
export function getTillSessionStatusExtra(_value: TillSessionStatus): Record<string, unknown> | undefined {
  return undefined;
}
