<?php

namespace App\Omnify\Modules\MenuProductSku\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\MenuProduct;
use App\Models\ProductSku;
use App\Omnify\Modules\MenuProductSku\Locales\MenuProductSkuLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * MenuProductSkuBaseModel
 *
 * @property int $menu_product_id
 * @property int $product_sku_id
 * @property float $selling_price
 * @property bool $is_price_overridden
 * @property bool $is_active
 * @property string|null $disabled_reason
 * @property mixed|null $disabled_at
 * @property string|null $disabled_by_name
 */
class MenuProductSkuBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;
    use SoftDeletes;

    /**
     * The table associated with the model.
     */
    protected $table = 'menu_product_skus';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = MenuProductSkuLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = MenuProductSkuLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'menu_product_id',
        'product_sku_id',
        'selling_price',
        'is_price_overridden',
        'is_active',
        'disabled_reason',
        'disabled_at',
        'disabled_by_name',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'selling_price' => 'decimal:2',
            'is_price_overridden' => 'boolean',
            'is_active' => 'boolean',
            'disabled_at' => 'datetime',
        ];
    }

    /**
     * Get the menuProduct that owns this model.
     */
    public function menuProduct(): BelongsTo
    {
        return $this->belongsTo(MenuProduct::class, 'menu_product_id');
    }

    /**
     * Get the productSku that owns this model.
     */
    public function productSku(): BelongsTo
    {
        return $this->belongsTo(ProductSku::class, 'product_sku_id');
    }
}
