/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import { CustomerOrderPickupType } from '../enum/CustomerOrderPickupType';
import { CustomerOrderStatus } from '../enum/CustomerOrderStatus';
import { CustomerOrderType } from '../enum/CustomerOrderType';
import type { Branch } from './Branch';
import type { Brand } from './Brand';
import type { Coupon } from './Coupon';
import type { Customer } from './Customer';
import type { CustomerOrderItem } from './CustomerOrderItem';
import type { OrderPayment } from './OrderPayment';
import type { Organization } from './Organization';
import type { Table } from './Table';
import type { TillSession } from './TillSession';

/**
 * 注文
 */
export interface CustomerOrder {
  id: string;
  order_code: string;
  qr_token?: string | null;
  client_order_id?: string | null;
  order_type?: CustomerOrderType | null;
  pickup_type: CustomerOrderPickupType;
  scheduled_pickup_time?: DateTimeString | null;
  estimated_ready_time?: DateTimeString | null;
  actual_ready_time?: DateTimeString | null;
  preparation_minutes: number;
  status: CustomerOrderStatus;
  subtotal: number;
  discount_amount: number;
  coupon_code_snapshot?: string | null;
  service_charge: number;
  tax_amount: number;
  is_tax_included: boolean;
  tax_rounding_mode: string;
  tax_rounding_decimals?: number | null;
  total_amount: number;
  paid_amount: number;
  total_tip: number;
  stripe_payment_intent_id?: string | null;
  opened_at: DateTimeString;
  checkout_at?: DateTimeString | null;
  closed_at?: DateTimeString | null;
  voided_at?: DateTimeString | null;
  void_reason?: string | null;
  payment_due_at?: DateTimeString | null;
  payment_timeout_minutes?: number | null;
  auto_cancelled_at?: DateTimeString | null;
  guest_count?: number | null;
  split_people_count?: number | null;
  note?: string | null;
  stock_out_transaction_id?: string | null;
  created_by_id?: string | null;
  customer_takeaway_name?: string | null;
  customer_takeaway_phone?: string | null;
  customer_takeaway_email?: string | null;
  table_id?: string | null;
  table?: Table | null;
  customer_id?: string | null;
  customer?: Customer | null;
  coupon_id?: string | null;
  coupon?: Coupon | null;
  branch_id: string;
  branch?: Branch;
  brand_id: string;
  brand?: Brand;
  organization_id: string;
  organization?: Organization;
  tillSession_id?: string | null;
  tillSession?: TillSession | null;
  items?: CustomerOrderItem[];
  payments?: OrderPayment[];
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for CustomerOrder
 */
export const customerOrderI18n = {
  label: {"ja":"注文","en":"Customer Order","vi":"Đơn hàng"},
  fields: {
    order_code: {
      label: {"ja":"注文コード","en":"Order Code","vi":"Mã đơn hàng"},
      placeholder: {"ja":"注文コードを入力","en":"Enter Order Code","vi":"Nhập Mã đơn hàng"},
    },
    qr_token: {
      label: {"ja":"QRトークン","en":"QR Token","vi":"Token QR"},
      placeholder: {"ja":"QRトークンを入力","en":"Enter QR Token","vi":"Nhập Token QR"},
    },
    client_order_id: {
      label: {"ja":"クライアント注文ID","en":"Client Order ID","vi":"ID đơn (local)"},
      placeholder: {"ja":"クライアント注文IDを入力","en":"Enter Client Order ID","vi":"Nhập ID đơn (local)"},
    },
    order_type: {
      label: {"ja":"注文タイプ","en":"Order Type","vi":"Loại đơn hàng"},
      placeholder: {"ja":"注文タイプを入力","en":"Enter Order Type","vi":"Nhập Loại đơn hàng"},
    },
    pickup_type: {
      label: {"ja":"ピックアップタイプ","en":"Pickup Type","vi":"Loại nhận hàng"},
      placeholder: {"ja":"ピックアップタイプを入力","en":"Enter Pickup Type","vi":"Nhập Loại nhận hàng"},
    },
    scheduled_pickup_time: {
      label: {"ja":"予約受取時刻","en":"Scheduled Pickup Time","vi":"Giờ nhận hẹn"},
      placeholder: {"ja":"予約受取時刻を入力","en":"Enter Scheduled Pickup Time","vi":"Nhập Giờ nhận hẹn"},
    },
    estimated_ready_time: {
      label: {"ja":"完成予定時刻","en":"Estimated Ready Time","vi":"Dự kiến xong"},
      placeholder: {"ja":"完成予定時刻を入力","en":"Enter Estimated Ready Time","vi":"Nhập Dự kiến xong"},
    },
    actual_ready_time: {
      label: {"ja":"実際の完成時刻","en":"Actual Ready Time","vi":"Giờ xong thực tế"},
      placeholder: {"ja":"実際の完成時刻を入力","en":"Enter Actual Ready Time","vi":"Nhập Giờ xong thực tế"},
    },
    preparation_minutes: {
      label: {"ja":"調理時間（分）","en":"Preparation Minutes","vi":"Thời gian chuẩn bị (phút)"},
      placeholder: {"ja":"調理時間（分）を入力","en":"Enter Preparation Minutes","vi":"Nhập Thời gian chuẩn bị (phút)"},
    },
    status: {
      label: {"ja":"ステータス","en":"Status","vi":"Trạng thái"},
      placeholder: {"ja":"ステータスを入力","en":"Enter Status","vi":"Nhập Trạng thái"},
    },
    subtotal: {
      label: {"ja":"小計","en":"Subtotal","vi":"Tạm tính"},
      placeholder: {"ja":"小計を入力","en":"Enter Subtotal","vi":"Nhập Tạm tính"},
    },
    discount_amount: {
      label: {"ja":"割引額","en":"Discount Amount","vi":"Giảm giá"},
      placeholder: {"ja":"割引額を入力","en":"Enter Discount Amount","vi":"Nhập Giảm giá"},
    },
    coupon_code_snapshot: {
      label: {"ja":"クーポンコード（スナップショット）","en":"Coupon Code Snapshot","vi":"Mã coupon (snapshot)"},
      placeholder: {"ja":"クーポンコード（スナップショット）を入力","en":"Enter Coupon Code Snapshot","vi":"Nhập Mã coupon (snapshot)"},
    },
    service_charge: {
      label: {"ja":"サービス料","en":"Service Charge","vi":"Phí phục vụ"},
      placeholder: {"ja":"サービス料を入力","en":"Enter Service Charge","vi":"Nhập Phí phục vụ"},
    },
    tax_amount: {
      label: {"ja":"税額","en":"Tax Amount","vi":"Thuế"},
      placeholder: {"ja":"税額を入力","en":"Enter Tax Amount","vi":"Nhập Thuế"},
    },
    is_tax_included: {
      label: {"ja":"税込価格","en":"Prices Include Tax","vi":"Giá đã gồm thuế"},
      placeholder: {"ja":"税込価格を入力","en":"Enter Prices Include Tax","vi":"Nhập Giá đã gồm thuế"},
    },
    tax_rounding_mode: {
      label: {"ja":"消費税の端数処理","en":"Tax Rounding Mode","vi":"Cách làm tròn thuế"},
      placeholder: {"ja":"消費税の端数処理を入力","en":"Enter Tax Rounding Mode","vi":"Nhập Cách làm tròn thuế"},
    },
    tax_rounding_decimals: {
      label: {"ja":"消費税の小数点桁数","en":"Tax Rounding Decimals","vi":"Số thập phân làm tròn thuế"},
      placeholder: {"ja":"消費税の小数点桁数を入力","en":"Enter Tax Rounding Decimals","vi":"Nhập Số thập phân làm tròn thuế"},
    },
    total_amount: {
      label: {"ja":"合計金額","en":"Total Amount","vi":"Tổng tiền"},
      placeholder: {"ja":"合計金額を入力","en":"Enter Total Amount","vi":"Nhập Tổng tiền"},
    },
    paid_amount: {
      label: {"ja":"支払済金額","en":"Paid Amount","vi":"Đã thanh toán"},
      placeholder: {"ja":"支払済金額を入力","en":"Enter Paid Amount","vi":"Nhập Đã thanh toán"},
    },
    total_tip: {
      label: {"ja":"チップ合計","en":"Total Tip","vi":"Tổng tip"},
      placeholder: {"ja":"チップ合計を入力","en":"Enter Total Tip","vi":"Nhập Tổng tip"},
    },
    stripe_payment_intent_id: {
      label: {"ja":"Stripe 決済 ID","en":"Stripe Payment Intent","vi":"Mã Stripe PaymentIntent"},
      placeholder: {"ja":"Stripe 決済 IDを入力","en":"Enter Stripe Payment Intent","vi":"Nhập Mã Stripe PaymentIntent"},
    },
    opened_at: {
      label: {"ja":"受付日時","en":"Opened At","vi":"Thời điểm mở"},
      placeholder: {"ja":"受付日時を入力","en":"Enter Opened At","vi":"Nhập Thời điểm mở"},
    },
    checkout_at: {
      label: {"ja":"会計日時","en":"Checkout At","vi":"Thời điểm tính tiền"},
      placeholder: {"ja":"会計日時を入力","en":"Enter Checkout At","vi":"Nhập Thời điểm tính tiền"},
    },
    closed_at: {
      label: {"ja":"完了日時","en":"Closed At","vi":"Thời điểm đóng"},
      placeholder: {"ja":"完了日時を入力","en":"Enter Closed At","vi":"Nhập Thời điểm đóng"},
    },
    voided_at: {
      label: {"ja":"無効日時","en":"Voided At","vi":"Thời điểm hủy"},
      placeholder: {"ja":"無効日時を入力","en":"Enter Voided At","vi":"Nhập Thời điểm hủy"},
    },
    void_reason: {
      label: {"ja":"無効理由","en":"Void Reason","vi":"Lý do hủy"},
      placeholder: {"ja":"無効理由を入力","en":"Enter Void Reason","vi":"Nhập Lý do hủy"},
    },
    payment_due_at: {
      label: {"ja":"支払期限","en":"Payment Due At","vi":"Hạn thanh toán"},
      placeholder: {"ja":"支払期限を入力","en":"Enter Payment Due At","vi":"Nhập Hạn thanh toán"},
    },
    payment_timeout_minutes: {
      label: {"ja":"支払タイムアウト（分）","en":"Payment Timeout (Minutes)","vi":"Thời gian chờ thanh toán (phút)"},
      placeholder: {"ja":"支払タイムアウト（分）を入力","en":"Enter Payment Timeout (Minutes)","vi":"Nhập Thời gian chờ thanh toán (phút)"},
    },
    auto_cancelled_at: {
      label: {"ja":"自動キャンセル日時","en":"Auto Cancelled At","vi":"Thời điểm tự huỷ"},
      placeholder: {"ja":"自動キャンセル日時を入力","en":"Enter Auto Cancelled At","vi":"Nhập Thời điểm tự huỷ"},
    },
    guest_count: {
      label: {"ja":"来客数","en":"Guest Count","vi":"Số khách"},
      placeholder: {"ja":"来客数を入力","en":"Enter Guest Count","vi":"Nhập Số khách"},
    },
    split_people_count: {
      label: {"ja":"割り勘人数","en":"Split People Count","vi":"Số người chia hóa đơn"},
      placeholder: {"ja":"割り勘人数を入力","en":"Enter Split People Count","vi":"Nhập Số người chia hóa đơn"},
    },
    note: {
      label: {"ja":"備考","en":"Note","vi":"Ghi chú"},
      placeholder: {"ja":"備考を入力","en":"Enter Note","vi":"Nhập Ghi chú"},
    },
    stock_out_transaction_id: {
      label: {"ja":"出庫取引","en":"Stock Out Transaction","vi":"Phiếu xuất kho"},
      placeholder: {"ja":"出庫取引を入力","en":"Enter Stock Out Transaction","vi":"Nhập Phiếu xuất kho"},
    },
    created_by_id: {
      label: {"ja":"作成者","en":"Created By","vi":"Người tạo"},
      placeholder: {"ja":"作成者を入力","en":"Enter Created By","vi":"Nhập Người tạo"},
    },
    customer_takeaway_name: {
      label: {"ja":"テイクアウト顧客名","en":"Takeaway Customer Name","vi":"Tên khách mang về"},
      placeholder: {"ja":"テイクアウト顧客名を入力","en":"Enter Takeaway Customer Name","vi":"Nhập Tên khách mang về"},
    },
    customer_takeaway_phone: {
      label: {"ja":"テイクアウト顧客電話","en":"Takeaway Customer Phone","vi":"SĐT khách mang về"},
      placeholder: {"ja":"テイクアウト顧客電話を入力","en":"Enter Takeaway Customer Phone","vi":"Nhập SĐT khách mang về"},
    },
    customer_takeaway_email: {
      label: {"ja":"テイクアウト顧客メール","en":"Takeaway Customer Email","vi":"Email khách mang về"},
      placeholder: {"ja":"テイクアウト顧客メールを入力","en":"Enter Takeaway Customer Email","vi":"Nhập Email khách mang về"},
    },
    table: {
      label: {"ja":"テーブル","en":"Table","vi":"Bàn"},
      placeholder: {"ja":"テーブルを入力","en":"Enter Table","vi":"Nhập Bàn"},
    },
    customer: {
      label: {"ja":"顧客","en":"Customer","vi":"Khách hàng"},
      placeholder: {"ja":"顧客を入力","en":"Enter Customer","vi":"Nhập Khách hàng"},
    },
    coupon: {
      label: {"ja":"クーポン","en":"Coupon","vi":"Coupon"},
      placeholder: {"ja":"クーポンを入力","en":"Enter Coupon","vi":"Nhập Coupon"},
    },
    branch: {
      label: {"ja":"店舗","en":"Branch","vi":"Chi nhánh"},
      placeholder: {"ja":"店舗を入力","en":"Enter Branch","vi":"Nhập Chi nhánh"},
    },
    brand: {
      label: {"ja":"ブランド","en":"Brand","vi":"Thương hiệu"},
      placeholder: {"ja":"ブランドを入力","en":"Enter Brand","vi":"Nhập Thương hiệu"},
    },
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    till_session: {
      label: {"ja":"レジセッション","en":"Till Session","vi":"Ca thu ngân"},
      placeholder: {"ja":"レジセッションを入力","en":"Enter Till Session","vi":"Nhập Ca thu ngân"},
    },
    items: {
      label: {"ja":"注文明細","en":"Order Items","vi":"Chi tiết đơn hàng"},
      placeholder: {"ja":"注文明細を入力","en":"Enter Order Items","vi":"Nhập Chi tiết đơn hàng"},
    },
    payments: {
      label: {"ja":"支払い","en":"Payments","vi":"Thanh toán"},
      placeholder: {"ja":"支払いを入力","en":"Enter Payments","vi":"Nhập Thanh toán"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for CustomerOrder */
export const baseCustomerOrderSchemas = {
  order_code: z.string().min(1).max(50),
  qr_token: z.string().max(64).optional().nullable(),
  client_order_id: z.string().optional().nullable(),
  order_type: z.nativeEnum(CustomerOrderType).optional().nullable(),
  pickup_type: z.nativeEnum(CustomerOrderPickupType),
  scheduled_pickup_time: z.string().datetime({ offset: true }).optional().nullable(),
  estimated_ready_time: z.string().datetime({ offset: true }).optional().nullable(),
  actual_ready_time: z.string().datetime({ offset: true }).optional().nullable(),
  preparation_minutes: z.number().int(),
  status: z.nativeEnum(CustomerOrderStatus),
  subtotal: z.number(),
  discount_amount: z.number(),
  coupon_code_snapshot: z.string().max(50).optional().nullable(),
  service_charge: z.number(),
  tax_amount: z.number(),
  is_tax_included: z.boolean(),
  tax_rounding_mode: z.string().min(1).max(20),
  tax_rounding_decimals: z.number().int().optional().nullable(),
  total_amount: z.number(),
  paid_amount: z.number(),
  total_tip: z.number(),
  stripe_payment_intent_id: z.string().max(255).optional().nullable(),
  opened_at: z.string().datetime({ offset: true }),
  checkout_at: z.string().datetime({ offset: true }).optional().nullable(),
  closed_at: z.string().datetime({ offset: true }).optional().nullable(),
  voided_at: z.string().datetime({ offset: true }).optional().nullable(),
  void_reason: z.string().max(500).optional().nullable(),
  payment_due_at: z.string().datetime({ offset: true }).optional().nullable(),
  payment_timeout_minutes: z.number().int().optional().nullable(),
  auto_cancelled_at: z.string().datetime({ offset: true }).optional().nullable(),
  guest_count: z.number().int().optional().nullable(),
  split_people_count: z.number().int().optional().nullable(),
  note: z.string().optional().nullable(),
  stock_out_transaction_id: z.string().optional().nullable(),
  created_by_id: z.string().optional().nullable(),
  customer_takeaway_name: z.string().max(255).optional().nullable(),
  customer_takeaway_phone: z.string().max(50).optional().nullable(),
  customer_takeaway_email: z.string().max(255).optional().nullable(),
} as const;

/** Create schema for CustomerOrder */
export const baseCustomerOrderCreateSchema = z.object({
  order_code: baseCustomerOrderSchemas.order_code,
  qr_token: baseCustomerOrderSchemas.qr_token,
  client_order_id: baseCustomerOrderSchemas.client_order_id,
  order_type: baseCustomerOrderSchemas.order_type,
  pickup_type: baseCustomerOrderSchemas.pickup_type,
  scheduled_pickup_time: baseCustomerOrderSchemas.scheduled_pickup_time,
  estimated_ready_time: baseCustomerOrderSchemas.estimated_ready_time,
  actual_ready_time: baseCustomerOrderSchemas.actual_ready_time,
  preparation_minutes: baseCustomerOrderSchemas.preparation_minutes,
  status: baseCustomerOrderSchemas.status,
  subtotal: baseCustomerOrderSchemas.subtotal,
  discount_amount: baseCustomerOrderSchemas.discount_amount,
  coupon_code_snapshot: baseCustomerOrderSchemas.coupon_code_snapshot,
  service_charge: baseCustomerOrderSchemas.service_charge,
  tax_amount: baseCustomerOrderSchemas.tax_amount,
  is_tax_included: baseCustomerOrderSchemas.is_tax_included,
  tax_rounding_mode: baseCustomerOrderSchemas.tax_rounding_mode,
  tax_rounding_decimals: baseCustomerOrderSchemas.tax_rounding_decimals,
  total_amount: baseCustomerOrderSchemas.total_amount,
  paid_amount: baseCustomerOrderSchemas.paid_amount,
  total_tip: baseCustomerOrderSchemas.total_tip,
  stripe_payment_intent_id: baseCustomerOrderSchemas.stripe_payment_intent_id,
  opened_at: baseCustomerOrderSchemas.opened_at,
  checkout_at: baseCustomerOrderSchemas.checkout_at,
  closed_at: baseCustomerOrderSchemas.closed_at,
  voided_at: baseCustomerOrderSchemas.voided_at,
  void_reason: baseCustomerOrderSchemas.void_reason,
  payment_due_at: baseCustomerOrderSchemas.payment_due_at,
  payment_timeout_minutes: baseCustomerOrderSchemas.payment_timeout_minutes,
  auto_cancelled_at: baseCustomerOrderSchemas.auto_cancelled_at,
  guest_count: baseCustomerOrderSchemas.guest_count,
  split_people_count: baseCustomerOrderSchemas.split_people_count,
  note: baseCustomerOrderSchemas.note,
  stock_out_transaction_id: baseCustomerOrderSchemas.stock_out_transaction_id,
  created_by_id: baseCustomerOrderSchemas.created_by_id,
  customer_takeaway_name: baseCustomerOrderSchemas.customer_takeaway_name,
  customer_takeaway_phone: baseCustomerOrderSchemas.customer_takeaway_phone,
  customer_takeaway_email: baseCustomerOrderSchemas.customer_takeaway_email,
});

/** Update schema for CustomerOrder */
export const baseCustomerOrderUpdateSchema = baseCustomerOrderCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseCustomerOrderCreate = z.infer<typeof baseCustomerOrderCreateSchema>;
export type BaseCustomerOrderUpdate = z.infer<typeof baseCustomerOrderUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getCustomerOrderLabel(locale: string): string {
  return customerOrderI18n.label[locale as keyof typeof customerOrderI18n.label] ?? customerOrderI18n.label['en'] ?? 'CustomerOrder';
}

/** Get field label for a specific locale */
export function getCustomerOrderFieldLabel(field: string, locale: string): string {
  const fields = customerOrderI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getCustomerOrderFieldPlaceholder(field: string, locale: string): string {
  const fields = customerOrderI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for CustomerOrder.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const customerOrderMetadata = {
  modelName: "CustomerOrder",
  table: "customer_orders",

  fields: {
    order_code: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "注文コード",
        en: "Order Code",
        vi: "Mã đơn hàng",
      },
      placeholder: {
        ja: "注文コードを入力",
        en: "Enter Order Code",
        vi: "Nhập Mã đơn hàng",
      },
    },
    qr_token: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 64,
      },
      label: {
        ja: "QRトークン",
        en: "QR Token",
        vi: "Token QR",
      },
      placeholder: {
        ja: "QRトークンを入力",
        en: "Enter QR Token",
        vi: "Nhập Token QR",
      },
    },
    client_order_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "クライアント注文ID",
        en: "Client Order ID",
        vi: "ID đơn (local)",
      },
      placeholder: {
        ja: "クライアント注文IDを入力",
        en: "Enter Client Order ID",
        vi: "Nhập ID đơn (local)",
      },
    },
    order_type: {
      type: "enum",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      enum: "CustomerOrderType",
      enumValues: ["spot", "dine_in", "takeaway"] as const,
      label: {
        ja: "注文タイプ",
        en: "Order Type",
        vi: "Loại đơn hàng",
      },
      placeholder: {
        ja: "注文タイプを入力",
        en: "Enter Order Type",
        vi: "Nhập Loại đơn hàng",
      },
    },
    pickup_type: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "CustomerOrderPickupType",
      enumValues: ["immediate", "scheduled"] as const,
      label: {
        ja: "ピックアップタイプ",
        en: "Pickup Type",
        vi: "Loại nhận hàng",
      },
      placeholder: {
        ja: "ピックアップタイプを入力",
        en: "Enter Pickup Type",
        vi: "Nhập Loại nhận hàng",
      },
    },
    scheduled_pickup_time: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "予約受取時刻",
        en: "Scheduled Pickup Time",
        vi: "Giờ nhận hẹn",
      },
      placeholder: {
        ja: "予約受取時刻を入力",
        en: "Enter Scheduled Pickup Time",
        vi: "Nhập Giờ nhận hẹn",
      },
    },
    estimated_ready_time: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "完成予定時刻",
        en: "Estimated Ready Time",
        vi: "Dự kiến xong",
      },
      placeholder: {
        ja: "完成予定時刻を入力",
        en: "Enter Estimated Ready Time",
        vi: "Nhập Dự kiến xong",
      },
    },
    actual_ready_time: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "実際の完成時刻",
        en: "Actual Ready Time",
        vi: "Giờ xong thực tế",
      },
      placeholder: {
        ja: "実際の完成時刻を入力",
        en: "Enter Actual Ready Time",
        vi: "Nhập Giờ xong thực tế",
      },
    },
    preparation_minutes: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "調理時間（分）",
        en: "Preparation Minutes",
        vi: "Thời gian chuẩn bị (phút)",
      },
      placeholder: {
        ja: "調理時間（分）を入力",
        en: "Enter Preparation Minutes",
        vi: "Nhập Thời gian chuẩn bị (phút)",
      },
    },
    status: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "CustomerOrderStatus",
      enumValues: ["pending", "awaiting_confirmation", "confirmed", "open", "dining", "checkout", "paying", "closed", "voided", "expired"] as const,
      label: {
        ja: "ステータス",
        en: "Status",
        vi: "Trạng thái",
      },
      placeholder: {
        ja: "ステータスを入力",
        en: "Enter Status",
        vi: "Nhập Trạng thái",
      },
    },
    subtotal: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "小計",
        en: "Subtotal",
        vi: "Tạm tính",
      },
      placeholder: {
        ja: "小計を入力",
        en: "Enter Subtotal",
        vi: "Nhập Tạm tính",
      },
    },
    discount_amount: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "割引額",
        en: "Discount Amount",
        vi: "Giảm giá",
      },
      placeholder: {
        ja: "割引額を入力",
        en: "Enter Discount Amount",
        vi: "Nhập Giảm giá",
      },
    },
    coupon_code_snapshot: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "クーポンコード（スナップショット）",
        en: "Coupon Code Snapshot",
        vi: "Mã coupon (snapshot)",
      },
      placeholder: {
        ja: "クーポンコード（スナップショット）を入力",
        en: "Enter Coupon Code Snapshot",
        vi: "Nhập Mã coupon (snapshot)",
      },
    },
    service_charge: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "サービス料",
        en: "Service Charge",
        vi: "Phí phục vụ",
      },
      placeholder: {
        ja: "サービス料を入力",
        en: "Enter Service Charge",
        vi: "Nhập Phí phục vụ",
      },
    },
    tax_amount: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "税額",
        en: "Tax Amount",
        vi: "Thuế",
      },
      placeholder: {
        ja: "税額を入力",
        en: "Enter Tax Amount",
        vi: "Nhập Thuế",
      },
    },
    is_tax_included: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "税込価格",
        en: "Prices Include Tax",
        vi: "Giá đã gồm thuế",
      },
      placeholder: {
        ja: "税込価格を入力",
        en: "Enter Prices Include Tax",
        vi: "Nhập Giá đã gồm thuế",
      },
    },
    tax_rounding_mode: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 20,
      },
      label: {
        ja: "消費税の端数処理",
        en: "Tax Rounding Mode",
        vi: "Cách làm tròn thuế",
      },
      placeholder: {
        ja: "消費税の端数処理を入力",
        en: "Enter Tax Rounding Mode",
        vi: "Nhập Cách làm tròn thuế",
      },
    },
    tax_rounding_decimals: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "消費税の小数点桁数",
        en: "Tax Rounding Decimals",
        vi: "Số thập phân làm tròn thuế",
      },
      placeholder: {
        ja: "消費税の小数点桁数を入力",
        en: "Enter Tax Rounding Decimals",
        vi: "Nhập Số thập phân làm tròn thuế",
      },
    },
    total_amount: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "合計金額",
        en: "Total Amount",
        vi: "Tổng tiền",
      },
      placeholder: {
        ja: "合計金額を入力",
        en: "Enter Total Amount",
        vi: "Nhập Tổng tiền",
      },
    },
    paid_amount: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "支払済金額",
        en: "Paid Amount",
        vi: "Đã thanh toán",
      },
      placeholder: {
        ja: "支払済金額を入力",
        en: "Enter Paid Amount",
        vi: "Nhập Đã thanh toán",
      },
    },
    total_tip: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "チップ合計",
        en: "Total Tip",
        vi: "Tổng tip",
      },
      placeholder: {
        ja: "チップ合計を入力",
        en: "Enter Total Tip",
        vi: "Nhập Tổng tip",
      },
    },
    stripe_payment_intent_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "Stripe 決済 ID",
        en: "Stripe Payment Intent",
        vi: "Mã Stripe PaymentIntent",
      },
      placeholder: {
        ja: "Stripe 決済 IDを入力",
        en: "Enter Stripe Payment Intent",
        vi: "Nhập Mã Stripe PaymentIntent",
      },
    },
    opened_at: {
      type: "datetime",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "受付日時",
        en: "Opened At",
        vi: "Thời điểm mở",
      },
      placeholder: {
        ja: "受付日時を入力",
        en: "Enter Opened At",
        vi: "Nhập Thời điểm mở",
      },
    },
    checkout_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "会計日時",
        en: "Checkout At",
        vi: "Thời điểm tính tiền",
      },
      placeholder: {
        ja: "会計日時を入力",
        en: "Enter Checkout At",
        vi: "Nhập Thời điểm tính tiền",
      },
    },
    closed_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "完了日時",
        en: "Closed At",
        vi: "Thời điểm đóng",
      },
      placeholder: {
        ja: "完了日時を入力",
        en: "Enter Closed At",
        vi: "Nhập Thời điểm đóng",
      },
    },
    voided_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "無効日時",
        en: "Voided At",
        vi: "Thời điểm hủy",
      },
      placeholder: {
        ja: "無効日時を入力",
        en: "Enter Voided At",
        vi: "Nhập Thời điểm hủy",
      },
    },
    void_reason: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 500,
      },
      label: {
        ja: "無効理由",
        en: "Void Reason",
        vi: "Lý do hủy",
      },
      placeholder: {
        ja: "無効理由を入力",
        en: "Enter Void Reason",
        vi: "Nhập Lý do hủy",
      },
    },
    payment_due_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "支払期限",
        en: "Payment Due At",
        vi: "Hạn thanh toán",
      },
      placeholder: {
        ja: "支払期限を入力",
        en: "Enter Payment Due At",
        vi: "Nhập Hạn thanh toán",
      },
    },
    payment_timeout_minutes: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "支払タイムアウト（分）",
        en: "Payment Timeout (Minutes)",
        vi: "Thời gian chờ thanh toán (phút)",
      },
      placeholder: {
        ja: "支払タイムアウト（分）を入力",
        en: "Enter Payment Timeout (Minutes)",
        vi: "Nhập Thời gian chờ thanh toán (phút)",
      },
    },
    auto_cancelled_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "自動キャンセル日時",
        en: "Auto Cancelled At",
        vi: "Thời điểm tự huỷ",
      },
      placeholder: {
        ja: "自動キャンセル日時を入力",
        en: "Enter Auto Cancelled At",
        vi: "Nhập Thời điểm tự huỷ",
      },
    },
    guest_count: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "来客数",
        en: "Guest Count",
        vi: "Số khách",
      },
      placeholder: {
        ja: "来客数を入力",
        en: "Enter Guest Count",
        vi: "Nhập Số khách",
      },
    },
    split_people_count: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "割り勘人数",
        en: "Split People Count",
        vi: "Số người chia hóa đơn",
      },
      placeholder: {
        ja: "割り勘人数を入力",
        en: "Enter Split People Count",
        vi: "Nhập Số người chia hóa đơn",
      },
    },
    note: {
      type: "text",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "備考",
        en: "Note",
        vi: "Ghi chú",
      },
      placeholder: {
        ja: "備考を入力",
        en: "Enter Note",
        vi: "Nhập Ghi chú",
      },
    },
    stock_out_transaction_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "出庫取引",
        en: "Stock Out Transaction",
        vi: "Phiếu xuất kho",
      },
      placeholder: {
        ja: "出庫取引を入力",
        en: "Enter Stock Out Transaction",
        vi: "Nhập Phiếu xuất kho",
      },
    },
    created_by_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "作成者",
        en: "Created By",
        vi: "Người tạo",
      },
      placeholder: {
        ja: "作成者を入力",
        en: "Enter Created By",
        vi: "Nhập Người tạo",
      },
    },
    customer_takeaway_name: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "テイクアウト顧客名",
        en: "Takeaway Customer Name",
        vi: "Tên khách mang về",
      },
      placeholder: {
        ja: "テイクアウト顧客名を入力",
        en: "Enter Takeaway Customer Name",
        vi: "Nhập Tên khách mang về",
      },
    },
    customer_takeaway_phone: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "テイクアウト顧客電話",
        en: "Takeaway Customer Phone",
        vi: "SĐT khách mang về",
      },
      placeholder: {
        ja: "テイクアウト顧客電話を入力",
        en: "Enter Takeaway Customer Phone",
        vi: "Nhập SĐT khách mang về",
      },
    },
    customer_takeaway_email: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "テイクアウト顧客メール",
        en: "Takeaway Customer Email",
        vi: "Email khách mang về",
      },
      placeholder: {
        ja: "テイクアウト顧客メールを入力",
        en: "Enter Takeaway Customer Email",
        vi: "Nhập Email khách mang về",
      },
    },
    table_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Table",
        table: "tables",
        onDelete: "SET NULL",
      },
      label: {},
    },
    customer_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Customer",
        table: "customers",
        onDelete: "SET NULL",
      },
      label: {},
    },
    coupon_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Coupon",
        table: "coupons",
        onDelete: "SET NULL",
      },
      label: {},
    },
    branch_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Branch",
        table: "branches",
        onDelete: "CASCADE",
      },
      label: {},
    },
    brand_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Brand",
        table: "brands",
        onDelete: "CASCADE",
      },
      label: {},
    },
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    till_session_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "TillSession",
        table: "till_sessions",
        onDelete: "SET NULL",
      },
      label: {},
    },
  },

  translatableFields: [] as const,
  requiredFields: ["order_code", "pickup_type", "preparation_minutes", "status", "subtotal", "discount_amount", "service_charge", "tax_amount", "is_tax_included", "tax_rounding_mode", "total_amount", "paid_amount", "total_tip", "opened_at", "branch_id", "brand_id", "organization_id"] as const,
  enumFields: ["order_type", "pickup_type", "status"] as const,
  relationFields: ["table_id", "customer_id", "coupon_id", "branch_id", "brand_id", "organization_id", "till_session_id"] as const,
} as const;

export type CustomerOrderFieldName = keyof typeof customerOrderMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a CustomerOrder. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface CustomerOrderCreateFormState {
  order_code: string;
  qr_token?: string | null;
  client_order_id?: string | null;
  order_type?: CustomerOrderType | null;
  pickup_type: CustomerOrderPickupType;
  scheduled_pickup_time?: string | null;
  estimated_ready_time?: string | null;
  actual_ready_time?: string | null;
  preparation_minutes: number;
  status: CustomerOrderStatus;
  subtotal: number;
  discount_amount: number;
  coupon_code_snapshot?: string | null;
  service_charge: number;
  tax_amount: number;
  is_tax_included: boolean;
  tax_rounding_mode: string;
  tax_rounding_decimals?: number | null;
  total_amount: number;
  paid_amount: number;
  total_tip: number;
  stripe_payment_intent_id?: string | null;
  opened_at: string;
  checkout_at?: string | null;
  closed_at?: string | null;
  voided_at?: string | null;
  void_reason?: string | null;
  payment_due_at?: string | null;
  payment_timeout_minutes?: number | null;
  auto_cancelled_at?: string | null;
  guest_count?: number | null;
  split_people_count?: number | null;
  note?: string | null;
  stock_out_transaction_id?: string | null;
  created_by_id?: string | null;
  customer_takeaway_name?: string | null;
  customer_takeaway_phone?: string | null;
  customer_takeaway_email?: string | null;
  table_id?: string | null;
  customer_id?: string | null;
  coupon_id?: string | null;
  branch_id: string;
  brand_id: string;
  organization_id: string;
  till_session_id?: string | null;
}

/** Form-state shape for updating a CustomerOrder. Every field optional. */
export interface CustomerOrderUpdateFormState {
  order_code?: string;
  qr_token?: string | null;
  client_order_id?: string | null;
  order_type?: CustomerOrderType | null;
  pickup_type?: CustomerOrderPickupType;
  scheduled_pickup_time?: string | null;
  estimated_ready_time?: string | null;
  actual_ready_time?: string | null;
  preparation_minutes?: number;
  status?: CustomerOrderStatus;
  subtotal?: number;
  discount_amount?: number;
  coupon_code_snapshot?: string | null;
  service_charge?: number;
  tax_amount?: number;
  is_tax_included?: boolean;
  tax_rounding_mode?: string;
  tax_rounding_decimals?: number | null;
  total_amount?: number;
  paid_amount?: number;
  total_tip?: number;
  stripe_payment_intent_id?: string | null;
  opened_at?: string;
  checkout_at?: string | null;
  closed_at?: string | null;
  voided_at?: string | null;
  void_reason?: string | null;
  payment_due_at?: string | null;
  payment_timeout_minutes?: number | null;
  auto_cancelled_at?: string | null;
  guest_count?: number | null;
  split_people_count?: number | null;
  note?: string | null;
  stock_out_transaction_id?: string | null;
  created_by_id?: string | null;
  customer_takeaway_name?: string | null;
  customer_takeaway_phone?: string | null;
  customer_takeaway_email?: string | null;
  table_id?: string | null;
  customer_id?: string | null;
  coupon_id?: string | null;
  branch_id?: string;
  brand_id?: string;
  organization_id?: string;
  till_session_id?: string | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyCustomerOrderCreateForm(): CustomerOrderCreateFormState {
  return {
    order_code: '',
    qr_token: '',
    client_order_id: '',
    pickup_type: CustomerOrderPickupType.Immediate,
    scheduled_pickup_time: '',
    estimated_ready_time: '',
    actual_ready_time: '',
    preparation_minutes: 15,
    status: CustomerOrderStatus.Open,
    subtotal: 0,
    discount_amount: 0,
    coupon_code_snapshot: '',
    service_charge: 0,
    tax_amount: 0,
    is_tax_included: false,
    tax_rounding_mode: "round",
    tax_rounding_decimals: 0,
    total_amount: 0,
    paid_amount: 0,
    total_tip: 0,
    stripe_payment_intent_id: '',
    opened_at: '',
    checkout_at: '',
    closed_at: '',
    voided_at: '',
    void_reason: '',
    payment_due_at: '',
    payment_timeout_minutes: 0,
    auto_cancelled_at: '',
    guest_count: 0,
    split_people_count: 0,
    note: '',
    stock_out_transaction_id: '',
    created_by_id: '',
    customer_takeaway_name: '',
    customer_takeaway_phone: '',
    customer_takeaway_email: '',
    table_id: '',
    customer_id: '',
    coupon_id: '',
    branch_id: '',
    brand_id: '',
    organization_id: '',
    till_session_id: '',
  };
}

/** Convert create form state into the payload that baseCustomerOrderCreateSchema accepts. */
export function buildCustomerOrderCreatePayload(form: CustomerOrderCreateFormState): BaseCustomerOrderCreate {
  const payload: Record<string, unknown> = {
    order_code: form.order_code.trim(),
    qr_token: form.qr_token?.toString().trim() || null,
    client_order_id: form.client_order_id?.toString().trim() || null,
    order_type: form.order_type,
    pickup_type: form.pickup_type,
    scheduled_pickup_time: form.scheduled_pickup_time,
    estimated_ready_time: form.estimated_ready_time,
    actual_ready_time: form.actual_ready_time,
    preparation_minutes: form.preparation_minutes,
    status: form.status,
    subtotal: form.subtotal,
    discount_amount: form.discount_amount,
    coupon_code_snapshot: form.coupon_code_snapshot?.toString().trim() || null,
    service_charge: form.service_charge,
    tax_amount: form.tax_amount,
    is_tax_included: form.is_tax_included,
    tax_rounding_mode: form.tax_rounding_mode.trim(),
    tax_rounding_decimals: form.tax_rounding_decimals,
    total_amount: form.total_amount,
    paid_amount: form.paid_amount,
    total_tip: form.total_tip,
    stripe_payment_intent_id: form.stripe_payment_intent_id?.toString().trim() || null,
    opened_at: form.opened_at,
    checkout_at: form.checkout_at,
    closed_at: form.closed_at,
    voided_at: form.voided_at,
    void_reason: form.void_reason?.toString().trim() || null,
    payment_due_at: form.payment_due_at,
    payment_timeout_minutes: form.payment_timeout_minutes,
    auto_cancelled_at: form.auto_cancelled_at,
    guest_count: form.guest_count,
    split_people_count: form.split_people_count,
    note: form.note?.toString().trim() || null,
    stock_out_transaction_id: form.stock_out_transaction_id?.toString().trim() || null,
    created_by_id: form.created_by_id?.toString().trim() || null,
    customer_takeaway_name: form.customer_takeaway_name?.toString().trim() || null,
    customer_takeaway_phone: form.customer_takeaway_phone?.toString().trim() || null,
    customer_takeaway_email: form.customer_takeaway_email?.toString().trim() || null,
    table_id: form.table_id?.toString().trim() || null,
    customer_id: form.customer_id?.toString().trim() || null,
    coupon_id: form.coupon_id?.toString().trim() || null,
    branch_id: form.branch_id.trim(),
    brand_id: form.brand_id.trim(),
    organization_id: form.organization_id.trim(),
    till_session_id: form.till_session_id?.toString().trim() || null,
  };

  return payload as BaseCustomerOrderCreate;
}

/** Convert update form state into the payload that baseCustomerOrderUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildCustomerOrderUpdatePayload(form: CustomerOrderUpdateFormState): BaseCustomerOrderUpdate {
  const payload: Record<string, unknown> = {};
  if (form.order_code !== undefined) {
    payload.order_code = form.order_code?.toString().trim() ?? null;
  }
  if (form.qr_token !== undefined) {
    payload.qr_token = form.qr_token?.toString().trim() ?? null;
  }
  if (form.client_order_id !== undefined) {
    payload.client_order_id = form.client_order_id?.toString().trim() ?? null;
  }
  if (form.order_type !== undefined) {
    payload.order_type = form.order_type;
  }
  if (form.pickup_type !== undefined) {
    payload.pickup_type = form.pickup_type;
  }
  if (form.scheduled_pickup_time !== undefined) {
    payload.scheduled_pickup_time = form.scheduled_pickup_time;
  }
  if (form.estimated_ready_time !== undefined) {
    payload.estimated_ready_time = form.estimated_ready_time;
  }
  if (form.actual_ready_time !== undefined) {
    payload.actual_ready_time = form.actual_ready_time;
  }
  if (form.preparation_minutes !== undefined) {
    payload.preparation_minutes = form.preparation_minutes;
  }
  if (form.status !== undefined) {
    payload.status = form.status;
  }
  if (form.subtotal !== undefined) {
    payload.subtotal = form.subtotal;
  }
  if (form.discount_amount !== undefined) {
    payload.discount_amount = form.discount_amount;
  }
  if (form.coupon_code_snapshot !== undefined) {
    payload.coupon_code_snapshot = form.coupon_code_snapshot?.toString().trim() ?? null;
  }
  if (form.service_charge !== undefined) {
    payload.service_charge = form.service_charge;
  }
  if (form.tax_amount !== undefined) {
    payload.tax_amount = form.tax_amount;
  }
  if (form.is_tax_included !== undefined) {
    payload.is_tax_included = form.is_tax_included;
  }
  if (form.tax_rounding_mode !== undefined) {
    payload.tax_rounding_mode = form.tax_rounding_mode?.toString().trim() ?? null;
  }
  if (form.tax_rounding_decimals !== undefined) {
    payload.tax_rounding_decimals = form.tax_rounding_decimals;
  }
  if (form.total_amount !== undefined) {
    payload.total_amount = form.total_amount;
  }
  if (form.paid_amount !== undefined) {
    payload.paid_amount = form.paid_amount;
  }
  if (form.total_tip !== undefined) {
    payload.total_tip = form.total_tip;
  }
  if (form.stripe_payment_intent_id !== undefined) {
    payload.stripe_payment_intent_id = form.stripe_payment_intent_id?.toString().trim() ?? null;
  }
  if (form.opened_at !== undefined) {
    payload.opened_at = form.opened_at;
  }
  if (form.checkout_at !== undefined) {
    payload.checkout_at = form.checkout_at;
  }
  if (form.closed_at !== undefined) {
    payload.closed_at = form.closed_at;
  }
  if (form.voided_at !== undefined) {
    payload.voided_at = form.voided_at;
  }
  if (form.void_reason !== undefined) {
    payload.void_reason = form.void_reason?.toString().trim() ?? null;
  }
  if (form.payment_due_at !== undefined) {
    payload.payment_due_at = form.payment_due_at;
  }
  if (form.payment_timeout_minutes !== undefined) {
    payload.payment_timeout_minutes = form.payment_timeout_minutes;
  }
  if (form.auto_cancelled_at !== undefined) {
    payload.auto_cancelled_at = form.auto_cancelled_at;
  }
  if (form.guest_count !== undefined) {
    payload.guest_count = form.guest_count;
  }
  if (form.split_people_count !== undefined) {
    payload.split_people_count = form.split_people_count;
  }
  if (form.note !== undefined) {
    payload.note = form.note?.toString().trim() ?? null;
  }
  if (form.stock_out_transaction_id !== undefined) {
    payload.stock_out_transaction_id = form.stock_out_transaction_id?.toString().trim() ?? null;
  }
  if (form.created_by_id !== undefined) {
    payload.created_by_id = form.created_by_id?.toString().trim() ?? null;
  }
  if (form.customer_takeaway_name !== undefined) {
    payload.customer_takeaway_name = form.customer_takeaway_name?.toString().trim() ?? null;
  }
  if (form.customer_takeaway_phone !== undefined) {
    payload.customer_takeaway_phone = form.customer_takeaway_phone?.toString().trim() ?? null;
  }
  if (form.customer_takeaway_email !== undefined) {
    payload.customer_takeaway_email = form.customer_takeaway_email?.toString().trim() ?? null;
  }
  if (form.table_id !== undefined) {
    payload.table_id = form.table_id?.toString().trim() ?? null;
  }
  if (form.customer_id !== undefined) {
    payload.customer_id = form.customer_id?.toString().trim() ?? null;
  }
  if (form.coupon_id !== undefined) {
    payload.coupon_id = form.coupon_id?.toString().trim() ?? null;
  }
  if (form.branch_id !== undefined) {
    payload.branch_id = form.branch_id?.toString().trim() ?? null;
  }
  if (form.brand_id !== undefined) {
    payload.brand_id = form.brand_id?.toString().trim() ?? null;
  }
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.till_session_id !== undefined) {
    payload.till_session_id = form.till_session_id?.toString().trim() ?? null;
  }
  return payload as BaseCustomerOrderUpdate;
}
