/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import { DisposalReason } from '../enum/DisposalReason';
import type { StockTransactionItem } from './StockTransactionItem';

/**
 * 廃棄記録
 */
export interface DisposalRecord {
  id: string;
  stockTransactionItem_id: string;
  stockTransactionItem?: StockTransactionItem;
  disposal_reason: DisposalReason;
  cost_at_disposal: number;
  note?: string | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for DisposalRecord
 */
export const disposalRecordI18n = {
  label: {"ja":"廃棄記録","en":"Disposal Record","vi":"Chi tiết hủy"},
  fields: {
    stock_transaction_item: {
      label: {"ja":"在庫取引明細","en":"Stock Transaction Item","vi":"Chi tiết phiếu kho"},
      placeholder: {"ja":"在庫取引明細を入力","en":"Enter Stock Transaction Item","vi":"Nhập Chi tiết phiếu kho"},
    },
    disposal_reason: {
      label: {"ja":"廃棄理由","en":"Disposal Reason","vi":"Lý do hủy"},
      placeholder: {"ja":"廃棄理由を入力","en":"Enter Disposal Reason","vi":"Nhập Lý do hủy"},
    },
    cost_at_disposal: {
      label: {"ja":"廃棄時原価","en":"Cost at Disposal","vi":"Giá vốn lúc hủy"},
      placeholder: {"ja":"廃棄時原価を入力","en":"Enter Cost at Disposal","vi":"Nhập Giá vốn lúc hủy"},
    },
    note: {
      label: {"ja":"備考","en":"Note","vi":"Ghi chú"},
      placeholder: {"ja":"備考を入力","en":"Enter Note","vi":"Nhập Ghi chú"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for DisposalRecord */
export const baseDisposalRecordSchemas = {
  disposal_reason: z.nativeEnum(DisposalReason),
  cost_at_disposal: z.number(),
  note: z.string().optional().nullable(),
} as const;

/** Create schema for DisposalRecord */
export const baseDisposalRecordCreateSchema = z.object({
  disposal_reason: baseDisposalRecordSchemas.disposal_reason,
  cost_at_disposal: baseDisposalRecordSchemas.cost_at_disposal,
  note: baseDisposalRecordSchemas.note,
});

/** Update schema for DisposalRecord */
export const baseDisposalRecordUpdateSchema = baseDisposalRecordCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseDisposalRecordCreate = z.infer<typeof baseDisposalRecordCreateSchema>;
export type BaseDisposalRecordUpdate = z.infer<typeof baseDisposalRecordUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getDisposalRecordLabel(locale: string): string {
  return disposalRecordI18n.label[locale as keyof typeof disposalRecordI18n.label] ?? disposalRecordI18n.label['en'] ?? 'DisposalRecord';
}

/** Get field label for a specific locale */
export function getDisposalRecordFieldLabel(field: string, locale: string): string {
  const fields = disposalRecordI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getDisposalRecordFieldPlaceholder(field: string, locale: string): string {
  const fields = disposalRecordI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for DisposalRecord.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const disposalRecordMetadata = {
  modelName: "DisposalRecord",
  table: "disposal_records",

  fields: {
    stock_transaction_item_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "StockTransactionItem",
        table: "stock_transaction_items",
        onDelete: "CASCADE",
      },
      label: {},
    },
    disposal_reason: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enum: "DisposalReason",
      enumValues: ["expired", "overproduction", "damaged", "quality", "contaminated", "other"] as const,
      label: {
        ja: "廃棄理由",
        en: "Disposal Reason",
        vi: "Lý do hủy",
      },
      placeholder: {
        ja: "廃棄理由を入力",
        en: "Enter Disposal Reason",
        vi: "Nhập Lý do hủy",
      },
      description: {
        ja: "品目が廃棄される理由を分類する固定enum。BR-05: ユーザーはカスタム理由を追加できない。",
        en: "Fixed enum classifying why the item is being disposed. BR-05: users cannot add custom reasons.",
        vi: "Enum cố định phân loại lý do hủy. BR-05: user không được thêm lý do tùy chỉnh.",
      },
    },
    cost_at_disposal: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "廃棄時原価",
        en: "Cost at Disposal",
        vi: "Giá vốn lúc hủy",
      },
      placeholder: {
        ja: "廃棄時原価を入力",
        en: "Enter Cost at Disposal",
        vi: "Nhập Giá vốn lúc hủy",
      },
      description: {
        ja: "廃棄作成時のcost_price（バリエーション）またはcalculated_cost（材料）のスナップショット。BR-04。",
        en: "Snapshot of cost_price (variant) or calculated_cost (material) at disposal creation time. BR-04.",
        vi: "Snapshot giá vốn tại thời điểm tạo phiếu hủy. BR-04.",
      },
    },
    note: {
      type: "text",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "備考",
        en: "Note",
        vi: "Ghi chú",
      },
      placeholder: {
        ja: "備考を入力",
        en: "Enter Note",
        vi: "Nhập Ghi chú",
      },
      description: {
        ja: "任意の備考。disposal_reason=otherの場合は必須（BR-02）。アプリレベルのバリデーション。",
        en: "Optional note. Required when disposal_reason=other (BR-02). App-level validation.",
        vi: "Ghi chú tùy chọn. Bắt buộc khi disposal_reason=other (BR-02). Validate ở app.",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["stock_transaction_item_id", "disposal_reason", "cost_at_disposal"] as const,
  enumFields: ["disposal_reason"] as const,
  relationFields: ["stock_transaction_item_id"] as const,
} as const;

export type DisposalRecordFieldName = keyof typeof disposalRecordMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a DisposalRecord. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface DisposalRecordCreateFormState {
  stock_transaction_item_id: string;
  disposal_reason: DisposalReason;
  cost_at_disposal: number;
  note?: string | null;
}

/** Form-state shape for updating a DisposalRecord. Every field optional. */
export interface DisposalRecordUpdateFormState {
  stock_transaction_item_id?: string;
  disposal_reason?: DisposalReason;
  cost_at_disposal?: number;
  note?: string | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyDisposalRecordCreateForm(): DisposalRecordCreateFormState {
  return {
    stock_transaction_item_id: '',
    disposal_reason: DisposalReason.Expired,
    cost_at_disposal: 0,
    note: '',
  };
}

/** Convert create form state into the payload that baseDisposalRecordCreateSchema accepts. */
export function buildDisposalRecordCreatePayload(form: DisposalRecordCreateFormState): BaseDisposalRecordCreate {
  const payload: Record<string, unknown> = {
    stock_transaction_item_id: form.stock_transaction_item_id.trim(),
    disposal_reason: form.disposal_reason,
    cost_at_disposal: form.cost_at_disposal,
    note: form.note?.toString().trim() || null,
  };

  return payload as BaseDisposalRecordCreate;
}

/** Convert update form state into the payload that baseDisposalRecordUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildDisposalRecordUpdatePayload(form: DisposalRecordUpdateFormState): BaseDisposalRecordUpdate {
  const payload: Record<string, unknown> = {};
  if (form.stock_transaction_item_id !== undefined) {
    payload.stock_transaction_item_id = form.stock_transaction_item_id?.toString().trim() ?? null;
  }
  if (form.disposal_reason !== undefined) {
    payload.disposal_reason = form.disposal_reason;
  }
  if (form.cost_at_disposal !== undefined) {
    payload.cost_at_disposal = form.cost_at_disposal;
  }
  if (form.note !== undefined) {
    payload.note = form.note?.toString().trim() ?? null;
  }
  return payload as BaseDisposalRecordUpdate;
}
