/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { FloatingSectionProduct } from './FloatingSectionProduct';
import type { ProductSku } from './ProductSku';

/**
 * フローティングセクション商品SKU
 */
export interface FloatingSectionProductSku {
  id: string;
  floatingSectionProduct_id: string;
  floatingSectionProduct?: FloatingSectionProduct;
  productSku_id: string;
  productSku?: ProductSku;
  is_active: boolean;
  selling_price: number;
  is_price_overridden: boolean;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for FloatingSectionProductSku
 */
export const floatingSectionProductSkuI18n = {
  label: {"ja":"フローティングセクション商品SKU","en":"Floating Section Product SKU","vi":"SKU sản phẩm trong khung giờ ưu đãi"},
  fields: {
    floating_section_product: {
      label: {"ja":"フローティングセクション商品","en":"Floating Section Product","vi":"Sản phẩm trong khung giờ ưu đãi"},
      placeholder: {"ja":"フローティングセクション商品を入力","en":"Enter Floating Section Product","vi":"Nhập Sản phẩm trong khung giờ ưu đãi"},
    },
    product_sku: {
      label: {"ja":"商品SKU","en":"Product SKU","vi":"SKU sản phẩm"},
      placeholder: {"ja":"商品SKUを入力","en":"Enter Product SKU","vi":"Nhập SKU sản phẩm"},
    },
    is_active: {
      label: {"ja":"有効","en":"Active","vi":"Hoạt động"},
      placeholder: {"ja":"有効を入力","en":"Enter Active","vi":"Nhập Hoạt động"},
    },
    selling_price: {
      label: {"ja":"販売価格","en":"Selling Price","vi":"Giá bán"},
      placeholder: {"ja":"販売価格を入力","en":"Enter Selling Price","vi":"Nhập Giá bán"},
    },
    is_price_overridden: {
      label: {"ja":"価格上書き済み","en":"Price Overridden","vi":"Đã ghi đè giá"},
      placeholder: {"ja":"価格上書き済みを入力","en":"Enter Price Overridden","vi":"Nhập Đã ghi đè giá"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for FloatingSectionProductSku */
export const baseFloatingSectionProductSkuSchemas = {
  is_active: z.boolean(),
  selling_price: z.number(),
  is_price_overridden: z.boolean(),
} as const;

/** Create schema for FloatingSectionProductSku */
export const baseFloatingSectionProductSkuCreateSchema = z.object({
  is_active: baseFloatingSectionProductSkuSchemas.is_active,
  selling_price: baseFloatingSectionProductSkuSchemas.selling_price,
  is_price_overridden: baseFloatingSectionProductSkuSchemas.is_price_overridden,
});

/** Update schema for FloatingSectionProductSku */
export const baseFloatingSectionProductSkuUpdateSchema = baseFloatingSectionProductSkuCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseFloatingSectionProductSkuCreate = z.infer<typeof baseFloatingSectionProductSkuCreateSchema>;
export type BaseFloatingSectionProductSkuUpdate = z.infer<typeof baseFloatingSectionProductSkuUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getFloatingSectionProductSkuLabel(locale: string): string {
  return floatingSectionProductSkuI18n.label[locale as keyof typeof floatingSectionProductSkuI18n.label] ?? floatingSectionProductSkuI18n.label['en'] ?? 'FloatingSectionProductSku';
}

/** Get field label for a specific locale */
export function getFloatingSectionProductSkuFieldLabel(field: string, locale: string): string {
  const fields = floatingSectionProductSkuI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getFloatingSectionProductSkuFieldPlaceholder(field: string, locale: string): string {
  const fields = floatingSectionProductSkuI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for FloatingSectionProductSku.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const floatingSectionProductSkuMetadata = {
  modelName: "FloatingSectionProductSku",
  table: "floating_section_product_skus",

  fields: {
    floating_section_product_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "FloatingSectionProduct",
        table: "floating_section_products",
        onDelete: "CASCADE",
      },
      label: {},
    },
    product_sku_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "ProductSku",
        table: "product_skus",
        onDelete: "CASCADE",
      },
      label: {},
    },
    is_active: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "有効",
        en: "Active",
        vi: "Hoạt động",
      },
      placeholder: {
        ja: "有効を入力",
        en: "Enter Active",
        vi: "Nhập Hoạt động",
      },
      description: {
        ja: "SKUレベルのトグル。個別のバリアントを無効にできます（例：特定のサイズが品切れ）。",
        en: "SKU-level toggle. Can deactivate an individual variant (e.g. one size out of stock).",
        vi: "Toggle cấp SKU. Có thể tắt bán 1 biến thể cụ thể (vd hết size lớn).",
      },
    },
    selling_price: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "販売価格",
        en: "Selling Price",
        vi: "Giá bán",
      },
      placeholder: {
        ja: "販売価格を入力",
        en: "Enter Selling Price",
        vi: "Nhập Giá bán",
      },
      description: {
        ja: "このバリアントのプロモーション価格。初期値はproduct_skus.selling_priceからコピー。本部/店舗が上書き可能。",
        en: "Promotional price for this variant. Initially copied from product_skus.selling_price; HQ/shop can override.",
        vi: "Giá ưu đãi cho biến thể này. Ban đầu copy từ product_skus.selling_price; HQ/shop có thể ghi đè.",
      },
    },
    is_price_overridden: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "価格上書き済み",
        en: "Price Overridden",
        vi: "Đã ghi đè giá",
      },
      placeholder: {
        ja: "価格上書き済みを入力",
        en: "Enter Price Overridden",
        vi: "Nhập Đã ghi đè giá",
      },
      description: {
        ja: "selling_priceがカスタマイズされたかどうか。作成/リセット直後はFalse。",
        en: "Whether selling_price has been customized. False right after create/reset.",
        vi: "selling_price đã được tùy chỉnh chưa. False ngay sau khi tạo/reset.",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["floating_section_product_id", "product_sku_id", "is_active", "selling_price", "is_price_overridden"] as const,
  enumFields: [] as const,
  relationFields: ["floating_section_product_id", "product_sku_id"] as const,
} as const;

export type FloatingSectionProductSkuFieldName = keyof typeof floatingSectionProductSkuMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a FloatingSectionProductSku. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface FloatingSectionProductSkuCreateFormState {
  floating_section_product_id: string;
  product_sku_id: string;
  is_active: boolean;
  selling_price: number;
  is_price_overridden: boolean;
}

/** Form-state shape for updating a FloatingSectionProductSku. Every field optional. */
export interface FloatingSectionProductSkuUpdateFormState {
  floating_section_product_id?: string;
  product_sku_id?: string;
  is_active?: boolean;
  selling_price?: number;
  is_price_overridden?: boolean;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyFloatingSectionProductSkuCreateForm(): FloatingSectionProductSkuCreateFormState {
  return {
    floating_section_product_id: '',
    product_sku_id: '',
    is_active: true,
    selling_price: 0,
    is_price_overridden: false,
  };
}

/** Convert create form state into the payload that baseFloatingSectionProductSkuCreateSchema accepts. */
export function buildFloatingSectionProductSkuCreatePayload(form: FloatingSectionProductSkuCreateFormState): BaseFloatingSectionProductSkuCreate {
  const payload: Record<string, unknown> = {
    floating_section_product_id: form.floating_section_product_id.trim(),
    product_sku_id: form.product_sku_id.trim(),
    is_active: form.is_active,
    selling_price: form.selling_price,
    is_price_overridden: form.is_price_overridden,
  };

  return payload as BaseFloatingSectionProductSkuCreate;
}

/** Convert update form state into the payload that baseFloatingSectionProductSkuUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildFloatingSectionProductSkuUpdatePayload(form: FloatingSectionProductSkuUpdateFormState): BaseFloatingSectionProductSkuUpdate {
  const payload: Record<string, unknown> = {};
  if (form.floating_section_product_id !== undefined) {
    payload.floating_section_product_id = form.floating_section_product_id?.toString().trim() ?? null;
  }
  if (form.product_sku_id !== undefined) {
    payload.product_sku_id = form.product_sku_id?.toString().trim() ?? null;
  }
  if (form.is_active !== undefined) {
    payload.is_active = form.is_active;
  }
  if (form.selling_price !== undefined) {
    payload.selling_price = form.selling_price;
  }
  if (form.is_price_overridden !== undefined) {
    payload.is_price_overridden = form.is_price_overridden;
  }
  return payload as BaseFloatingSectionProductSkuUpdate;
}
