/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { Product } from './Product';
import type { ProductSku } from './ProductSku';
import type { ToppingGroup } from './ToppingGroup';
import type { ToppingGroupItem } from './ToppingGroupItem';

/**
 * 商品トッピング項目上書き
 */
export interface ProductToppingGroupItemOverride {
  id: string;
  product_id: string;
  product?: Product;
  toppingGroup_id: string;
  toppingGroup?: ToppingGroup;
  toppingGroupItem_id: string;
  toppingGroupItem?: ToppingGroupItem;
  productSku_id?: string | null;
  productSku?: ProductSku | null;
  is_hidden: boolean;
  override_price?: number | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for ProductToppingGroupItemOverride
 */
export const productToppingGroupItemOverrideI18n = {
  label: {"ja":"商品トッピング項目上書き","en":"Product Topping Group Item Override","vi":"Ghi đè Topping theo Sản phẩm"},
  fields: {
    product: {
      label: {"ja":"商品","en":"Product","vi":"Sản phẩm"},
      placeholder: {"ja":"商品を入力","en":"Enter Product","vi":"Nhập Sản phẩm"},
    },
    topping_group: {
      label: {"ja":"トッピンググループ","en":"Topping Group","vi":"Nhóm Topping"},
      placeholder: {"ja":"トッピンググループを入力","en":"Enter Topping Group","vi":"Nhập Nhóm Topping"},
    },
    topping_group_item: {
      label: {"ja":"トッピンググループ項目","en":"Topping Group Item","vi":"Mục Topping"},
      placeholder: {"ja":"トッピンググループ項目を入力","en":"Enter Topping Group Item","vi":"Nhập Mục Topping"},
    },
    product_sku: {
      label: {"ja":"商品SKU","en":"Product SKU","vi":"SKU sản phẩm"},
      placeholder: {"ja":"商品SKUを入力","en":"Enter Product SKU","vi":"Nhập SKU sản phẩm"},
    },
    is_hidden: {
      label: {"ja":"非表示","en":"Is Hidden","vi":"Ẩn"},
      placeholder: {"ja":"非表示を入力","en":"Enter Is Hidden","vi":"Nhập Ẩn"},
    },
    override_price: {
      label: {"ja":"上書き価格","en":"Override Price","vi":"Giá ghi đè"},
      placeholder: {"ja":"上書き価格を入力","en":"Enter Override Price","vi":"Nhập Giá ghi đè"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for ProductToppingGroupItemOverride */
export const baseProductToppingGroupItemOverrideSchemas = {
  is_hidden: z.boolean(),
  override_price: z.number().optional().nullable(),
} as const;

/** Create schema for ProductToppingGroupItemOverride */
export const baseProductToppingGroupItemOverrideCreateSchema = z.object({
  is_hidden: baseProductToppingGroupItemOverrideSchemas.is_hidden,
  override_price: baseProductToppingGroupItemOverrideSchemas.override_price,
});

/** Update schema for ProductToppingGroupItemOverride */
export const baseProductToppingGroupItemOverrideUpdateSchema = baseProductToppingGroupItemOverrideCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseProductToppingGroupItemOverrideCreate = z.infer<typeof baseProductToppingGroupItemOverrideCreateSchema>;
export type BaseProductToppingGroupItemOverrideUpdate = z.infer<typeof baseProductToppingGroupItemOverrideUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getProductToppingGroupItemOverrideLabel(locale: string): string {
  return productToppingGroupItemOverrideI18n.label[locale as keyof typeof productToppingGroupItemOverrideI18n.label] ?? productToppingGroupItemOverrideI18n.label['en'] ?? 'ProductToppingGroupItemOverride';
}

/** Get field label for a specific locale */
export function getProductToppingGroupItemOverrideFieldLabel(field: string, locale: string): string {
  const fields = productToppingGroupItemOverrideI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getProductToppingGroupItemOverrideFieldPlaceholder(field: string, locale: string): string {
  const fields = productToppingGroupItemOverrideI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for ProductToppingGroupItemOverride.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const productToppingGroupItemOverrideMetadata = {
  modelName: "ProductToppingGroupItemOverride",
  table: "product_topping_group_item_overrides",

  fields: {
    product_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Product",
        table: "products",
        onDelete: "CASCADE",
      },
      label: {},
    },
    topping_group_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "ToppingGroup",
        table: "topping_groups",
        onDelete: "CASCADE",
      },
      label: {},
    },
    topping_group_item_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "ToppingGroupItem",
        table: "topping_group_items",
        onDelete: "CASCADE",
      },
      label: {},
    },
    product_sku_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "ProductSku",
        table: "product_skus",
        onDelete: "CASCADE",
      },
      label: {},
    },
    is_hidden: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "非表示",
        en: "Is Hidden",
        vi: "Ẩn",
      },
      placeholder: {
        ja: "非表示を入力",
        en: "Enter Is Hidden",
        vi: "Nhập Ẩn",
      },
    },
    override_price: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "上書き価格",
        en: "Override Price",
        vi: "Giá ghi đè",
      },
      placeholder: {
        ja: "上書き価格を入力",
        en: "Enter Override Price",
        vi: "Nhập Giá ghi đè",
      },
    },
  },

  translatableFields: [] as const,
  requiredFields: ["product_id", "topping_group_id", "topping_group_item_id", "is_hidden"] as const,
  enumFields: [] as const,
  relationFields: ["product_id", "topping_group_id", "topping_group_item_id", "product_sku_id"] as const,
} as const;

export type ProductToppingGroupItemOverrideFieldName = keyof typeof productToppingGroupItemOverrideMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a ProductToppingGroupItemOverride. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface ProductToppingGroupItemOverrideCreateFormState {
  product_id: string;
  topping_group_id: string;
  topping_group_item_id: string;
  product_sku_id?: string | null;
  is_hidden: boolean;
  override_price?: number | null;
}

/** Form-state shape for updating a ProductToppingGroupItemOverride. Every field optional. */
export interface ProductToppingGroupItemOverrideUpdateFormState {
  product_id?: string;
  topping_group_id?: string;
  topping_group_item_id?: string;
  product_sku_id?: string | null;
  is_hidden?: boolean;
  override_price?: number | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyProductToppingGroupItemOverrideCreateForm(): ProductToppingGroupItemOverrideCreateFormState {
  return {
    product_id: '',
    topping_group_id: '',
    topping_group_item_id: '',
    product_sku_id: '',
    is_hidden: false,
    override_price: 0,
  };
}

/** Convert create form state into the payload that baseProductToppingGroupItemOverrideCreateSchema accepts. */
export function buildProductToppingGroupItemOverrideCreatePayload(form: ProductToppingGroupItemOverrideCreateFormState): BaseProductToppingGroupItemOverrideCreate {
  const payload: Record<string, unknown> = {
    product_id: form.product_id.trim(),
    topping_group_id: form.topping_group_id.trim(),
    topping_group_item_id: form.topping_group_item_id.trim(),
    product_sku_id: form.product_sku_id?.toString().trim() || null,
    is_hidden: form.is_hidden,
    override_price: form.override_price,
  };

  return payload as BaseProductToppingGroupItemOverrideCreate;
}

/** Convert update form state into the payload that baseProductToppingGroupItemOverrideUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildProductToppingGroupItemOverrideUpdatePayload(form: ProductToppingGroupItemOverrideUpdateFormState): BaseProductToppingGroupItemOverrideUpdate {
  const payload: Record<string, unknown> = {};
  if (form.product_id !== undefined) {
    payload.product_id = form.product_id?.toString().trim() ?? null;
  }
  if (form.topping_group_id !== undefined) {
    payload.topping_group_id = form.topping_group_id?.toString().trim() ?? null;
  }
  if (form.topping_group_item_id !== undefined) {
    payload.topping_group_item_id = form.topping_group_item_id?.toString().trim() ?? null;
  }
  if (form.product_sku_id !== undefined) {
    payload.product_sku_id = form.product_sku_id?.toString().trim() ?? null;
  }
  if (form.is_hidden !== undefined) {
    payload.is_hidden = form.is_hidden;
  }
  if (form.override_price !== undefined) {
    payload.override_price = form.override_price;
  }
  return payload as BaseProductToppingGroupItemOverrideUpdate;
}
