/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import type { Locale } from '../common';
import { buildI18nPayload, emptyLocaleMap } from '../payload-helpers';
import { z } from 'zod';
import type { DateTimeString } from '../common';
import { ApprovalStatus } from '../enum/ApprovalStatus';
import type { Brand } from './Brand';
import type { Material } from './Material';
import type { Organization } from './Organization';
import type { ProductSku } from './ProductSku';
import type { User } from './User';

/**
 * レシピ
 */
export interface Recipe {
  id: string;
  sku?: string | null;
  name: string;
  description?: string | null;
  material_id?: string | null;
  material?: Material | null;
  output_quantity: number;
  output_unit?: string | null;
  ingredients?: unknown | null;
  preparation_time?: number | null;
  yield_variance_tolerance_pct?: number | null;
  instructions?: string | null;
  is_active: boolean;
  approval_status?: ApprovalStatus | null;
  approved_by_id?: string | null;
  approved_by?: User | null;
  approved_at?: DateTimeString | null;
  rejected_by_id?: string | null;
  rejected_by?: User | null;
  rejected_at?: DateTimeString | null;
  rejection_reason?: string | null;
  allergen_rollup?: unknown | null;
  allergen_rollup_updated_at?: DateTimeString | null;
  skus?: ProductSku[];
  organization_id: string;
  organization?: Organization;
  brand_id: string;
  brand?: Brand;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Recipe
 */
export const recipeI18n = {
  label: {"ja":"レシピ","en":"Recipe","vi":"Công thức"},
  fields: {
    sku: {
      label: {"ja":"レシピSKU","en":"Recipe SKU","vi":"Mã công thức"},
      placeholder: {"ja":"例：R-001","en":"e.g., R-001","vi":"VD: R-001"},
    },
    name: {
      label: {"ja":"レシピ名","en":"Recipe Name","vi":"Tên công thức"},
      placeholder: {"ja":"レシピ名を入力","en":"Enter Recipe Name","vi":"Nhập Tên công thức"},
    },
    description: {
      label: {"ja":"説明","en":"Description","vi":"Mô tả"},
      placeholder: {"ja":"説明を入力","en":"Enter Description","vi":"Nhập Mô tả"},
    },
    material: {
      label: {"ja":"材料","en":"Material","vi":"Nguyên liệu"},
      placeholder: {"ja":"材料を入力","en":"Enter Material","vi":"Nhập Nguyên liệu"},
    },
    output_quantity: {
      label: {"ja":"出力数量","en":"Output Quantity","vi":"Số lượng đầu ra"},
      placeholder: {"ja":"出力数量を入力","en":"Enter Output Quantity","vi":"Nhập Số lượng đầu ra"},
    },
    output_unit: {
      label: {"ja":"出力単位","en":"Output Unit","vi":"Đơn vị đầu ra"},
      placeholder: {"ja":"出力単位を入力","en":"Enter Output Unit","vi":"Nhập Đơn vị đầu ra"},
    },
    ingredients: {
      label: {"ja":"材料リスト","en":"Ingredients","vi":"Danh sách nguyên liệu"},
      placeholder: {"ja":"材料リストを入力","en":"Enter Ingredients","vi":"Nhập Danh sách nguyên liệu"},
    },
    preparation_time: {
      label: {"ja":"調理時間","en":"Preparation Time","vi":"Thời gian chuẩn bị"},
      placeholder: {"ja":"調理時間を入力","en":"Enter Preparation Time","vi":"Nhập Thời gian chuẩn bị"},
    },
    yield_variance_tolerance_pct: {
      label: {"ja":"歩留まり許容差（%）","en":"Yield Variance Tolerance (%)","vi":"Sai số cho phép (%)"},
      placeholder: {"ja":"歩留まり許容差（%）を入力","en":"Enter Yield Variance Tolerance (%)","vi":"Nhập Sai số cho phép (%)"},
    },
    instructions: {
      label: {"ja":"調理手順","en":"Instructions","vi":"Hướng dẫn"},
      placeholder: {"ja":"調理手順を入力","en":"Enter Instructions","vi":"Nhập Hướng dẫn"},
    },
    is_active: {
      label: {"ja":"有効","en":"Active","vi":"Hoạt động"},
      placeholder: {"ja":"有効を入力","en":"Enter Active","vi":"Nhập Hoạt động"},
    },
    approval_status: {
      label: {"ja":"承認ステータス","en":"Approval Status","vi":"Trạng thái duyệt"},
      placeholder: {"ja":"承認ステータスを入力","en":"Enter Approval Status","vi":"Nhập Trạng thái duyệt"},
    },
    approved_by: {
      label: {"ja":"承認者","en":"Approved By","vi":"Người duyệt"},
      placeholder: {"ja":"承認者を入力","en":"Enter Approved By","vi":"Nhập Người duyệt"},
    },
    approved_at: {
      label: {"ja":"承認日時","en":"Approved At","vi":"Thời điểm duyệt"},
      placeholder: {"ja":"承認日時を入力","en":"Enter Approved At","vi":"Nhập Thời điểm duyệt"},
    },
    rejected_by: {
      label: {"ja":"却下者","en":"Rejected By","vi":"Người từ chối"},
      placeholder: {"ja":"却下者を入力","en":"Enter Rejected By","vi":"Nhập Người từ chối"},
    },
    rejected_at: {
      label: {"ja":"却下日時","en":"Rejected At","vi":"Thời điểm từ chối"},
      placeholder: {"ja":"却下日時を入力","en":"Enter Rejected At","vi":"Nhập Thời điểm từ chối"},
    },
    rejection_reason: {
      label: {"ja":"却下理由","en":"Rejection Reason","vi":"Lý do từ chối"},
      placeholder: {"ja":"却下理由を入力","en":"Enter Rejection Reason","vi":"Nhập Lý do từ chối"},
    },
    allergen_rollup: {
      label: {"ja":"アレルゲン集約","en":"Allergen Rollup","vi":"Tổng hợp dị ứng"},
      placeholder: {"ja":"アレルゲン集約を入力","en":"Enter Allergen Rollup","vi":"Nhập Tổng hợp dị ứng"},
    },
    allergen_rollup_updated_at: {
      label: {"ja":"アレルゲン集約更新日時","en":"Allergen Rollup Updated At","vi":"Thời điểm cập nhật tổng hợp dị ứng"},
      placeholder: {"ja":"アレルゲン集約更新日時を入力","en":"Enter Allergen Rollup Updated At","vi":"Nhập Thời điểm cập nhật tổng hợp dị ứng"},
    },
    skus: {
      label: {"ja":"SKU一覧","en":"SKUs","vi":"SKU"},
      placeholder: {"ja":"SKU一覧を入力","en":"Enter SKUs","vi":"Nhập SKU"},
    },
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    brand: {
      label: {"ja":"ブランド","en":"Brand","vi":"Thương hiệu"},
      placeholder: {"ja":"ブランドを入力","en":"Enter Brand","vi":"Nhập Thương hiệu"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Recipe */
export const baseRecipeSchemas = {
  sku: z.string().max(50).optional().nullable(),
  name: z.string().min(1).max(255),
  description: z.string().optional().nullable(),
  output_quantity: z.number(),
  output_unit: z.string().max(50).optional().nullable(),
  ingredients: z.unknown().optional().nullable(),
  preparation_time: z.number().int().optional().nullable(),
  yield_variance_tolerance_pct: z.number().optional().nullable(),
  instructions: z.string().optional().nullable(),
  is_active: z.boolean(),
  approval_status: z.nativeEnum(ApprovalStatus).optional().nullable(),
  approved_at: z.string().datetime({ offset: true }).optional().nullable(),
  rejected_at: z.string().datetime({ offset: true }).optional().nullable(),
  rejection_reason: z.string().optional().nullable(),
  allergen_rollup: z.unknown().optional().nullable(),
  allergen_rollup_updated_at: z.string().datetime({ offset: true }).optional().nullable(),
} as const;

/** Create schema for Recipe */
export const baseRecipeCreateSchema = z.object({
  sku: baseRecipeSchemas.sku,
  name: baseRecipeSchemas.name,
  description: baseRecipeSchemas.description,
  output_quantity: baseRecipeSchemas.output_quantity,
  output_unit: baseRecipeSchemas.output_unit,
  ingredients: baseRecipeSchemas.ingredients,
  preparation_time: baseRecipeSchemas.preparation_time,
  yield_variance_tolerance_pct: baseRecipeSchemas.yield_variance_tolerance_pct,
  instructions: baseRecipeSchemas.instructions,
  is_active: baseRecipeSchemas.is_active,
  approval_status: baseRecipeSchemas.approval_status,
  approved_at: baseRecipeSchemas.approved_at,
  rejected_at: baseRecipeSchemas.rejected_at,
  rejection_reason: baseRecipeSchemas.rejection_reason,
  allergen_rollup: baseRecipeSchemas.allergen_rollup,
  allergen_rollup_updated_at: baseRecipeSchemas.allergen_rollup_updated_at,
  ja: z.object({
    name: z.string().max(255).optional().nullable(),
    description: z.string().optional().nullable(),
    instructions: z.string().optional().nullable(),
    rejection_reason: z.string().optional().nullable(),
  }).optional(),
  en: z.object({
    name: z.string().max(255).optional().nullable(),
    description: z.string().optional().nullable(),
    instructions: z.string().optional().nullable(),
    rejection_reason: z.string().optional().nullable(),
  }).optional(),
  vi: z.object({
    name: z.string().max(255).optional().nullable(),
    description: z.string().optional().nullable(),
    instructions: z.string().optional().nullable(),
    rejection_reason: z.string().optional().nullable(),
  }).optional(),
});

/** Update schema for Recipe */
export const baseRecipeUpdateSchema = baseRecipeCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseRecipeCreate = z.infer<typeof baseRecipeCreateSchema>;
export type BaseRecipeUpdate = z.infer<typeof baseRecipeUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getRecipeLabel(locale: string): string {
  return recipeI18n.label[locale as keyof typeof recipeI18n.label] ?? recipeI18n.label['en'] ?? 'Recipe';
}

/** Get field label for a specific locale */
export function getRecipeFieldLabel(field: string, locale: string): string {
  const fields = recipeI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getRecipeFieldPlaceholder(field: string, locale: string): string {
  const fields = recipeI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for Recipe.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const recipeMetadata = {
  modelName: "Recipe",
  table: "recipes",

  fields: {
    sku: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "レシピSKU",
        en: "Recipe SKU",
        vi: "Mã công thức",
      },
      placeholder: {
        ja: "例：R-001",
        en: "e.g., R-001",
        vi: "VD: R-001",
      },
      description: {
        ja: "プレフィックスR-を持つ一意のSKU",
        en: "Unique SKU with prefix R-",
        vi: "SKU duy nhất với tiền tố R-",
      },
    },
    name: {
      type: "string",
      required: true,
      nullable: false,
      translatable: true,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "レシピ名",
        en: "Recipe Name",
        vi: "Tên công thức",
      },
      placeholder: {
        ja: "レシピ名を入力",
        en: "Enter Recipe Name",
        vi: "Nhập Tên công thức",
      },
    },
    description: {
      type: "text",
      required: false,
      nullable: true,
      translatable: true,
      validation: {},
      label: {
        ja: "説明",
        en: "Description",
        vi: "Mô tả",
      },
      placeholder: {
        ja: "説明を入力",
        en: "Enter Description",
        vi: "Nhập Mô tả",
      },
    },
    material_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Material",
        table: "materials",
        onDelete: "CASCADE",
      },
      label: {},
    },
    output_quantity: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "出力数量",
        en: "Output Quantity",
        vi: "Số lượng đầu ra",
      },
      placeholder: {
        ja: "出力数量を入力",
        en: "Enter Output Quantity",
        vi: "Nhập Số lượng đầu ra",
      },
    },
    output_unit: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "出力単位",
        en: "Output Unit",
        vi: "Đơn vị đầu ra",
      },
      placeholder: {
        ja: "出力単位を入力",
        en: "Enter Output Unit",
        vi: "Nhập Đơn vị đầu ra",
      },
    },
    ingredients: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "材料リスト",
        en: "Ingredients",
        vi: "Danh sách nguyên liệu",
      },
      placeholder: {
        ja: "材料リストを入力",
        en: "Enter Ingredients",
        vi: "Nhập Danh sách nguyên liệu",
      },
    },
    preparation_time: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "調理時間",
        en: "Preparation Time",
        vi: "Thời gian chuẩn bị",
      },
      placeholder: {
        ja: "調理時間を入力",
        en: "Enter Preparation Time",
        vi: "Nhập Thời gian chuẩn bị",
      },
      description: {
        ja: "分単位",
        en: "Time in minutes",
        vi: "Tính bằng phút",
      },
    },
    yield_variance_tolerance_pct: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "歩留まり許容差（%）",
        en: "Yield Variance Tolerance (%)",
        vi: "Sai số cho phép (%)",
      },
      placeholder: {
        ja: "歩留まり許容差（%）を入力",
        en: "Enter Yield Variance Tolerance (%)",
        vi: "Nhập Sai số cho phép (%)",
      },
      description: {
        ja: "実際生産量と計画生産量の許容差（%）。0 = 差異が出るたびに理由が必要。",
        en: "Allowed % drift between actual and planned yield before a reason is required. 0 = any drift requires a reason.",
        vi: "Sai số % cho phép giữa sản lượng thực và kế hoạch trước khi cần lý do. 0 = mọi chênh lệch đều cần lý do.",
      },
    },
    instructions: {
      type: "text",
      required: false,
      nullable: true,
      translatable: true,
      validation: {},
      label: {
        ja: "調理手順",
        en: "Instructions",
        vi: "Hướng dẫn",
      },
      placeholder: {
        ja: "調理手順を入力",
        en: "Enter Instructions",
        vi: "Nhập Hướng dẫn",
      },
    },
    is_active: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "有効",
        en: "Active",
        vi: "Hoạt động",
      },
      placeholder: {
        ja: "有効を入力",
        en: "Enter Active",
        vi: "Nhập Hoạt động",
      },
    },
    approval_status: {
      type: "enum",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      enum: "ApprovalStatus",
      enumValues: ["draft", "pending", "approved", "rejected"] as const,
      label: {
        ja: "承認ステータス",
        en: "Approval Status",
        vi: "Trạng thái duyệt",
      },
      placeholder: {
        ja: "承認ステータスを入力",
        en: "Enter Approval Status",
        vi: "Nhập Trạng thái duyệt",
      },
    },
    approved_by_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "User",
        table: "users",
        onDelete: "SET NULL",
      },
      label: {},
    },
    approved_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "承認日時",
        en: "Approved At",
        vi: "Thời điểm duyệt",
      },
      placeholder: {
        ja: "承認日時を入力",
        en: "Enter Approved At",
        vi: "Nhập Thời điểm duyệt",
      },
    },
    rejected_by_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "User",
        table: "users",
        onDelete: "SET NULL",
      },
      label: {},
    },
    rejected_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "却下日時",
        en: "Rejected At",
        vi: "Thời điểm từ chối",
      },
      placeholder: {
        ja: "却下日時を入力",
        en: "Enter Rejected At",
        vi: "Nhập Thời điểm từ chối",
      },
    },
    rejection_reason: {
      type: "text",
      required: false,
      nullable: true,
      translatable: true,
      validation: {},
      label: {
        ja: "却下理由",
        en: "Rejection Reason",
        vi: "Lý do từ chối",
      },
      placeholder: {
        ja: "却下理由を入力",
        en: "Enter Rejection Reason",
        vi: "Nhập Lý do từ chối",
      },
    },
    allergen_rollup: {
      type: "json",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "アレルゲン集約",
        en: "Allergen Rollup",
        vi: "Tổng hợp dị ứng",
      },
      placeholder: {
        ja: "アレルゲン集約を入力",
        en: "Enter Allergen Rollup",
        vi: "Nhập Tổng hợp dị ứng",
      },
    },
    allergen_rollup_updated_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "アレルゲン集約更新日時",
        en: "Allergen Rollup Updated At",
        vi: "Thời điểm cập nhật tổng hợp dị ứng",
      },
      placeholder: {
        ja: "アレルゲン集約更新日時を入力",
        en: "Enter Allergen Rollup Updated At",
        vi: "Nhập Thời điểm cập nhật tổng hợp dị ứng",
      },
    },
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    brand_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Brand",
        table: "brands",
        onDelete: "CASCADE",
      },
      label: {},
    },
  },

  translatableFields: ["name", "description", "instructions", "rejection_reason"] as const,
  requiredFields: ["name", "output_quantity", "is_active", "organization_id", "brand_id"] as const,
  enumFields: ["approval_status"] as const,
  relationFields: ["material_id", "approved_by_id", "rejected_by_id", "organization_id", "brand_id"] as const,
} as const;

export type RecipeFieldName = keyof typeof recipeMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a Recipe. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface RecipeCreateFormState {
  sku?: string | null;
  name: Record<Locale, string>;
  description: Record<Locale, string>;
  material_id?: string | null;
  output_quantity: number;
  output_unit?: string | null;
  ingredients?: unknown | null;
  preparation_time?: number | null;
  yield_variance_tolerance_pct?: number | null;
  instructions: Record<Locale, string>;
  is_active: boolean;
  approval_status?: ApprovalStatus | null;
  approved_by_id?: string | null;
  approved_at?: string | null;
  rejected_by_id?: string | null;
  rejected_at?: string | null;
  rejection_reason: Record<Locale, string>;
  allergen_rollup?: unknown | null;
  allergen_rollup_updated_at?: string | null;
  organization_id: string;
  brand_id: string;
}

/** Form-state shape for updating a Recipe. Every field optional. */
export interface RecipeUpdateFormState {
  sku?: string | null;
  name?: Record<Locale, string>;
  description?: Record<Locale, string>;
  material_id?: string | null;
  output_quantity?: number;
  output_unit?: string | null;
  ingredients?: unknown | null;
  preparation_time?: number | null;
  yield_variance_tolerance_pct?: number | null;
  instructions?: Record<Locale, string>;
  is_active?: boolean;
  approval_status?: ApprovalStatus | null;
  approved_by_id?: string | null;
  approved_at?: string | null;
  rejected_by_id?: string | null;
  rejected_at?: string | null;
  rejection_reason?: Record<Locale, string>;
  allergen_rollup?: unknown | null;
  allergen_rollup_updated_at?: string | null;
  organization_id?: string;
  brand_id?: string;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyRecipeCreateForm(): RecipeCreateFormState {
  return {
    sku: '',
    name: emptyLocaleMap(),
    description: emptyLocaleMap(),
    material_id: '',
    output_quantity: 1,
    output_unit: '',
    ingredients: null,
    preparation_time: 0,
    yield_variance_tolerance_pct: 0,
    instructions: emptyLocaleMap(),
    is_active: true,
    approved_by_id: '',
    approved_at: '',
    rejected_by_id: '',
    rejected_at: '',
    rejection_reason: emptyLocaleMap(),
    allergen_rollup: null,
    allergen_rollup_updated_at: '',
    organization_id: '',
    brand_id: '',
  };
}

/** Convert create form state into the payload that baseRecipeCreateSchema accepts. */
export function buildRecipeCreatePayload(form: RecipeCreateFormState): BaseRecipeCreate {
  const payload: Record<string, unknown> = {
    sku: form.sku?.toString().trim() || null,
    name: (form.name["ja"] ?? '').trim(),
    description: (form.description["ja"] ?? '').trim(),
    material_id: form.material_id?.toString().trim() || null,
    output_quantity: form.output_quantity,
    output_unit: form.output_unit?.toString().trim() || null,
    ingredients: form.ingredients,
    preparation_time: form.preparation_time,
    yield_variance_tolerance_pct: form.yield_variance_tolerance_pct,
    instructions: (form.instructions["ja"] ?? '').trim(),
    is_active: form.is_active,
    approval_status: form.approval_status,
    approved_by_id: form.approved_by_id?.toString().trim() || null,
    approved_at: form.approved_at,
    rejected_by_id: form.rejected_by_id?.toString().trim() || null,
    rejected_at: form.rejected_at,
    rejection_reason: (form.rejection_reason["ja"] ?? '').trim(),
    allergen_rollup: form.allergen_rollup,
    allergen_rollup_updated_at: form.allergen_rollup_updated_at,
    organization_id: form.organization_id.trim(),
    brand_id: form.brand_id.trim(),
  };

  // Per-locale sub-objects (matches issue #53 wire shape).
  const i18n = buildI18nPayload({
    name: form.name,
    description: form.description,
    instructions: form.instructions,
    rejection_reason: form.rejection_reason,
  });
  Object.assign(payload, i18n);

  return payload as BaseRecipeCreate;
}

/** Convert update form state into the payload that baseRecipeUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildRecipeUpdatePayload(form: RecipeUpdateFormState): BaseRecipeUpdate {
  const payload: Record<string, unknown> = {};
  if (form.sku !== undefined) {
    payload.sku = form.sku?.toString().trim() ?? null;
  }
  if (form.name !== undefined) {
    payload.name = (form.name["ja"] ?? '').trim();
  }
  if (form.description !== undefined) {
    payload.description = (form.description["ja"] ?? '').trim();
  }
  if (form.material_id !== undefined) {
    payload.material_id = form.material_id?.toString().trim() ?? null;
  }
  if (form.output_quantity !== undefined) {
    payload.output_quantity = form.output_quantity;
  }
  if (form.output_unit !== undefined) {
    payload.output_unit = form.output_unit?.toString().trim() ?? null;
  }
  if (form.ingredients !== undefined) {
    payload.ingredients = form.ingredients;
  }
  if (form.preparation_time !== undefined) {
    payload.preparation_time = form.preparation_time;
  }
  if (form.yield_variance_tolerance_pct !== undefined) {
    payload.yield_variance_tolerance_pct = form.yield_variance_tolerance_pct;
  }
  if (form.instructions !== undefined) {
    payload.instructions = (form.instructions["ja"] ?? '').trim();
  }
  if (form.is_active !== undefined) {
    payload.is_active = form.is_active;
  }
  if (form.approval_status !== undefined) {
    payload.approval_status = form.approval_status;
  }
  if (form.approved_by_id !== undefined) {
    payload.approved_by_id = form.approved_by_id?.toString().trim() ?? null;
  }
  if (form.approved_at !== undefined) {
    payload.approved_at = form.approved_at;
  }
  if (form.rejected_by_id !== undefined) {
    payload.rejected_by_id = form.rejected_by_id?.toString().trim() ?? null;
  }
  if (form.rejected_at !== undefined) {
    payload.rejected_at = form.rejected_at;
  }
  if (form.rejection_reason !== undefined) {
    payload.rejection_reason = (form.rejection_reason["ja"] ?? '').trim();
  }
  if (form.allergen_rollup !== undefined) {
    payload.allergen_rollup = form.allergen_rollup;
  }
  if (form.allergen_rollup_updated_at !== undefined) {
    payload.allergen_rollup_updated_at = form.allergen_rollup_updated_at;
  }
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.brand_id !== undefined) {
    payload.brand_id = form.brand_id?.toString().trim() ?? null;
  }

  // Per-locale sub-objects only for fields the user touched.
  const localeInput: Record<string, Record<string, string> | undefined> = {};
  if (form.name !== undefined) localeInput.name = form.name;
  if (form.description !== undefined) localeInput.description = form.description;
  if (form.instructions !== undefined) localeInput.instructions = form.instructions;
  if (form.rejection_reason !== undefined) localeInput.rejection_reason = form.rejection_reason;
  Object.assign(payload, buildI18nPayload(localeInput));
  return payload as BaseRecipeUpdate;
}
