-- Code generated by omnify. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'draft',
    is_hidden INTEGER NOT NULL DEFAULT 0,
    organization_id TEXT NOT NULL,
    brand_id TEXT NOT NULL,
    product_type_id INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    deleted_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_products_organization_id ON products(organization_id);

CREATE INDEX IF NOT EXISTS idx_products_brand_id ON products(brand_id);

CREATE INDEX IF NOT EXISTS idx_products_product_type_id ON products(product_type_id);
