<?php

namespace App\Omnify\Modules\MaterialBatch\Policies;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\MaterialBatch;
use App\Models\User;
use Illuminate\Auth\Access\HandlesAuthorization;

class MaterialBatchPolicyBase
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can view.
     */
    public function view(User $user, MaterialBatch $record): bool
    {
        return true;
    }

    /**
     * Determine whether the user can viewAny.
     */
    public function viewAny(User $user): bool
    {
        return true;
    }

    /**
     * Determine whether the user can create.
     */
    public function create(User $user): bool
    {
        return true;
    }

    /**
     * Determine whether the user can update.
     */
    public function update(User $user, MaterialBatch $record): bool
    {
        return true;
    }

    /**
     * Determine whether the user can delete.
     */
    public function delete(User $user, MaterialBatch $record): bool
    {
        return true;
    }

    /**
     * Determine whether the user can restore.
     */
    public function restore(User $user, MaterialBatch $record): bool
    {
        return true;
    }

    /**
     * Determine whether the user can forceDelete.
     */
    public function forceDelete(User $user, MaterialBatch $record): bool
    {
        return true;
    }
}
