<?php

namespace App\Services\Printing;

use App\Models\Printer;
use App\Models\PrintJob;
use App\Models\User;
use App\Services\Print\TemplateStamp;
use App\Services\Printing\Enums\PrintConfidence;
use App\Services\Printing\Enums\PrintJobKind;
use App\Services\Printing\Enums\PrintJobStatus;
use App\Services\Printing\Enums\PrintTransport;
use App\Services\Printing\Enums\UposPrinterStatus;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

/**
 * plan-052 T1.2 — ingest a batch of ws_lan JOURNAL rows synced UP by a
 * workstation.
 *
 * This is the ONLY writer of `ws_lan` print_jobs rows, and it only ever
 * INSERTS. The workstation printed already; Cloud is writing down history, not
 * running a queue (DESIGN §1b). Three properties follow, and each is a rule
 * this class must not break:
 *
 *   - **P-07 real time.** `printed_at` comes from the device's clock at the
 *     moment the paper came out. A shop that was offline all evening and syncs
 *     at 09:00 the next morning must not have every slip stamped 09:00 — that
 *     would drag the whole ledger into the wrong business day (#1091).
 *   - **P-09 idempotency at the constraint.** The id is generated by the
 *     device, and it is the primary key. A retried batch collides in the DB.
 *     No application-level "does it exist?" check, because two concurrent
 *     retries race past those.
 *   - **P-33 no invented confidence.** A device may report `confirmed` only if
 *     its own machine can actually confirm. If the printer's capability
 *     profile says error detection is level A, the claim is clamped back down
 *     to `sent_only` here, at the boundary.
 *   - **§4 the trail, not a gate.** Since the 2026-07-28 ruling nothing in the
 *     printing pipeline may refuse a print, so this ingest is where the
 *     accountability lands: actor + channel on EVERY row, first print
 *     included. The "reprinted with no reason" flag is not written here — it is
 *     DERIVED from the row ({@see PrintJob::warnedWithoutReason()}),
 *     so a shop that printed offline all evening and never asked Cloud
 *     anything still arrives correctly flagged, and no stored copy can drift
 *     from the columns beside it.
 */
class PrintJobJournalIngestService
{
    public function __construct(private readonly PrintJobRegistry $registry) {}

    /**
     * @param  list<array<string, mixed>>  $entries
     * @return array{accepted: list<string>, duplicates: list<string>}
     */
    public function ingest(string $organizationId, string $branchId, array $entries): array
    {
        if ($entries === []) {
            return ['accepted' => [], 'duplicates' => []];
        }

        $ids = array_values(array_filter(array_map(
            static fn (array $entry): string => (string) ($entry['id'] ?? ''),
            $entries,
        )));

        $existing = PrintJob::query()->whereIn('id', $ids)->pluck('id')->all();

        $printerProfiles = $this->printerProfiles($branchId);
        $knownActors = $this->knownActors($entries);

        $rows = [];
        $accepted = [];
        $duplicates = [];
        $now = CarbonImmutable::now();

        foreach ($entries as $entry) {
            $id = (string) ($entry['id'] ?? '');

            if ($id === '' || in_array($id, $existing, true) || isset($rows[$id])) {
                // Already recorded (or repeated inside this very batch) — the
                // fact is unchanged, so this is a success, not an error.
                $duplicates[] = $id;

                continue;
            }

            $rows[$id] = $this->buildRow($id, $organizationId, $branchId, $entry, $printerProfiles, $knownActors, $now);
            $accepted[] = $id;
        }

        if ($rows !== []) {
            // insertOrIgnore, not insert: between the SELECT above and this
            // write another sync attempt may have landed the same batch. The
            // PK collision is the guarantee; this just keeps it quiet.
            DB::table('print_jobs')->insertOrIgnore(array_values($rows));
        }

        $this->recordPrinterStatuses($branchId, $entries, $printerProfiles);

        return ['accepted' => $accepted, 'duplicates' => array_values(array_unique($duplicates))];
    }

    /**
     * @param  array<string, mixed>  $entry
     * @param  array<string, PrinterCapabilityProfile>  $printerProfiles
     * @param  list<string>  $knownActors
     * @return array<string, mixed>
     */
    private function buildRow(
        string $id,
        string $organizationId,
        string $branchId,
        array $entry,
        array $printerProfiles,
        array $knownActors,
        CarbonImmutable $now,
    ): array {
        $kind = PrintJobKind::tryFrom((string) ($entry['kind'] ?? '')) ?? PrintJobKind::Report;
        $status = PrintJobStatus::tryFrom((string) ($entry['status'] ?? '')) ?? PrintJobStatus::Printed;

        $printedAt = $this->parseTimestamp($entry['printed_at'] ?? null);
        $issuedAt = $this->parseTimestamp($entry['issued_at'] ?? null) ?? $printedAt ?? $now;

        $printerId = $this->normaliseId($entry['printer_id'] ?? null);
        $confidence = $this->resolveConfidence(
            (string) ($entry['confidence'] ?? PrintConfidence::SentOnly->value),
            $printerId === null ? null : ($printerProfiles[$printerId] ?? null),
        );

        return [
            'id' => $id,
            'organization_id' => $organizationId,
            'branch_id' => $branchId,
            'printer_id' => $printerId !== null && isset($printerProfiles[$printerId]) ? $printerId : null,
            // A workstation journal is ws_lan BY DEFINITION — the device does
            // not get to claim a transport it does not own.
            'transport' => PrintTransport::WsLan->value,
            'kind' => $kind->value,
            'order_id' => $this->normaliseId($entry['order_id'] ?? null),
            'payment_id' => $this->normaliseId($entry['payment_id'] ?? null),
            'payload' => isset($entry['payload']) && is_array($entry['payload'])
                ? json_encode($entry['payload'])
                : null,
            'reprint_no' => max(1, (int) ($entry['reprint_no'] ?? 1)),
            // §4 point 2 — WHO. Stamped on EVERY row, first print included:
            // the channel always (it is never unknown — a print came from
            // somewhere), the user whenever the device named one. A null actor
            // is an honest "this workstation printed it with nobody signed in",
            // not a hole in the trail.
            'requested_by_id' => $this->resolveActor($entry['requested_by_id'] ?? null, $knownActors),
            'requested_via' => $this->normaliseString($entry['requested_via'] ?? null, 32) ?? 'workstation',
            'reprint_reason' => $this->normaliseString($entry['reprint_reason'] ?? null, 255),
            // TR-28 — WHICH layout drew the sheet, as the device recorded it
            // (`<scope>:<version>`). Taken verbatim rather than re-resolved:
            // the workstation is the only tier that knows, because it is the
            // tier that rendered, and Cloud re-resolving here would answer with
            // whatever is current TODAY — which for a sheet printed last month
            // is a different document.
            //
            // Absent stays NULL, and the distinction is load-bearing: NULL means
            // the legacy formatter drew it, which has no version at all
            // ({@see TemplateStamp}). `normaliseString` already collapses
            // ''/whitespace to null, so an older workstation that never sends the
            // field and a newer one that sends nothing both land honestly.
            'template_version' => $this->normaliseString(
                $entry['template_version'] ?? null,
                TemplateStamp::MAX_LENGTH,
            ),
            'status' => $status->value,
            'confidence' => $confidence->value,
            'attempts' => max(0, (int) ($entry['attempts'] ?? 1)),
            'last_error' => $this->normaliseString($entry['last_error'] ?? null, 255),
            'acked_at' => $this->parseTimestamp($entry['acked_at'] ?? null),
            'printed_reported_at' => $printedAt,
            'expires_at' => $this->registry->expiresAt($kind, $issuedAt),
            'created_at' => $now,
            'updated_at' => $now,
        ];
    }

    /**
     * P-33 — the device tells us what it believes; the printer's declared
     * capability decides whether that belief is admissible. A machine on a raw
     * socket with no status channel cannot have confirmed anything, whatever
     * the payload says.
     */
    private function resolveConfidence(string $claimed, ?PrinterCapabilityProfile $profile): PrintConfidence
    {
        $confidence = PrintConfidence::tryFrom($claimed) ?? PrintConfidence::SentOnly;

        if ($confidence === PrintConfidence::Confirmed
            && $profile !== null
            && $profile->printConfidence() === PrintConfidence::SentOnly->value) {
            return PrintConfidence::SentOnly;
        }

        return $confidence;
    }

    /**
     * T1.3 — mirror the UPOS status the workstation observed onto the printer
     * row, so an HQ dashboard can say "máy bếp 2 hết giấy lúc 19:40" instead of
     * nothing at all.
     *
     * The LAST entry in the batch wins, because a batch is ordered oldest-first
     * and the newest observation is the current one. This is the only column of
     * a printer that the ingest is allowed to move: config stays Cloud-owned
     * and flows the other way.
     *
     * @param  list<array<string, mixed>>  $entries
     * @param  array<string, PrinterCapabilityProfile>  $printerProfiles
     */
    private function recordPrinterStatuses(string $branchId, array $entries, array $printerProfiles): void
    {
        $latest = [];

        foreach ($entries as $entry) {
            $printerId = $this->normaliseId($entry['printer_id'] ?? null);
            $status = UposPrinterStatus::tryFrom((string) ($entry['printer_status'] ?? ''));

            if ($printerId === null || $status === null || ! isset($printerProfiles[$printerId])) {
                continue;
            }

            $latest[$printerId] = [
                'status' => $status,
                'seen_at' => $this->parseTimestamp($entry['printed_at'] ?? null) ?? CarbonImmutable::now(),
            ];
        }

        foreach ($latest as $printerId => $observation) {
            Printer::query()
                ->where('id', $printerId)
                ->where('branch_id', $branchId)
                ->update([
                    'last_status' => $observation['status']->value,
                    'last_seen_at' => $observation['seen_at'],
                ]);
        }
    }

    /**
     * An actor id the device sent that Cloud has never heard of must NOT take
     * the batch down with it.
     *
     * `requested_by_id` is a foreign key, and a journal batch is one insert: a
     * single stale or mistyped id would reject every print in it, and those
     * rows exist nowhere else. A shop would silently lose an evening of history
     * because one tablet remembered a deleted user — which is precisely the
     * trade the ledger is not allowed to make (the journal records, it never
     * refuses).
     *
     * So unknown ids degrade to NULL: the print is still recorded, the channel
     * still says where it came from, and the person is simply unknown.
     *
     * @param  list<array<string, mixed>>  $entries
     * @return list<string>
     */
    private function knownActors(array $entries): array
    {
        $ids = array_values(array_unique(array_filter(array_map(
            fn (array $entry): ?string => $this->normaliseId($entry['requested_by_id'] ?? null),
            $entries,
        ))));

        if ($ids === []) {
            return [];
        }

        return User::query()->whereIn('id', $ids)->pluck('id')->all();
    }

    /** @param  list<string>  $knownActors */
    private function resolveActor(mixed $value, array $knownActors): ?string
    {
        $id = $this->normaliseId($value);

        return $id !== null && in_array($id, $knownActors, true) ? $id : null;
    }

    /** @return array<string, PrinterCapabilityProfile> */
    private function printerProfiles(string $branchId): array
    {
        return Printer::query()
            ->where('branch_id', $branchId)
            ->get(['id', 'model_profile'])
            ->mapWithKeys(fn (Printer $printer): array => [
                $printer->id => $printer->capabilityProfile(),
            ])
            ->all();
    }

    private function parseTimestamp(mixed $value): ?CarbonImmutable
    {
        if (! is_string($value) || trim($value) === '') {
            return null;
        }

        try {
            return CarbonImmutable::parse($value)->utc();
        } catch (\Throwable) {
            return null;
        }
    }

    private function normaliseId(mixed $value): ?string
    {
        return is_string($value) && trim($value) !== '' ? trim($value) : null;
    }

    private function normaliseString(mixed $value, int $limit): ?string
    {
        if (! is_string($value) || trim($value) === '') {
            return null;
        }

        return mb_substr(trim($value), 0, $limit);
    }
}
