/**
 * DO NOT EDIT - Auto-generated by Omnify.
 * @generated by omnify
 */
import type { Denomination, DenominationCreateFormState, DenominationUpdateFormState } from "./Denomination";

export interface DenominationFilters {
  page?: number;
  per_page?: number;
  search?: string;
  currency_code?: string;
  kind?: string;
  is_active?: boolean;
  with_trashed?: boolean;
  only_trashed?: boolean;
  sort?: string;
}

export interface DenominationLookupItem {
  id: string;
  name: string;
}

function toParams(filters: Record<string, any>): string {
  const p = new URLSearchParams();
  if (filters.page) p.set("page", String(filters.page));
  if (filters.per_page) p.set("per_page", String(filters.per_page));
  if (filters.search) p.set("search", filters.search);
  if (filters.currency_code) p.set("currency_code", filters.currency_code);
  if (filters.kind) p.set("kind", filters.kind);
  if (filters.is_active !== undefined) p.set("is_active", filters.is_active ? "1" : "0");
  if (filters.with_trashed) p.set("with_trashed", "1");
  if (filters.only_trashed) p.set("only_trashed", "1");
  if (filters.sort) p.set("sort", filters.sort);
  return p.toString();
}

// Factory — URL is injected by user-land, not hardcoded.
export function createDenominationBaseService(baseUrl: (slug: string, path?: string) => string) {
  return {
    list: (slug: string, filters: DenominationFilters = {}) =>
      apiFetch<PaginatedResponse<Denomination>>(
        `${baseUrl(slug)}?${toParams({ per_page: 25, ...filters })}`
      ),

    getById: (slug: string, id: string) =>
      apiFetch<{ data: Denomination }>(baseUrl(slug, `/${id}`)),

    lookup: (slug: string) =>
      apiFetch<{ data: DenominationLookupItem[] }>(baseUrl(slug, "/lookup")),

    create: (slug: string, data: DenominationCreateFormState) =>
      apiFetch<{ data: Denomination }>(baseUrl(slug), {
        method: "POST",
        body: JSON.stringify(data),
      }),

    update: (slug: string, id: string, data: Partial<DenominationUpdateFormState>) =>
      apiFetch<{ data: Denomination }>(baseUrl(slug, `/${id}`), {
        method: "PUT",
        body: JSON.stringify(data),
      }),

    delete: (slug: string, id: string) =>
      apiFetch<null>(baseUrl(slug, `/${id}`), { method: "DELETE" }),

    restore: (slug: string, id: string) =>
      apiFetch<{ data: Denomination }>(baseUrl(slug, `/${id}/restore`), {
        method: "POST",
      }),
  };
}

export type DenominationBaseServiceType = ReturnType<typeof createDenominationBaseService>;
