/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import type { Locale } from '../common';
import { buildI18nPayload, emptyLocaleMap } from '../payload-helpers';
import { z } from 'zod';
import type { DateTimeString } from '../common';
import { TaxClassification } from '../enum/TaxClassification';
import type { Brand } from './Brand';
import type { Organization } from './Organization';
import type { Product } from './Product';
import type { TaxTypeRate } from './TaxTypeRate';

/**
 * 税区分
 */
export interface TaxType {
  id: string;
  code: string;
  name: string;
  rate: number;
  classification?: TaxClassification | null;
  is_default: boolean;
  is_active: boolean;
  products?: Product[];
  rates?: TaxTypeRate[];
  organization_id: string;
  organization?: Organization;
  brand_id: string;
  brand?: Brand;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString | null;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for TaxType
 */
export const taxTypeI18n = {
  label: {"ja":"税区分","en":"Tax Type","vi":"Loại thuế"},
  fields: {
    code: {
      label: {"ja":"コード","en":"Code","vi":"Mã"},
      placeholder: {"ja":"コードを入力","en":"Enter Code","vi":"Nhập Mã"},
    },
    name: {
      label: {"ja":"名前","en":"Name","vi":"Tên"},
      placeholder: {"ja":"名前を入力","en":"Enter Name","vi":"Nhập Tên"},
    },
    rate: {
      label: {"ja":"税率 (%)","en":"Rate (%)","vi":"Thuế suất (%)"},
      placeholder: {"ja":"税率 (%)を入力","en":"Enter Rate (%)","vi":"Nhập Thuế suất (%)"},
    },
    classification: {
      label: {"ja":"課税区分","en":"Classification","vi":"Phân loại thuế"},
      placeholder: {"ja":"課税区分を入力","en":"Enter Classification","vi":"Nhập Phân loại thuế"},
    },
    is_default: {
      label: {"ja":"デフォルト","en":"Default","vi":"Mặc định"},
      placeholder: {"ja":"デフォルトを入力","en":"Enter Default","vi":"Nhập Mặc định"},
    },
    is_active: {
      label: {"ja":"有効","en":"Active","vi":"Hoạt động"},
      placeholder: {"ja":"有効を入力","en":"Enter Active","vi":"Nhập Hoạt động"},
    },
    products: {
      label: {"ja":"商品","en":"Products","vi":"Sản phẩm"},
      placeholder: {"ja":"商品を入力","en":"Enter Products","vi":"Nhập Sản phẩm"},
    },
    rates: {
      label: {"ja":"税率適用期間","en":"Rate Periods","vi":"Kỳ hiệu lực"},
      placeholder: {"ja":"税率適用期間を入力","en":"Enter Rate Periods","vi":"Nhập Kỳ hiệu lực"},
    },
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    brand: {
      label: {"ja":"ブランド","en":"Brand","vi":"Thương hiệu"},
      placeholder: {"ja":"ブランドを入力","en":"Enter Brand","vi":"Nhập Thương hiệu"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for TaxType */
export const baseTaxTypeSchemas = {
  code: z.string().min(1).max(50),
  name: z.string().min(1).max(100),
  rate: z.number(),
  classification: z.nativeEnum(TaxClassification).optional().nullable(),
  is_default: z.boolean(),
  is_active: z.boolean(),
} as const;

/** Create schema for TaxType */
export const baseTaxTypeCreateSchema = z.object({
  code: baseTaxTypeSchemas.code,
  name: baseTaxTypeSchemas.name,
  rate: baseTaxTypeSchemas.rate,
  classification: baseTaxTypeSchemas.classification,
  is_default: baseTaxTypeSchemas.is_default,
  is_active: baseTaxTypeSchemas.is_active,
  ja: z.object({
    name: z.string().max(100).optional().nullable(),
  }).optional(),
  en: z.object({
    name: z.string().max(100).optional().nullable(),
  }).optional(),
  vi: z.object({
    name: z.string().max(100).optional().nullable(),
  }).optional(),
});

/** Update schema for TaxType */
export const baseTaxTypeUpdateSchema = baseTaxTypeCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseTaxTypeCreate = z.infer<typeof baseTaxTypeCreateSchema>;
export type BaseTaxTypeUpdate = z.infer<typeof baseTaxTypeUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getTaxTypeLabel(locale: string): string {
  return taxTypeI18n.label[locale as keyof typeof taxTypeI18n.label] ?? taxTypeI18n.label['en'] ?? 'TaxType';
}

/** Get field label for a specific locale */
export function getTaxTypeFieldLabel(field: string, locale: string): string {
  const fields = taxTypeI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getTaxTypeFieldPlaceholder(field: string, locale: string): string {
  const fields = taxTypeI18n.fields as Record<string, { label: Record<string, string>; placeholder?: Record<string, string> }>;
  const fieldI18n = fields[field];
  if (!fieldI18n?.placeholder) return '';
  return fieldI18n.placeholder[locale] ?? fieldI18n.placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for TaxType.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const taxTypeMetadata = {
  modelName: "TaxType",
  table: "tax_types",

  fields: {
    code: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 50,
      },
      label: {
        ja: "コード",
        en: "Code",
        vi: "Mã",
      },
      placeholder: {
        ja: "コードを入力",
        en: "Enter Code",
        vi: "Nhập Mã",
      },
    },
    name: {
      type: "string",
      required: true,
      nullable: false,
      translatable: true,
      validation: {
        maxLength: 100,
      },
      label: {
        ja: "名前",
        en: "Name",
        vi: "Tên",
      },
      placeholder: {
        ja: "名前を入力",
        en: "Enter Name",
        vi: "Nhập Tên",
      },
    },
    rate: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "税率 (%)",
        en: "Rate (%)",
        vi: "Thuế suất (%)",
      },
      placeholder: {
        ja: "税率 (%)を入力",
        en: "Enter Rate (%)",
        vi: "Nhập Thuế suất (%)",
      },
    },
    classification: {
      type: "enum",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      enum: "TaxClassification",
      enumValues: ["taxable", "exempt", "out_of_scope", "zero_rated"] as const,
      label: {
        ja: "課税区分",
        en: "Classification",
        vi: "Phân loại thuế",
      },
      placeholder: {
        ja: "課税区分を入力",
        en: "Enter Classification",
        vi: "Nhập Phân loại thuế",
      },
    },
    is_default: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "デフォルト",
        en: "Default",
        vi: "Mặc định",
      },
      placeholder: {
        ja: "デフォルトを入力",
        en: "Enter Default",
        vi: "Nhập Mặc định",
      },
    },
    is_active: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "有効",
        en: "Active",
        vi: "Hoạt động",
      },
      placeholder: {
        ja: "有効を入力",
        en: "Enter Active",
        vi: "Nhập Hoạt động",
      },
    },
    organization_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    brand_id: {
      type: "uuid",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Brand",
        table: "brands",
        onDelete: "CASCADE",
      },
      label: {},
    },
  },

  translatableFields: ["name"] as const,
  requiredFields: ["code", "name", "rate", "is_default", "is_active", "organization_id", "brand_id"] as const,
  enumFields: ["classification"] as const,
  relationFields: ["organization_id", "brand_id"] as const,
} as const;

export type TaxTypeFieldName = keyof typeof taxTypeMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a TaxType. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface TaxTypeCreateFormState {
  code: string;
  name: Record<Locale, string>;
  rate: number;
  classification?: TaxClassification | null;
  is_default: boolean;
  is_active: boolean;
  organization_id: string;
  brand_id: string;
}

/** Form-state shape for updating a TaxType. Every field optional. */
export interface TaxTypeUpdateFormState {
  code?: string;
  name?: Record<Locale, string>;
  rate?: number;
  classification?: TaxClassification | null;
  is_default?: boolean;
  is_active?: boolean;
  organization_id?: string;
  brand_id?: string;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyTaxTypeCreateForm(): TaxTypeCreateFormState {
  return {
    code: '',
    name: emptyLocaleMap(),
    rate: 0,
    is_default: false,
    is_active: true,
    organization_id: '',
    brand_id: '',
  };
}

/** Convert create form state into the payload that baseTaxTypeCreateSchema accepts. */
export function buildTaxTypeCreatePayload(form: TaxTypeCreateFormState): BaseTaxTypeCreate {
  const payload: Record<string, unknown> = {
    code: form.code.trim(),
    name: (form.name["ja"] ?? '').trim(),
    rate: form.rate,
    classification: form.classification,
    is_default: form.is_default,
    is_active: form.is_active,
    organization_id: form.organization_id.trim(),
    brand_id: form.brand_id.trim(),
  };

  // Per-locale sub-objects (matches issue #53 wire shape).
  const i18n = buildI18nPayload({
    name: form.name,
  });
  Object.assign(payload, i18n);

  return payload as BaseTaxTypeCreate;
}

/** Convert update form state into the payload that baseTaxTypeUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildTaxTypeUpdatePayload(form: TaxTypeUpdateFormState): BaseTaxTypeUpdate {
  const payload: Record<string, unknown> = {};
  if (form.code !== undefined) {
    payload.code = form.code?.toString().trim() ?? null;
  }
  if (form.name !== undefined) {
    payload.name = (form.name["ja"] ?? '').trim();
  }
  if (form.rate !== undefined) {
    payload.rate = form.rate;
  }
  if (form.classification !== undefined) {
    payload.classification = form.classification;
  }
  if (form.is_default !== undefined) {
    payload.is_default = form.is_default;
  }
  if (form.is_active !== undefined) {
    payload.is_active = form.is_active;
  }
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id?.toString().trim() ?? null;
  }
  if (form.brand_id !== undefined) {
    payload.brand_id = form.brand_id?.toString().trim() ?? null;
  }

  // Per-locale sub-objects only for fields the user touched.
  const localeInput: Record<string, Record<string, string> | undefined> = {};
  if (form.name !== undefined) localeInput.name = form.name;
  Object.assign(payload, buildI18nPayload(localeInput));
  return payload as BaseTaxTypeUpdate;
}
