<?php

/**
 * plan-040 cluster-A [Arch] (A) — the schema-integrity changes shipped by
 * plan-040 must originate from Omnify YAML codegen, never from a hand-edit of
 * the generated migration.
 *
 * TESTS.md cluster A:
 *   "[Arch] (A) given the generated migrations dir, when the test runs, then
 *    no plan-040 task hand-edited migrations/omnify/ (schema diff originates
 *    from YAML)."
 *
 * Why this exists: the pre-commit hook (.githooks/pre-commit) only blocks
 * NEWLY ADDED hand-written migrations OUTSIDE database/migrations/omnify/. It
 * does NOT catch a hand-EDIT of an existing generated file inside that dir
 * (that folder is a blanket allow-list for the hook), and it does not run in
 * CI. Plan-040's cluster A landed exactly there — 10 generated alter_* files
 * dated 2000_02_20_* (per-org code uniques C5/M13, idempotent genealogy edge
 * H12, decimal scale L5). This arch test pins them to the Omnify codegen
 * marker so a later hand-edit is caught.
 *
 * NOTE: the folder legitimately also holds hand-authored "runtime" migrations
 * from other plans (e.g. till_tender_categories seeding), so this test is
 * deliberately scoped to the plan-040 cluster-A file set rather than the whole
 * directory.
 *
 * (Pure filesystem scan — no DB.)
 */

/** The 10 cluster-A schema-integrity migrations plan-040 generated. */
dataset('plan040_cluster_a_migrations', [
    // Table stems, not filenames. Plan-040 originally shipped ten `alter_*`
    // migrations; the #1217 flattening folded them into the `create_*` files,
    // so the columns — and the codegen markers this test cares about — now live
    // there. Addressing by stem also survives the next renumbering, which is
    // what broke the previous form.
    'create_materials_table',
    'create_stock_transactions_table',
    'create_material_batches_table',
    'create_disposal_records_table',
    'create_genealogy_links_table',
    'create_stock_alerts_table',
    'create_stock_counts_table',
    'create_stock_levels_table',
    'create_stock_movements_table',
    'create_stock_transfers_table',
]);

/**
 * Resolve a generated migration by its table stem. Named distinctly from the
 * sibling helper in Plan040ClusterARestrictArchTest because Pest loads every
 * test file into one global scope.
 */
function codegenMigrationPath(string $tableStem): ?string
{
    $matches = glob(database_path('migrations/omnify/*_'.$tableStem.'.php'));

    return count($matches) === 1 ? $matches[0] : null;
}

it('is generated codegen, not a hand-edit (carries the Omnify marker)', function (string $name) {
    $path = codegenMigrationPath($name);

    expect($path)->not->toBeNull("No generated migration matches *_{$name}.php");

    $head = (string) file_get_contents((string) $path, false, null, 0, 1024);

    expect(str_contains($head, '@generated by omnify'))
        ->toBeTrue(
            "{$name} lost its Omnify codegen marker — a plan-040 schema change was hand-edited "
            .'in migrations/omnify/. Edit the schema YAML and run `npm run omnify:gen` instead.'
        );
    expect(str_contains($head, 'DO NOT EDIT THIS FILE'))
        ->toBeTrue("{$name} lost the Omnify DO-NOT-EDIT banner — treat as a hand-edit.");
})->with('plan040_cluster_a_migrations');
