/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * テーブル状態
 */
export enum TableStatus {
  Free = 'free',
  Occupied = 'occupied',
  Reserved = 'reserved',
  Cleaning = 'cleaning',
  OutOfService = 'out_of_service',
}

/** All TableStatus values */
export const TableStatusValues = Object.values(TableStatus) as TableStatus[];

/** Type guard for TableStatus */
export function isTableStatus(value: unknown): value is TableStatus {
  return TableStatusValues.includes(value as TableStatus);
}

const tableStatusLabels: Partial<Record<TableStatus, Record<string, string>>> = {
  [TableStatus.Free]: { 'en': 'Free', 'ja': '空席', 'vi': 'Trống' },
  [TableStatus.Occupied]: { 'en': 'Occupied', 'ja': '使用中', 'vi': 'Đang phục vụ' },
  [TableStatus.Reserved]: { 'en': 'Reserved', 'ja': '予約済み', 'vi': 'Đã đặt trước' },
  [TableStatus.Cleaning]: { 'en': 'Cleaning', 'ja': '清掃中', 'vi': 'Đang dọn' },
  [TableStatus.OutOfService]: { 'en': 'Out of Service', 'ja': '利用不可', 'vi': 'Tạm ngưng' },
};

/** Get label for TableStatus value with locale support */
export function getTableStatusLabel(value: TableStatus, locale?: string): string {
  const labels = tableStatusLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for TableStatus value */
export function getTableStatusExtra(_value: TableStatus): Record<string, unknown> | undefined {
  return undefined;
}
