<?php

namespace App\Omnify\Modules\NotificationDelivery\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\NotificationRecipient;
use App\Omnify\Enums\NotificationChannelEnum;
use App\Omnify\Enums\NotificationDeliveryStatusEnum;
use App\Omnify\Modules\NotificationDelivery\Locales\NotificationDeliveryLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * NotificationDeliveryBaseModel
 *
 * @property int $notification_recipient_id
 * @property NotificationChannelEnum $channel
 * @property NotificationDeliveryStatusEnum $status
 * @property int|null $attempts
 * @property mixed|null $last_attempted_at
 * @property mixed|null $sent_at
 * @property mixed|null $delivered_at
 * @property mixed|null $failed_at
 * @property string|null $error
 * @property string|null $provider_ref
 */
class NotificationDeliveryBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;

    /**
     * The table associated with the model.
     */
    protected $table = 'notification_deliveries';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = NotificationDeliveryLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = NotificationDeliveryLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'notification_recipient_id',
        'channel',
        'status',
        'attempts',
        'last_attempted_at',
        'sent_at',
        'delivered_at',
        'failed_at',
        'error',
        'provider_ref',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'channel' => NotificationChannelEnum::class,
            'status' => NotificationDeliveryStatusEnum::class,
            'attempts' => 'integer',
            'last_attempted_at' => 'datetime',
            'sent_at' => 'datetime',
            'delivered_at' => 'datetime',
            'failed_at' => 'datetime',
        ];
    }

    /**
     * Get the notificationRecipient that owns this model.
     */
    public function notificationRecipient(): BelongsTo
    {
        return $this->belongsTo(NotificationRecipient::class, 'notification_recipient_id');
    }
}
