/**
 * ESLint flat config for godx-kiosk (Expo + React Native).
 *
 * Was missing entirely — 190+ source files shipped unlinted for the
 * lifetime of the repo. `eslint-config-expo` is the official Expo
 * recommendation; it pre-wires react/react-native/react-hooks +
 * TypeScript parser with the right globals (__DEV__, requestIdleCallback,
 * etc) and ignores Metro/Expo-managed artefacts.
 *
 * Local additions:
 *   - Ignore stitch/* design dumps (2.9 MB of Stitch-exported HTML)
 *     + src/types/models/base/* (omnify codegen — owned by the
 *     schema, not by hand-editing)
 *   - Warn instead of error on react-hooks/exhaustive-deps because
 *     several payment-flow useEffect calls deliberately omit deps
 *     to enforce single-shot semantics (see app/payment/card.tsx:87
 *     + qr.tsx:126 — both carry inline eslint-disable-next-line
 *     comments with rationale).
 */
const expoConfig = require("eslint-config-expo/flat");

module.exports = [
  // Apply Expo's recommended preset first.
  ...expoConfig,

  // Ignore patterns. flat-config requires this as its own block.
  {
    ignores: [
      "dist/",
      "build/",
      ".expo/",
      "android/",
      "ios/",
      // Stitch design dumps — generated HTML, not hand-edited
      "stitch/",
      // omnify codegen — owned by the schema, regenerated wholesale
      "src/types/models/base/",
      // rn-query-setup.ts sits beside base/ rather than inside it, but carries
      // the same "DO NOT EDIT - Auto-generated by Omnify" header. It contains
      // its own apiFetch implementation, so the no-restricted-globals rule
      // fires on it — and an inline disable there would be erased by the next
      // regen. Excluded at the config level instead, which is where a rule
      // about generated code belongs (#1259).
      "src/types/models/rn-query-setup.ts",
      // build artefacts
      "node_modules/",
      "*.config.js",
      "*.config.ts",
    ],
  },

  // Project-specific overrides.
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      // Several payment-flow useEffects deliberately run once on mount
      // to prevent duplicate payment_id creation. Each carries an
      // inline disable comment with rationale; demoting to warn keeps
      // the protection without forcing the comment in every case.
      // Raw fetch() bypasses the wrapper that stamps the device token and
      // Accept-Language, and that throws the shared error shape. The missing
      // Accept-Language has bitten twice already: the backend then returns
      // default-locale strings and Vietnamese users are quietly shown Japanese.
      // Every other app in the monorepo carries this rule; kiosk was the only
      // one without it — the same gap as the missing no-console rule below, and
      // in the same app (#1259).
      //
      // The wrapper itself and the pre-auth pairing call have nowhere else to
      // go; they carry inline disables naming the reason.
      "no-restricted-globals": [
        "error",
        {
          name: "fetch",
          message:
            "Use apiFetch from @/lib/api instead of raw fetch(). apiFetch centralises auth headers, Accept-Language, and the shared error shape.",
        },
      ],
      // No no-console rule existed at all — in the one app where the failure
      // actually happened. #1245 removed fourteen console.log calls that were
      // writing payment request bodies and raw QR tokens into production device
      // logs, but installed nothing to stop them returning. This is that
      // guard (#1259).
      //
      // warn/error stay allowed deliberately: #1245 kept console.error as a
      // breadcrumb in the device log for when Sentry cannot be reached. The one
      // sanctioned console.log lives in lib/dev-log.ts behind a DEV flag and
      // carries its own disable comment — one licensed door instead of an open
      // house.
      "no-console": ["error", { allow: ["warn", "error"] }],
      // Several payment-flow useEffects deliberately run once on mount
      // to prevent duplicate payment_id creation. Each carries an
      // inline disable comment with rationale; demoting to warn keeps
      // the protection without forcing the comment in every case.
      "react-hooks/exhaustive-deps": "warn",
      // RN style: prefer explicit anonymous functions for inline handlers
      "@typescript-eslint/no-explicit-any": "warn",
      // RN uses inline styles; turn off the warning for now.
      "react-native/no-inline-styles": "off",
      // React 19 hooks rules are stricter than the existing code's
      // patterns. Demoted to warn so the lint script LANDS as a
      // productivity gate without blocking on 24 pre-existing issues
      // (terminal-provider ref access in useEffect, idle-timer
      // setState in effect, etc). Future PRs see these as warnings
      // + can fix opportunistically. Tracked as follow-up cleanup.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/immutability": "warn",
      // Same posture for react/no-children-prop — codegen template
      // pattern in src/components/ui/* uses children prop.
      "react/no-children-prop": "warn",
      // Empty-interface warnings from the omnify model layer — those
      // files are ignored via the globalIgnore block anyway, but
      // demote for any remaining edge.
      "@typescript-eslint/no-empty-object-type": "warn",
    },
  },
];
