/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * デバイス状態
 */
export enum DeviceStatus {
  PendingActivation = 'pending_activation',
  Active = 'active',
  Inactive = 'inactive',
  Revoked = 'revoked',
}

/** All DeviceStatus values */
export const DeviceStatusValues = Object.values(DeviceStatus) as DeviceStatus[];

/** Type guard for DeviceStatus */
export function isDeviceStatus(value: unknown): value is DeviceStatus {
  return DeviceStatusValues.includes(value as DeviceStatus);
}

const deviceStatusLabels: Partial<Record<DeviceStatus, Record<string, string>>> = {
  [DeviceStatus.PendingActivation]: { 'en': 'Pending Activation', 'ja': 'アクティベーション待ち', 'vi': 'Chờ kích hoạt' },
  [DeviceStatus.Active]: { 'en': 'Active', 'ja': '有効', 'vi': 'Hoạt động' },
  [DeviceStatus.Inactive]: { 'en': 'Inactive', 'ja': '無効', 'vi': 'Tạm ngưng' },
  [DeviceStatus.Revoked]: { 'en': 'Revoked', 'ja': '取消済み', 'vi': 'Đã thu hồi' },
};

/** Get label for DeviceStatus value with locale support */
export function getDeviceStatusLabel(value: DeviceStatus, locale?: string): string {
  const labels = deviceStatusLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for DeviceStatus value */
export function getDeviceStatusExtra(_value: DeviceStatus): Record<string, unknown> | undefined {
  return undefined;
}
