/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 決済ゲートウェイ環境
 */
export enum PaymentGatewayEnvironment {
  Local = 'local',
  Sandbox = 'sandbox',
  Test = 'test',
  Live = 'live',
}

/** All PaymentGatewayEnvironment values */
export const PaymentGatewayEnvironmentValues = Object.values(PaymentGatewayEnvironment) as PaymentGatewayEnvironment[];

/** Type guard for PaymentGatewayEnvironment */
export function isPaymentGatewayEnvironment(value: unknown): value is PaymentGatewayEnvironment {
  return PaymentGatewayEnvironmentValues.includes(value as PaymentGatewayEnvironment);
}

const paymentGatewayEnvironmentLabels: Partial<Record<PaymentGatewayEnvironment, Record<string, string>>> = {
  [PaymentGatewayEnvironment.Local]: { 'en': 'Local', 'ja': 'ローカル', 'vi': 'Cục bộ' },
  [PaymentGatewayEnvironment.Sandbox]: { 'en': 'Sandbox', 'ja': 'サンドボックス', 'vi': 'Sandbox' },
  [PaymentGatewayEnvironment.Test]: { 'en': 'Test', 'ja': 'テスト', 'vi': 'Kiểm thử' },
  [PaymentGatewayEnvironment.Live]: { 'en': 'Live', 'ja': '本番', 'vi': 'Chính thức' },
};

/** Get label for PaymentGatewayEnvironment value with locale support */
export function getPaymentGatewayEnvironmentLabel(value: PaymentGatewayEnvironment, locale?: string): string {
  const labels = paymentGatewayEnvironmentLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for PaymentGatewayEnvironment value */
export function getPaymentGatewayEnvironmentExtra(_value: PaymentGatewayEnvironment): Record<string, unknown> | undefined {
  return undefined;
}
