/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

/**
 * 現金カウント段階
 */
export enum TillCountPhase {
  Opening = 'opening',
  Closing = 'closing',
}

/** All TillCountPhase values */
export const TillCountPhaseValues = Object.values(TillCountPhase) as TillCountPhase[];

/** Type guard for TillCountPhase */
export function isTillCountPhase(value: unknown): value is TillCountPhase {
  return TillCountPhaseValues.includes(value as TillCountPhase);
}

const tillCountPhaseLabels: Partial<Record<TillCountPhase, Record<string, string>>> = {
  [TillCountPhase.Opening]: { 'en': 'Opening', 'ja': '開始時', 'vi': 'Đầu ca' },
  [TillCountPhase.Closing]: { 'en': 'Closing', 'ja': '締め時', 'vi': 'Cuối ca' },
};

/** Get label for TillCountPhase value with locale support */
export function getTillCountPhaseLabel(value: TillCountPhase, locale?: string): string {
  const labels = tillCountPhaseLabels[value];
  if (!labels) return value;
  if (locale && labels[locale]) return labels[locale];
  return labels['ja'] ?? labels['en'] ?? Object.values(labels)[0] ?? value;
}

/** Get extra metadata for TillCountPhase value */
export function getTillCountPhaseExtra(_value: TillCountPhase): Record<string, unknown> | undefined {
  return undefined;
}
