<?php

namespace App\Omnify\Modules\PaymentGatewaySecretVersion\Locales;

/**
 * Localized display names for PaymentGatewaySecretVersion.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class PaymentGatewaySecretVersionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Payment Gateway Secret Version',
        'ja' => '決済ゲートウェイシークレットバージョン',
        'vi' => 'Phiên bản bí mật cổng thanh toán',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'provider_code' => [
            'en' => 'Provider',
            'ja' => 'プロバイダー',
            'vi' => 'Nhà cung cấp',
        ],
        'environment' => [
            'en' => 'Environment',
            'ja' => '環境',
            'vi' => 'Môi trường',
        ],
        'purpose' => [
            'en' => 'Purpose',
            'ja' => '用途',
            'vi' => 'Mục đích',
        ],
        'version' => [
            'en' => 'Version',
            'ja' => 'バージョン',
            'vi' => 'Phiên bản',
        ],
        'key_id' => [
            'en' => 'Master Key ID',
            'ja' => 'マスターキーID',
            'vi' => 'ID khóa chính',
        ],
        'nonce' => [
            'en' => 'Nonce',
            'ja' => 'ノンス',
            'vi' => 'Nonce',
        ],
        'ciphertext' => [
            'en' => 'Ciphertext',
            'ja' => '暗号文',
            'vi' => 'Bản mã',
        ],
        'fingerprint' => [
            'en' => 'Keyed Fingerprint',
            'ja' => 'キー付きフィンガープリント',
            'vi' => 'Dấu vân tay có khóa',
        ],
        'state' => [
            'en' => 'State',
            'ja' => '状態',
            'vi' => 'Trạng thái',
        ],
        'valid_until' => [
            'en' => 'Valid Until',
            'ja' => '有効期限',
            'vi' => 'Có hiệu lực đến',
        ],
        'created_at' => [
            'en' => 'Created At',
            'ja' => '作成日時',
            'vi' => 'Tạo lúc',
        ],
        'revoked_at' => [
            'en' => 'Revoked At',
            'ja' => '失効日時',
            'vi' => 'Thu hồi lúc',
        ],
    ];
}
