<?php

namespace App\Omnify\Modules\FloatingSectionProduct\Locales;

/**
 * Localized display names for FloatingSectionProduct.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class FloatingSectionProductLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Floating Section Product',
        'ja' => 'フローティングセクション商品',
        'vi' => 'Sản phẩm trong khung giờ ưu đãi',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'display_order' => [
            'en' => 'Display Order',
            'ja' => '表示順序',
            'vi' => 'Thứ tự hiển thị',
        ],
    ];
}
