<?php

namespace App\Omnify\Modules\MenuPromotion\Locales;

/**
 * Localized display names for MenuPromotion.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class MenuPromotionLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Menu Promotion',
        'ja' => 'メニュープロモーション',
        'vi' => 'Khuyến mãi menu',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'name' => [
            'en' => 'Name',
            'ja' => '名称',
            'vi' => 'Tên',
        ],
        'description' => [
            'en' => 'Description',
            'ja' => '説明',
            'vi' => 'Mô tả',
        ],
        'discount_percent' => [
            'en' => 'Discount Percent',
            'ja' => '割引率',
            'vi' => 'Phần trăm giảm',
        ],
        'applies_to' => [
            'en' => 'Applies To',
            'ja' => '適用範囲',
            'vi' => 'Phạm vi áp dụng',
        ],
        'daily_time_from' => [
            'en' => 'Daily Time From',
            'ja' => '日次開始時刻',
            'vi' => 'Giờ bắt đầu trong ngày',
        ],
        'daily_time_to' => [
            'en' => 'Daily Time To',
            'ja' => '日次終了時刻',
            'vi' => 'Giờ kết thúc trong ngày',
        ],
        'weekdays' => [
            'en' => 'Weekdays',
            'ja' => '曜日',
            'vi' => 'Ngày trong tuần',
        ],
        'valid_from' => [
            'en' => 'Valid From',
            'ja' => '有効開始',
            'vi' => 'Bắt đầu',
        ],
        'valid_until' => [
            'en' => 'Valid Until',
            'ja' => '有効終了',
            'vi' => 'Kết thúc',
        ],
        'stacking_mode' => [
            'en' => 'Stacking Mode',
            'ja' => 'スタッキングモード',
            'vi' => 'Chế độ cộng dồn',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
    ];
}
