<?php

namespace App\Omnify\Modules\CashDeviceErrorEvent\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\BranchResource;
use App\Http\Resources\CashDeviceTransactionResource;
use App\Http\Resources\OrganizationResource;
use App\Http\Resources\PeripheralDeviceResource;
use App\Http\Resources\TillSessionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CashDeviceErrorEventResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'peripheral_device_id' => $this->peripheral_device_id,
            'peripheralDevice' => $this->whenLoaded('peripheralDevice', fn () => new PeripheralDeviceResource($this->peripheralDevice)),
            'error_title' => $this->error_title,
            'error_group' => $this->error_group,
            'occurred_at' => $this->occurred_at?->toISOString(),
            'cleared_at' => $this->cleared_at?->toISOString(),
            'cash_device_transaction_id' => $this->cash_device_transaction_id,
            'cashDeviceTransaction' => $this->whenLoaded('cashDeviceTransaction', fn () => new CashDeviceTransactionResource($this->cashDeviceTransaction)),
            'till_session_id' => $this->till_session_id,
            'tillSession' => $this->whenLoaded('tillSession', fn () => new TillSessionResource($this->tillSession)),
            'branch_id' => $this->branch_id,
            'branch' => $this->whenLoaded('branch', fn () => new BranchResource($this->branch)),
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
