-- Code generated by omnify. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS brands (
    id TEXT PRIMARY KEY,
    console_brand_id TEXT NOT NULL UNIQUE,
    console_organization_id TEXT NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    description TEXT,
    logo_url TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    primary_color TEXT,
    secondary_color TEXT,
    accent_color TEXT,
    text_color TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now')),
    deleted_at TEXT
);
