<?php

namespace App\Omnify\Modules\DevicePaymentOption\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\BranchResource;
use App\Http\Resources\DeviceResource;
use App\Http\Resources\OrganizationResource;
use App\Http\Resources\ShopPaymentOptionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class DevicePaymentOptionResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'branch_id' => $this->branch_id,
            'branch' => $this->whenLoaded('branch', fn () => new BranchResource($this->branch)),
            'device_id' => $this->device_id,
            'device' => $this->whenLoaded('device', fn () => new DeviceResource($this->device)),
            'shop_payment_option_id' => $this->shop_payment_option_id,
            'shopPaymentOption' => $this->whenLoaded('shopPaymentOption', fn () => new ShopPaymentOptionResource($this->shopPaymentOption)),
            'preference' => $this->preference,
            'change_reason' => $this->change_reason,
            'version' => $this->version,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
