<?php

namespace App\Omnify\Modules\OrderCondition\Models;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\OrderCondition\Locales\OrderConditionLocales;
use App\Omnify\Shared\Models\BaseModel;
use App\Omnify\Traits\HasLocalizedDisplayName;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

/**
 * OrderConditionBaseModel
 *
 * @property string $conditionable_type
 * @property string $conditionable_id
 * @property string $type
 * @property string|null $source
 * @property string $label
 * @property float|null $rate
 * @property float $amount
 * @property float|null $taxable_base
 * @property string $currency_code
 * @property array|null $meta
 */
class OrderConditionBaseModel extends BaseModel
{
    use HasLocalizedDisplayName;
    use HasUuids;

    /**
     * The table associated with the model.
     */
    protected $table = 'order_conditions';

    /**
     * The primary key for the model.
     */
    protected $primaryKey = 'id';

    /**
     * The type of the primary key.
     */
    protected $keyType = 'string';

    /**
     * Indicates if the IDs are auto-incrementing.
     */
    public $incrementing = false;

    /**
     * Indicates if the model should be timestamped.
     */
    public $timestamps = true;

    /**
     * Localized display names for this model.
     *
     * @var array<string, string>
     */
    protected static array $localizedDisplayNames = OrderConditionLocales::DISPLAY_NAMES;

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    protected static array $localizedPropertyDisplayNames = OrderConditionLocales::PROPERTY_DISPLAY_NAMES;

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        'conditionable_type',
        'conditionable_id',
        'type',
        'source',
        'label',
        'rate',
        'amount',
        'taxable_base',
        'currency_code',
        'meta',
    ];

    /**
     * The attributes that should be hidden for serialization.
     */
    protected $hidden = [
    ];

    /**
     * The accessors to append to the model's array form.
     */
    protected $appends = [
    ];

    /**
     * Get the attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'rate' => 'decimal:2',
            'amount' => 'decimal:2',
            'taxable_base' => 'decimal:2',
            'meta' => 'array',
        ];
    }
}
