<?php

namespace App\Omnify\Modules\ShopPaymentOption\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\BranchResource;
use App\Http\Resources\BrandResource;
use App\Http\Resources\OrganizationResource;
use App\Http\Resources\PaymentGatewayConnectionResource;
use App\Http\Resources\PaymentGatewayOptionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class ShopPaymentOptionResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'organization_id' => $this->organization_id,
            'organization' => $this->whenLoaded('organization', fn () => new OrganizationResource($this->organization)),
            'brand_id' => $this->brand_id,
            'brand' => $this->whenLoaded('brand', fn () => new BrandResource($this->brand)),
            'branch_id' => $this->branch_id,
            'branch' => $this->whenLoaded('branch', fn () => new BranchResource($this->branch)),
            'option_id' => $this->option_id,
            'option' => $this->whenLoaded('option', fn () => new PaymentGatewayOptionResource($this->option)),
            'connection_id' => $this->connection_id,
            'connection' => $this->whenLoaded('connection', fn () => new PaymentGatewayConnectionResource($this->connection)),
            'preference' => $this->preference,
            'change_reason' => $this->change_reason,
            'version' => $this->version,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
