<?php

namespace App\Omnify\Modules\ShopPaymentOption\Requests;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Omnify\Modules\ShopPaymentOption\Locales\ShopPaymentOptionLocales;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class ShopPaymentOptionStoreRequestBase extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     * Override this method in the concrete request class to add authorization logic.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return $this->schemaRules();
    }

    /**
     * Get custom attributes for validator errors.
     *
     * @return array<string, string>
     */
    public function attributes(): array
    {
        return $this->schemaAttributes();
    }

    /**
     * Get the schema-defined validation rules.
     *
     * @return array<string, array>
     */
    protected function schemaRules(): array
    {
        return [
            'organization_id' => ['required', 'uuid', 'exists:organizations,id'],
            'brand_id' => ['required', 'uuid', 'exists:brands,id'],
            'branch_id' => ['required', 'uuid', 'exists:branches,id'],
            'option_id' => ['required', 'uuid', 'exists:payment_gateway_options,id'],
            'connection_id' => ['nullable', 'uuid', 'exists:payment_gateway_connections,id'],
            'preference' => ['required', 'string'],
            'change_reason' => ['nullable', 'string', 'max:500'],
            'version' => ['required', 'integer', 'min:1'],
        ];
    }

    /**
     * Get custom attributes for validator errors.
     * Resolves display names from Locales using the current app locale.
     *
     * @return array<string, string>
     */
    protected function schemaAttributes(): array
    {
        $locale = app()->getLocale();
        $fallback = config('app.fallback_locale', 'en');
        $propertyNames = ShopPaymentOptionLocales::PROPERTY_DISPLAY_NAMES;
        $attributes = [];

        $keys = [
            'organization_id',
            'brand_id',
            'branch_id',
            'option_id',
            'connection_id',
            'preference',
            'change_reason',
            'version',
        ];

        foreach ($keys as $key) {
            $names = $propertyNames[$key] ?? [];
            $attributes[$key] = $names[$locale] ?? $names[$fallback] ?? $names[array_key_first($names) ?? 'en'] ?? $key;
        }

        return $attributes;
    }
}
