<?php

namespace App\Omnify\Traits;

/**
 * Trait for models with polymorphic file attachments.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Models\File;
use App\Omnify\Enums\FileStatusEnum;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Facades\DB;

trait HasFiles
{
    /**
     * Get all files attached to this model.
     */
    public function files(): MorphMany
    {
        return $this->morphMany(File::class, 'fileable');
    }

    /**
     * Get files in a specific collection.
     */
    public function filesInCollection(string $collection): MorphMany
    {
        return $this->files()->where('collection', $collection);
    }

    /**
     * Get all permanent files.
     */
    public function permanentFiles(): MorphMany
    {
        return $this->files()->where('status', FileStatusEnum::Permanent);
    }

    /**
     * Attach files by IDs to a collection, making them permanent.
     *
     * @param  array<string>  $fileIds
     */
    public function attachFiles(array $fileIds, string $collection = 'default', int $startOrder = 0): void
    {
        if (empty($fileIds)) {
            return;
        }

        File::whereIn('id', $fileIds)->update([
            'fileable_type' => $this->getMorphClass(),
            'fileable_id' => $this->getKey(),
            'collection' => $collection,
            'status' => FileStatusEnum::Permanent,
            'expires_at' => null,
            'sort_order' => DB::raw('sort_order + '.$startOrder),
        ]);
    }

    /**
     * Sync files for a collection (detach old, attach new).
     *
     * @param  array<string>  $fileIds
     */
    public function syncFiles(array $fileIds, string $collection = 'default'): void
    {
        // Soft-delete files no longer in the list
        $this->filesInCollection($collection)
            ->whereNotIn('id', $fileIds)
            ->delete();

        // Attach new files
        $this->attachFiles($fileIds, $collection);

        // Update sort order based on array position
        foreach ($fileIds as $index => $id) {
            File::where('id', $id)->update(['sort_order' => $index]);
        }
    }
}
