/**
 * ⚠️ DO NOT EDIT THIS FILE! ⚠️
 * このファイルを編集しないでください！
 *
 * Auto-generated by omnify-ts from schemas.json.
 * Any manual changes will be OVERWRITTEN on next generation.
 */

import type { Locale } from '../common';
import { buildI18nPayload, emptyLocaleMap } from '../payload-helpers';
import { z } from 'zod';
import type { DateTimeString } from '../common';
import type { MenuProduct } from './MenuProduct';
import type { MenuSection } from './MenuSection';

/**
 * メニュー
 */
export interface Menu {
  id: string;
  name: string;
  description?: string;
  valid_from?: DateTimeString;
  valid_to?: DateTimeString;
  priority: number;
  status: 'Draft' | 'Pending' | 'Approved' | 'Active' | 'Inactive' | 'Rejected';
  rejection_reason?: string;
  created_by_id?: string;
  approved_by_id?: string;
  approved_at?: DateTimeString;
  rejected_by_id?: string;
  rejected_at?: DateTimeString;
  is_master: boolean;
  last_synced_at?: DateTimeString;
  menuProducts?: MenuProduct[];
  menuSections?: MenuSection[];
  masterMenu_id?: string;
  masterMenu?: Menu | null;
  clonedMenus?: Menu[];
  organization_id: number;
  organization?: Organization;
  brand_id: number;
  brand?: Brand;
  branch_id?: number;
  branch?: Branch | null;
  created_at?: DateTimeString;
  updated_at?: DateTimeString;
  deleted_at?: DateTimeString;
}

// ============================================================================
// I18n (Internationalization)
// ============================================================================

/**
 * Unified i18n object for Menu
 */
export const menuI18n = {
  label: {"ja":"メニュー","en":"Menu","vi":"Menu"},
  fields: {
    name: {
      label: {"ja":"メニュー名","en":"Menu Name","vi":"Tên Menu"},
      placeholder: {"ja":"メニュー名を入力","en":"Enter Menu Name","vi":"Nhập Tên Menu"},
    },
    description: {
      label: {"ja":"説明","en":"Description","vi":"Mô tả"},
      placeholder: {"ja":"説明を入力","en":"Enter Description","vi":"Nhập Mô tả"},
    },
    valid_from: {
      label: {"ja":"有効開始日","en":"Valid From","vi":"Hiệu lực từ"},
      placeholder: {"ja":"有効開始日を入力","en":"Enter Valid From","vi":"Nhập Hiệu lực từ"},
    },
    valid_to: {
      label: {"ja":"有効終了日","en":"Valid To","vi":"Hiệu lực đến"},
      placeholder: {"ja":"有効終了日を入力","en":"Enter Valid To","vi":"Nhập Hiệu lực đến"},
    },
    priority: {
      label: {"ja":"優先度","en":"Priority","vi":"Độ ưu tiên"},
      placeholder: {"ja":"優先度を入力","en":"Enter Priority","vi":"Nhập Độ ưu tiên"},
    },
    status: {
      label: {"ja":"ステータス","en":"Status","vi":"Trạng thái"},
      placeholder: {"ja":"ステータスを入力","en":"Enter Status","vi":"Nhập Trạng thái"},
    },
    rejection_reason: {
      label: {"ja":"却下理由","en":"Rejection Reason","vi":"Lý do từ chối"},
      placeholder: {"ja":"却下理由を入力","en":"Enter Rejection Reason","vi":"Nhập Lý do từ chối"},
    },
    created_by_id: {
      label: {"ja":"作成者","en":"Created By","vi":"Người tạo"},
      placeholder: {"ja":"作成者を入力","en":"Enter Created By","vi":"Nhập Người tạo"},
    },
    approved_by_id: {
      label: {"ja":"承認者","en":"Approved By","vi":"Người duyệt"},
      placeholder: {"ja":"承認者を入力","en":"Enter Approved By","vi":"Nhập Người duyệt"},
    },
    approved_at: {
      label: {"ja":"承認日時","en":"Approved At","vi":"Thời gian duyệt"},
      placeholder: {"ja":"承認日時を入力","en":"Enter Approved At","vi":"Nhập Thời gian duyệt"},
    },
    rejected_by_id: {
      label: {"ja":"却下者","en":"Rejected By","vi":"Người từ chối"},
      placeholder: {"ja":"却下者を入力","en":"Enter Rejected By","vi":"Nhập Người từ chối"},
    },
    rejected_at: {
      label: {"ja":"却下日時","en":"Rejected At","vi":"Thời gian từ chối"},
      placeholder: {"ja":"却下日時を入力","en":"Enter Rejected At","vi":"Nhập Thời gian từ chối"},
    },
    is_master: {
      label: {"ja":"マスターメニュー","en":"Is Master Menu","vi":"Menu gốc"},
      placeholder: {"ja":"マスターメニューを入力","en":"Enter Is Master Menu","vi":"Nhập Menu gốc"},
    },
    last_synced_at: {
      label: {"ja":"最終同期日時","en":"Last Synced At","vi":"Đồng bộ lần cuối"},
      placeholder: {"ja":"最終同期日時を入力","en":"Enter Last Synced At","vi":"Nhập Đồng bộ lần cuối"},
    },
    menu_products: {
      label: {"ja":"メニュー商品","en":"Menu Products","vi":"Các sản phẩm trong menu"},
      placeholder: {"ja":"メニュー商品を入力","en":"Enter Menu Products","vi":"Nhập Các sản phẩm trong menu"},
    },
    menu_sections: {
      label: {"ja":"メニューセクション","en":"Menu Sections","vi":"Các nhóm danh mục"},
      placeholder: {"ja":"メニューセクションを入力","en":"Enter Menu Sections","vi":"Nhập Các nhóm danh mục"},
    },
    master_menu: {
      label: {"ja":"マスターメニュー","en":"Master Menu","vi":"Menu gốc"},
      placeholder: {"ja":"マスターメニューを入力","en":"Enter Master Menu","vi":"Nhập Menu gốc"},
    },
    cloned_menus: {
      label: {"ja":"クローンメニュー","en":"Cloned Menus","vi":"Các menu đã clone"},
      placeholder: {"ja":"クローンメニューを入力","en":"Enter Cloned Menus","vi":"Nhập Các menu đã clone"},
    },
    organization: {
      label: {"ja":"組織","en":"Organization","vi":"Tổ chức"},
      placeholder: {"ja":"組織を入力","en":"Enter Organization","vi":"Nhập Tổ chức"},
    },
    brand: {
      label: {"ja":"ブランド","en":"Brand","vi":"Thương hiệu"},
      placeholder: {"ja":"ブランドを入力","en":"Enter Brand","vi":"Nhập Thương hiệu"},
    },
    branch: {
      label: {"ja":"店舗","en":"Branch","vi":"Chi nhánh"},
      placeholder: {"ja":"店舗を入力","en":"Enter Branch","vi":"Nhập Chi nhánh"},
    },
  },
} as const;

// ============================================================================
// Zod Schemas
// ============================================================================

/** Field schemas for Menu */
export const baseMenuSchemas = {
  name: z.string().min(1).max(255),
  description: z.string().optional().nullable(),
  valid_from: z.string().datetime({ offset: true }).optional().nullable(),
  valid_to: z.string().datetime({ offset: true }).optional().nullable(),
  priority: z.number().int(),
  status: z.enum(['Draft', 'Pending', 'Approved', 'Active', 'Inactive', 'Rejected']),
  rejection_reason: z.string().optional().nullable(),
  created_by_id: z.string().optional().nullable(),
  approved_by_id: z.string().optional().nullable(),
  approved_at: z.string().datetime({ offset: true }).optional().nullable(),
  rejected_by_id: z.string().optional().nullable(),
  rejected_at: z.string().datetime({ offset: true }).optional().nullable(),
  is_master: z.boolean(),
  last_synced_at: z.string().datetime({ offset: true }).optional().nullable(),
} as const;

/** Create schema for Menu */
export const baseMenuCreateSchema = z.object({
  name: baseMenuSchemas.name,
  description: baseMenuSchemas.description,
  valid_from: baseMenuSchemas.valid_from,
  valid_to: baseMenuSchemas.valid_to,
  priority: baseMenuSchemas.priority,
  status: baseMenuSchemas.status,
  rejection_reason: baseMenuSchemas.rejection_reason,
  created_by_id: baseMenuSchemas.created_by_id,
  approved_by_id: baseMenuSchemas.approved_by_id,
  approved_at: baseMenuSchemas.approved_at,
  rejected_by_id: baseMenuSchemas.rejected_by_id,
  rejected_at: baseMenuSchemas.rejected_at,
  is_master: baseMenuSchemas.is_master,
  last_synced_at: baseMenuSchemas.last_synced_at,
});

/** Update schema for Menu */
export const baseMenuUpdateSchema = baseMenuCreateSchema.partial();

// ============================================================================
// Inferred Types
// ============================================================================

export type BaseMenuCreate = z.infer<typeof baseMenuCreateSchema>;
export type BaseMenuUpdate = z.infer<typeof baseMenuUpdateSchema>;

// ============================================================================
// I18n Helper Functions
// ============================================================================

/** Get model label for a specific locale */
export function getMenuLabel(locale: string): string {
  return menuI18n.label[locale as keyof typeof menuI18n.label] ?? menuI18n.label['en'] ?? 'Menu';
}

/** Get field label for a specific locale */
export function getMenuFieldLabel(field: string, locale: string): string {
  const fieldI18n = menuI18n.fields[field as keyof typeof menuI18n.fields];
  if (!fieldI18n) return field;
  return fieldI18n.label[locale as keyof typeof fieldI18n.label] ?? fieldI18n.label['en'] ?? field;
}

/** Get field placeholder for a specific locale */
export function getMenuFieldPlaceholder(field: string, locale: string): string {
  const fieldI18n = menuI18n.fields[field as keyof typeof menuI18n.fields];
  if (!fieldI18n || !('placeholder' in fieldI18n)) return '';
  const placeholder = fieldI18n.placeholder as Record<string, string>;
  return placeholder[locale] ?? placeholder['en'] ?? '';
}
// ============================================================================
// Form Field Metadata (issue #54)
// ============================================================================

/**
 * Form field metadata for Menu.
 *
 * Single source of truth for downstream tools (form runners, stories,
 * smoke tests, headless validation). Includes per-field type taxonomy,
 * validation rules, translatable / required / nullable flags, enum value
 * lists, relation pointers, and i18n labels — all flat, all in one const.
 */
export const menuMetadata = {
  modelName: "Menu",
  table: "menus",

  fields: {
    name: {
      type: "string",
      required: true,
      nullable: false,
      translatable: false,
      validation: {
        maxLength: 255,
      },
      label: {
        ja: "メニュー名",
        en: "Menu Name",
        vi: "Tên Menu",
      },
      placeholder: {
        ja: "メニュー名を入力",
        en: "Enter Menu Name",
        vi: "Nhập Tên Menu",
      },
      description: {
        ja: "メニューの表示名",
        en: "Display name for the menu",
        vi: "Tên hiển thị của menu",
      },
    },
    description: {
      type: "text",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "説明",
        en: "Description",
        vi: "Mô tả",
      },
      placeholder: {
        ja: "説明を入力",
        en: "Enter Description",
        vi: "Nhập Mô tả",
      },
      description: {
        ja: "オプションの説明やメモ",
        en: "Optional description or notes",
        vi: "Mô tả hoặc ghi chú",
      },
    },
    valid_from: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "有効開始日",
        en: "Valid From",
        vi: "Hiệu lực từ",
      },
      placeholder: {
        ja: "有効開始日を入力",
        en: "Enter Valid From",
        vi: "Nhập Hiệu lực từ",
      },
      description: {
        ja: "メニュー有効期間の開始日（null = 制限なし）",
        en: "Start date of menu validity (null = no start limit)",
        vi: "Ngày bắt đầu hiệu lực (null = không giới hạn)",
      },
    },
    valid_to: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "有効終了日",
        en: "Valid To",
        vi: "Hiệu lực đến",
      },
      placeholder: {
        ja: "有効終了日を入力",
        en: "Enter Valid To",
        vi: "Nhập Hiệu lực đến",
      },
      description: {
        ja: "メニュー有効期間の終了日（null = 制限なし）",
        en: "End date of menu validity (null = no end limit)",
        vi: "Ngày kết thúc hiệu lực (null = không giới hạn)",
      },
    },
    priority: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "優先度",
        en: "Priority",
        vi: "Độ ưu tiên",
      },
      placeholder: {
        ja: "優先度を入力",
        en: "Enter Priority",
        vi: "Nhập Độ ưu tiên",
      },
      description: {
        ja: "店舗内の優先度（小さいほど優先）。店舗内でユニークでなければなりません。",
        en: "Priority in branch (lower number = higher priority). MUST be unique per branch.",
        vi: "Độ ưu tiên trong branch (số nhỏ = ưu tiên cao). PHẢI duy nhất trong branch.",
      },
    },
    status: {
      type: "enum",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      enumValues: ["Draft", "Pending", "Approved", "Active", "Inactive", "Rejected"] as const,
      label: {
        ja: "ステータス",
        en: "Status",
        vi: "Trạng thái",
      },
      placeholder: {
        ja: "ステータスを入力",
        en: "Enter Status",
        vi: "Nhập Trạng thái",
      },
      description: {
        ja: "承認ワークフローの現在のステータス",
        en: "Current status in approval workflow",
        vi: "Trạng thái hiện tại trong quy trình duyệt",
      },
    },
    rejection_reason: {
      type: "text",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "却下理由",
        en: "Rejection Reason",
        vi: "Lý do từ chối",
      },
      placeholder: {
        ja: "却下理由を入力",
        en: "Enter Rejection Reason",
        vi: "Nhập Lý do từ chối",
      },
      description: {
        ja: "却下の理由（ステータス = 却下の場合）",
        en: "Reason for rejection (when status = Rejected)",
        vi: "Lý do từ chối (khi status = Rejected)",
      },
    },
    created_by_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "作成者",
        en: "Created By",
        vi: "Người tạo",
      },
      placeholder: {
        ja: "作成者を入力",
        en: "Enter Created By",
        vi: "Nhập Người tạo",
      },
    },
    approved_by_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "承認者",
        en: "Approved By",
        vi: "Người duyệt",
      },
      placeholder: {
        ja: "承認者を入力",
        en: "Enter Approved By",
        vi: "Nhập Người duyệt",
      },
    },
    approved_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "承認日時",
        en: "Approved At",
        vi: "Thời gian duyệt",
      },
      placeholder: {
        ja: "承認日時を入力",
        en: "Enter Approved At",
        vi: "Nhập Thời gian duyệt",
      },
    },
    rejected_by_id: {
      type: "string",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "却下者",
        en: "Rejected By",
        vi: "Người từ chối",
      },
      placeholder: {
        ja: "却下者を入力",
        en: "Enter Rejected By",
        vi: "Nhập Người từ chối",
      },
    },
    rejected_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "却下日時",
        en: "Rejected At",
        vi: "Thời gian từ chối",
      },
      placeholder: {
        ja: "却下日時を入力",
        en: "Enter Rejected At",
        vi: "Nhập Thời gian từ chối",
      },
    },
    is_master: {
      type: "boolean",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      label: {
        ja: "マスターメニュー",
        en: "Is Master Menu",
        vi: "Menu gốc",
      },
      placeholder: {
        ja: "マスターメニューを入力",
        en: "Enter Is Master Menu",
        vi: "Nhập Menu gốc",
      },
      description: {
        ja: "マスター/テンプレートメニューかどうか",
        en: "Whether this is a master/template menu",
        vi: "Đây có phải menu gốc/mẫu không",
      },
    },
    last_synced_at: {
      type: "datetime",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      label: {
        ja: "最終同期日時",
        en: "Last Synced At",
        vi: "Đồng bộ lần cuối",
      },
      placeholder: {
        ja: "最終同期日時を入力",
        en: "Enter Last Synced At",
        vi: "Nhập Đồng bộ lần cuối",
      },
      description: {
        ja: "最後にマスターと同期した時間",
        en: "Last time this menu was synced with master",
        vi: "Thời gian đồng bộ với master gần nhất",
      },
    },
    master_menu_id: {
      type: "uuid",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Menu",
        table: "menus",
        onDelete: undefined,
      },
      label: {},
    },
    organization_id: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Organization",
        table: "organizations",
        onDelete: "CASCADE",
      },
      label: {},
    },
    brand_id: {
      type: "number",
      required: true,
      nullable: false,
      translatable: false,
      validation: {},
      relation: {
        model: "Brand",
        table: "brands",
        onDelete: "CASCADE",
      },
      label: {},
    },
    branch_id: {
      type: "number",
      required: false,
      nullable: true,
      translatable: false,
      validation: {},
      relation: {
        model: "Branch",
        table: "branchs",
        onDelete: "CASCADE",
      },
      label: {},
    },
  },

  translatableFields: [] as const,
  requiredFields: ["name", "priority", "status", "is_master", "organization_id", "brand_id"] as const,
  enumFields: ["status"] as const,
  relationFields: ["master_menu_id", "organization_id", "brand_id", "branch_id"] as const,
} as const;

export type MenuFieldName = keyof typeof menuMetadata.fields;

// ============================================================================
// Form State + Payload Builders (issue #55)
// ============================================================================

/** Form-state shape for creating a Menu. Translatable fields are
 *  flat per-locale maps; the builder collapses them into the wire shape. */
export interface MenuCreateFormState {
  name: string;
  description?: string | null;
  valid_from?: string | null;
  valid_to?: string | null;
  priority: number;
  status: 'Draft' | 'Pending' | 'Approved' | 'Active' | 'Inactive' | 'Rejected';
  rejection_reason?: string | null;
  created_by_id?: string | null;
  approved_by_id?: string | null;
  approved_at?: string | null;
  rejected_by_id?: string | null;
  rejected_at?: string | null;
  is_master: boolean;
  last_synced_at?: string | null;
  master_menu_id?: string | null;
  organization_id: number;
  brand_id: number;
  branch_id?: number | null;
}

/** Form-state shape for updating a Menu. Every field optional. */
export interface MenuUpdateFormState {
  name?: string;
  description?: string | null;
  valid_from?: string | null;
  valid_to?: string | null;
  priority?: number;
  status?: 'Draft' | 'Pending' | 'Approved' | 'Active' | 'Inactive' | 'Rejected';
  rejection_reason?: string | null;
  created_by_id?: string | null;
  approved_by_id?: string | null;
  approved_at?: string | null;
  rejected_by_id?: string | null;
  rejected_at?: string | null;
  is_master?: boolean;
  last_synced_at?: string | null;
  master_menu_id?: string | null;
  organization_id?: number;
  brand_id?: number;
  branch_id?: number | null;
}

/** Default-state factory for the create form. Pre-fills every locale key. */
export function emptyMenuCreateForm(): MenuCreateFormState {
  return {
    name: '',
    description: '',
    valid_from: '',
    valid_to: '',
    priority: 10,
    status: "Draft",
    rejection_reason: '',
    created_by_id: '',
    approved_by_id: '',
    approved_at: '',
    rejected_by_id: '',
    rejected_at: '',
    is_master: false,
    last_synced_at: '',
    master_menu_id: '',
    organization_id: 0,
    brand_id: 0,
    branch_id: 0,
  };
}

/** Convert create form state into the payload that baseMenuCreateSchema accepts. */
export function buildMenuCreatePayload(form: MenuCreateFormState): BaseMenuCreate {
  const payload: Record<string, unknown> = {
    name: form.name.trim(),
    description: form.description?.toString().trim() || null,
    valid_from: form.valid_from,
    valid_to: form.valid_to,
    priority: form.priority,
    status: form.status,
    rejection_reason: form.rejection_reason?.toString().trim() || null,
    created_by_id: form.created_by_id?.toString().trim() || null,
    approved_by_id: form.approved_by_id?.toString().trim() || null,
    approved_at: form.approved_at,
    rejected_by_id: form.rejected_by_id?.toString().trim() || null,
    rejected_at: form.rejected_at,
    is_master: form.is_master,
    last_synced_at: form.last_synced_at,
    master_menu_id: form.master_menu_id?.toString().trim() || null,
    organization_id: form.organization_id,
    brand_id: form.brand_id,
    branch_id: form.branch_id,
  };

  return payload as BaseMenuCreate;
}

/** Convert update form state into the payload that baseMenuUpdateSchema accepts. Only fields present on `form` are emitted. */
export function buildMenuUpdatePayload(form: MenuUpdateFormState): BaseMenuUpdate {
  const payload: Record<string, unknown> = {};
  if (form.name !== undefined) {
    payload.name = form.name?.toString().trim() ?? null;
  }
  if (form.description !== undefined) {
    payload.description = form.description?.toString().trim() ?? null;
  }
  if (form.valid_from !== undefined) {
    payload.valid_from = form.valid_from;
  }
  if (form.valid_to !== undefined) {
    payload.valid_to = form.valid_to;
  }
  if (form.priority !== undefined) {
    payload.priority = form.priority;
  }
  if (form.status !== undefined) {
    payload.status = form.status;
  }
  if (form.rejection_reason !== undefined) {
    payload.rejection_reason = form.rejection_reason?.toString().trim() ?? null;
  }
  if (form.created_by_id !== undefined) {
    payload.created_by_id = form.created_by_id?.toString().trim() ?? null;
  }
  if (form.approved_by_id !== undefined) {
    payload.approved_by_id = form.approved_by_id?.toString().trim() ?? null;
  }
  if (form.approved_at !== undefined) {
    payload.approved_at = form.approved_at;
  }
  if (form.rejected_by_id !== undefined) {
    payload.rejected_by_id = form.rejected_by_id?.toString().trim() ?? null;
  }
  if (form.rejected_at !== undefined) {
    payload.rejected_at = form.rejected_at;
  }
  if (form.is_master !== undefined) {
    payload.is_master = form.is_master;
  }
  if (form.last_synced_at !== undefined) {
    payload.last_synced_at = form.last_synced_at;
  }
  if (form.master_menu_id !== undefined) {
    payload.master_menu_id = form.master_menu_id?.toString().trim() ?? null;
  }
  if (form.organization_id !== undefined) {
    payload.organization_id = form.organization_id;
  }
  if (form.brand_id !== undefined) {
    payload.brand_id = form.brand_id;
  }
  if (form.branch_id !== undefined) {
    payload.branch_id = form.branch_id;
  }
  return payload as BaseMenuUpdate;
}
