<?php

namespace App\Omnify\Modules\FloatingSectionSchedule\Locales;

/**
 * Localized display names for FloatingSectionSchedule.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class FloatingSectionScheduleLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Floating Section Schedule',
        'ja' => 'フローティングセクションスケジュール',
        'vi' => 'Lịch trình khung giờ ưu đãi',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'start_time' => [
            'en' => 'Start Time',
            'ja' => '開始時刻',
            'vi' => 'Giờ bắt đầu',
        ],
        'end_time' => [
            'en' => 'End Time',
            'ja' => '終了時刻',
            'vi' => 'Giờ kết thúc',
        ],
        'start_date' => [
            'en' => 'Start Date',
            'ja' => '開始日',
            'vi' => 'Ngày bắt đầu',
        ],
        'end_date' => [
            'en' => 'End Date',
            'ja' => '終了日',
            'vi' => 'Ngày kết thúc',
        ],
        'days_of_week' => [
            'en' => 'Days of Week',
            'ja' => '曜日',
            'vi' => 'Ngày trong tuần',
        ],
        'is_active' => [
            'en' => 'Active',
            'ja' => '有効',
            'vi' => 'Hoạt động',
        ],
        'is_time_overridden' => [
            'en' => 'Time Overridden',
            'ja' => '時間上書き済み',
            'vi' => 'Đã ghi đè giờ',
        ],
        'priority' => [
            'en' => 'Priority',
            'ja' => '優先度',
            'vi' => 'Độ ưu tiên',
        ],
        'created_by_id' => [
            'en' => 'Created By',
            'ja' => '作成者',
            'vi' => 'Người tạo',
        ],
    ];
}
