<?php

namespace App\Omnify\Modules\RecallAffectedOrder\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\RecallResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class RecallAffectedOrderResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'recall_id' => $this->recall_id,
            'recall' => $this->whenLoaded('recall', fn () => new RecallResource($this->recall)),
            'customer_order_id' => $this->customer_order_id,
            'notification_channel' => $this->notification_channel,
            'notified_at' => $this->notified_at?->toISOString(),
            'notification_id' => $this->notification_id,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
