<?php

namespace App\Omnify\Modules\StockTransactionItem\Resources;

/**
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */

use App\Http\Resources\MaterialLotResource;
use App\Http\Resources\MaterialResource;
use App\Http\Resources\ProductSkuResource;
use App\Http\Resources\StockTransactionResource;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class StockTransactionItemResourceBase extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array<string, mixed>
     */
    public function toArray(Request $request): array
    {
        return $this->schemaArray($request);
    }

    /**
     * Transform the schema-defined fields into an array.
     *
     * @return array<string, mixed>
     */
    protected function schemaArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'stock_transaction_id' => $this->stock_transaction_id,
            'stockTransaction' => $this->whenLoaded('stockTransaction', fn () => new StockTransactionResource($this->stockTransaction)),
            'product_sku_id' => $this->product_sku_id,
            'productSku' => $this->whenLoaded('productSku', fn () => new ProductSkuResource($this->productSku)),
            'material_id' => $this->material_id,
            'material' => $this->whenLoaded('material', fn () => new MaterialResource($this->material)),
            'material_lot_id' => $this->material_lot_id,
            'materialLot' => $this->whenLoaded('materialLot', fn () => new MaterialLotResource($this->materialLot)),
            'quantity' => $this->quantity,
            'base_quantity' => $this->base_quantity,
            'unit' => $this->unit,
            'cost_basis_amount' => $this->cost_basis_amount,
            'unit_price' => $this->unit_price,
            'note' => $this->note,
            'created_at' => $this->created_at?->toISOString(),
            'updated_at' => $this->updated_at?->toISOString(),
        ];
    }
}
