<?php

namespace App\Omnify\Modules\OrderPaymentIntent\Locales;

/**
 * Localized display names for OrderPaymentIntent.
 *
 * DO NOT EDIT - This file is auto-generated by Omnify.
 * Any changes will be overwritten on next generation.
 *
 * @generated by omnify
 */
class OrderPaymentIntentLocales
{
    /**
     * Localized display names for the model.
     *
     * @var array<string, string>
     */
    public const DISPLAY_NAMES = [
        'en' => 'Order Payment Intent',
        'ja' => '注文決済インテント',
        'vi' => 'Intent thanh toán của đơn',
    ];

    /**
     * Localized display names for properties.
     *
     * @var array<string, array<string, string>>
     */
    public const PROPERTY_DISPLAY_NAMES = [
        'provider' => [
            'en' => 'Provider',
            'ja' => '決済プロバイダ',
            'vi' => 'Cổng thanh toán',
        ],
        'intent_id' => [
            'en' => 'Intent ID',
            'ja' => 'インテント ID',
            'vi' => 'Mã intent',
        ],
    ];
}
